### ISSUE TITLE
Getting participants in a call using the API

### ISSUE THREAD

**Issue by rugt0r** [microsoftgraph/microsoft-graph-comms-samples#102]
Hi
This is related to a post I made on Stackoverflow, but it didn't gain much traction and this seems like a better place for it.

When I try to request the list of participants in a call (as detailed on https://docs.microsoft.com/en-us/graph/api/call-list-participants?view=graph-rest-beta) the response suggests there are none. For example:

I place a call to the bot, and the calling endpoint receives a notification of an incoming call with id 471f0300-401f-4c4a-9967-3cee9a052519. The bot answers the call with a POST on:
`https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519/answer
`

The bot subsequently receives a message on the calling endpoint that the call has been established. I can query the graph about this call by making a GET:
`https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519
`

I get a response with code 200 and the details of the call in progress, so the call is clearly valid and accessible. However, if I attempt to get the list of participants with this GET:
`https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519/participants
`

I get a response with code 200, but the body contains the following:
`{"@odata.context":"https://graph.microsoft.com/beta/$metadata#app/calls('471f0300-401f-4c4a-9967-3cee9a052519')/participants","value":[]}
`

Shouldn't this contain the list of participants in the call? Is this implemented, and if so, is there an example of this working?

Thanks.

--

Edit:
Further to this, I am not getting a notification of the roster being updated when the bot invites participants. Assuming the bot invites someone to join the call with the above call Id, I issue a POST to:
`https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519/participants/invite`

The response contains the Id of a comms operation, and when the invitee accepts, the calling endpoint receives a message that the comms operation completed. I do not however get an update to the participants resource as detailed in [this piece of documentation.](https://docs.microsoft.com/en-us/graph/api/participant-invite?view=graph-rest-beta&tabs=http#notification---roster-updated-with-participant-added) I can't see that I'm doing anything wrong here. Any ideas?

**Comment by rugt0r** [comment]
Another issue is that I can't get the participant resource when I use the myParticipantId field which is returned when I GET the call. Surely I should at least be able to get this?

Example assuming the callId is 471f0300-401f-4c4a-9967-3cee9a052519: 
I perform a GET on:
` https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519`
I get back some JSON which includes the following:
`"myParticipantId": "64e965cf-3672-4a58-accd-6fdd162be212"`

I assumed I would be able to get the participant resource by doing the following:
`https://graph.microsoft.com/beta/app/calls/471f0300-401f-4c4a-9967-3cee9a052519/participants/64e965cf-3672-4a58-accd-6fdd162be212`

But instead I get a 404 with "Participant not found" as the message.

**Comment by rugt0r** [comment]
The inability to get participants is becoming a real problem for me, I'd like to try out audio routing groups but once again it seems I need to provide participant Ids. Does anyone else have this working?

**Comment by rugt0r** [comment]
Running the incident bot sample I see that a GET on calls/{id}/participants does actually work and I get a list of participants. That's when I follow the instructions in README.md and schedule a meeting, join it myself, then post on https://{botUrl}/joinCall with the meeting ID so the bot can join.

Can we only get participants from a pre-existing meeting the bot has called into? Or is there a way for the bot to get the participants in a call it has created?

**Comment by rugt0r** [comment]
I see this note on the documentation:
["Important: When a call is escalated from peer-to-peer to multiparty, not all multiparty features are available. Specifically, the bot will not receive roster updates."](https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta)

So we don't get roster update notifications for a call, but does this mean that we cannot access the roster at all? And if so, why? Tracking participants seems like basic functionality.

**Comment by ksikorsk** [comment]
@VinodRavichandran can you discuss the above subtleties?  It looks like gaps with escalation to me.  Any plan to address these?

**Comment by VinodRavichandran** [comment]
@zhengni-msft  Can you please evaluate this. Is it just documentation update or fixes?

**Comment by rugt0r** [comment]
Hi, I am now getting roster updates on escalated calls via the calling endpoint, as well as being able to request the list of participants on escalated calls doing beta/app/calls/{id}/participants. This is what we were after, thanks.

**Comment by Jopie64** [comment]
@rugt0r 
We're running into the same problem as you described in the first post of this thread:
Unable to get a list of participants of an incoming call. Also querying `myParticipantId` fails like you mentioned.

Since this issue is now closed, did you find a way to mitigate this?

**Comment by mwerghemmi** [comment]
Hi @zhengni-msft , @VinodRavichandran , @zhengni-msft, 
Is the support of communications/calls/{id}/audioRoutingGroups/{id}  still planned for the  Graph API ?  
this is a vry important feature for call centers Scenarios.. 
Any change to get this GA this year ? 
Many thank !

**Comment by guerital** [comment]
Any news on this bug?

**Comment by Mr-alaa** [comment]
i tried all and i got 
 "code": "BadRequest",
        "message": "Resource not found for the segment 'app'.",

**Comment by Warrior1st** [comment]
Anyone figured this out? I tried using the beta version as suggested but I still get value: [].
