### ISSUE TITLE
register calling bot via the Azure portal

### ISSUE THREAD

**Issue by mwerghemmi** [microsoftgraph/microsoft-graph-comms-samples#103]
Hi,  
Is it planned (may be already possible) to register a calling bot directly from the azure portal ?

**Comment by ksikorsk** [comment]
This is already [how it's done](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/register-calling-bot.html).  Add a "Bot Channels Registration" resource.
