### ISSUE TITLE
Exception after upgrading to .net 4.7.2

### ISSUE THREAD

**Issue by simra** [microsoftgraph/microsoft-graph-comms-samples#104]
**Describe the issue**
I'm attempting to deploy AudioVideoPlaybackBot using the .net 4.7.2 framework.

I need to update the bot to use .net 4.7.2 in order to consume some libraries, but I hit an issue with service start when I deploy.  I reproed the issue by cloning the repo, updating osFamily to "6", and updating FrontEnd and WorkerRole to use .NET 4.7.2.

During deployment the service fails to launch and continuously recycles with this exception:
````
Unhandled Exception: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. at Sample.AudioVideoPlaybackBot.FrontEnd.Bot.Bot.Initialize(Service service, IGraphLogger logger) at Sample.AudioVideoPlaybackBot.FrontEnd.Service.Start() ...
````

**Expected behavior**
At 4.6.2 the service starts normally.

**Graph SDK (please complete the following information):**
unsure.

**Call ID**
No call (error on deployment)

**Logs**
See exception above.

**Additional context**
None that seems relevant.

**Comment by alexisconia** [comment]
Hi @simra 
As mentionned into the nuget package, Microsoft.Graph.Communications.Calls.Media is dependant to .net framework 4.6.2 https://www.nuget.org/packages/Microsoft.Graph.Communications.Calls.Media/1.1.0-prerelease.581#

**Comment by simra** [comment]
Closing as we got this working with 4.6.2.
