### ISSUE TITLE
OnlineMeeting - GetOnlineMeeting Error

### ISSUE THREAD

**Issue by alexisconia** [microsoftgraph/microsoft-graph-comms-samples#11]
Hello,

When i try to get a meeting, i always get an error: 400 Bad Request.
The message is "Invalid Meeting Id".

I'm generated the meeting this the method CreateOnlineMeetingAsync.

Thanks

**Comment by nileshbits** [comment]
Hi @alexisconia - Could you post your request body here?

**Comment by kanchm** [comment]
We support retrieving meetings only for Cloud-Video-Interop users where a [VTC conference id](https://docs.microsoft.com/en-us/microsoftteams/cloud-video-interop-for-teams-set-up) is generated for the CVI licensed user.  We will be adding support for non-CVI ids but no timeline has been set.

The JoinURL contains all the details for a bot to join a meeting.  The meeting id lookup is to get the same details from a VTC conference id.

**Comment by alexisconia** [comment]
Thanks for your quick reply @kanchm! is it possible to mention it in the documentation or in a readme file?

**Comment by kanchm** [comment]
Documentation published recently.
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/onlinemeeting_get
