### ISSUE TITLE
Running Application hosted media bots on Windows Containers

### ISSUE THREAD

**Issue by midmohan** [microsoftgraph/microsoft-graph-comms-samples#110]
Is running Application hosted media bots  supported on Windows Containers,

I get the following errors while trying to run them on containers, Tried on multiple windows server core version from 2016 to the latest 2019 1903 version

Unhandled Exception: Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: mediaInitializationFailure
Message: Media platform failed to initialize
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Skype.Internal.Bots.Media.InternalMediaPl
atform' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Rtc.Intern
al.Media.MediaApi.dll' or one of its dependencies. The specified module could not be found.
   at Microsoft.Skype.Bots.Media.MediaApiPlatformWrapper.GetMediaApiProductVersion()
   at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform.FetchProductVersions()
   at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform..ctor()
   at Microsoft.Skype.Bots.Media.MediaPlatform.CreatePlatform()
   at Microsoft.Skype.Bots.Media.MediaPlatform.Initialize(MediaPlatformSettings settings, IConfigurationManager configM
anager, Boolean isTest)
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(IC
ommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(IC
ommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)

**Comment by ssulzer** [comment]
@midmohan 

This is not a tested scenario. There may be a problem with Windows Server Core, concerning Server Media Foundation. Can you please try a container running on full Windows Server 2016?

**Comment by midmohan** [comment]
Thanks @ssulzer

**Comment by anujb** [comment]
@midmohan just do confirm, did this work for you on a full Windows Server?

**Comment by InDieTasten** [comment]
I can confirm, that the microsoft provided base images are all unable to load the required assemblies, as VC++ Redists are missing.

The vc_redist.x64.exe can be added to the container during build and be executed silently like this:
```dockerfile
RUN Powershell.exe -Command \
$ErrorActionPreference = 'Stop'; \
$ProgressPreference = 'SilentlyContinue'; \
Start-Process c:\app\redist\vc_redist.x64.exe -ArgumentList '/passive' \
-RedirectStandardOutput 'c:\Windows\System32' -Wait ; \
Remove-Item c:\app\redist\vc_redist.x64.exe -Force
```

This only worked on the `mcr.microsoft.com/windows:1903` for me. Windows Server Core images are unable to install it this way.

**Comment by tares003** [comment]
Had encountered the same issue, I had to reupload the certificate which done the tick.

**Comment by half2me** [comment]
For me its working on `server` but not `servercore`. It would be nice if we could use `servercore` as its half the size. Is there some SDK or dependency that we could install into core to make it work?

**Comment by InDieTasten** [comment]
@half2me As far as I remember, it depends on windows features that are not shipped as a separate package, so no. You need a full Windows installation to make it work. Although I don't want to discourage you from taking a stab at it. Could violate some TOS though, idk.

**Comment by ssulzer** [comment]
@half2me @InDieTasten 
The bot media SDK does not support Windows Server Core, a media bot has to run on a full Windows Server image, as you've observed.
The reason is that the media engine within the SDK requires the Windows Media Foundation (WMF) runtime, which unfortunately is not supported on Server Core.
I am hoping at some point to get this WMF dependency removed from the SDK, so that we could run a media bot on Server Core. But currently I don't have an ETA.

**Comment by half2me** [comment]
@ssulzer thanks for the reply. If the WMF requirement is dropped, would that mean that it could possibly run on a linux machine with mono? Or should I not be that hopeful :')

**Comment by ssulzer** [comment]
Well, first we have to finish porting the SDK to .NET Core/.NET6, then remove the WMF dependency to enable support for Server Core. Next step after that, who knows :)

**Comment by half2me** [comment]
@ssulzer awesome stuff. If you ever need help with testing beta versions, let me know. I've been using the SDK for the past year now, and I'm quite interested in the internals.

**Comment by half2me** [comment]
> Well, first we have to finish porting the SDK to .NET Core/.NET6, then remove the WMF dependency to enable support for Server Core. Next step after that, who knows :)

Hey @ssulzer any updates on this? Have you managed to drop the WMF dependency?

**Comment by ssulzer** [comment]
Hi @half2me 
The WMF dependency will remain, we could not remove it. I am not sure if it is possible to get the WMF feature installed on Server Core, I've seen some postings claiming it can be done.
