### ISSUE TITLE
Tracking end of call while recording

### ISSUE THREAD

**Issue by SydorenkoEgor** [microsoftgraph/microsoft-graph-comms-samples#114]
Hey guys can you help me, with some strange case.
After my bot is answering on a call I start recording audio, and if I try to break a call while my bot is recording audio  method [[RecordAsync]](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/calls/Microsoft.Graph.Communications.Calls.ICall.html#Microsoft_Graph_Communications_Calls_ICall_RecordAsync_System_Nullable_System_Int32__System_Nullable_System_Int32__System_Nullable_System_Int32__System_Nullable_System_Boolean__System_Nullable_System_Boolean__System_Collections_Generic_IEnumerable_Microsoft_Graph_Prompt__System_Collections_Generic_IEnumerable_System_String__System_Action_Microsoft_Graph_Communications_Calls_RecordOperationResult__System_Threading_CancellationToken_) do not return, also [[CallOnUpdated]](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/client/Microsoft.Graph.Communications.Resources.IResource-2.html?q=OnUpdate#events) is not raising too

**Comment by ksikorsk** [comment]
> if I try to break a call while my bot is recording audio

Can you elaborate on this please?  If a call is ended/removed from the ICallCollection, all associated operations should be terminated.  How are you "breaking" the call?

**Comment by SydorenkoEgor** [comment]
@ksikorsk Case step by step:
1. QA from his account calling to bot
2. Bot answering the call and start recording
3. QA  Hang up the call

**Comment by michele-bernardinello** [comment]
@ksikorsk my bot can join a call but I don't get a call "terminated" notification and of course OnUpdated event is never called. What could be the problem in your opinion?

**Comment by httpiga** [comment]
Same problem here, any updates about this?

**Comment by cecchifabi** [comment]
Also here, would love to hear about it

**Comment by SydorenkoEgor** [comment]
We've tried to get raw data from socket connection during the call, and if you trying to do the same, make sure that you are participant of TAP program.

**Comment by michele-bernardinello** [comment]
Seriously graph doesn't send a call with the notification when the call ends? In CallHandler class there is CallOnUpdated method that should handle call terminated event
