### ISSUE TITLE
Redirect call to a user's voicemail

### ISSUE THREAD

**Issue by mwerghemmi** [microsoftgraph/microsoft-graph-comms-samples#115]
Hello,  
Is it possible to redirect a call to a user voicemail directly (mean the call should go to the voicemail without ringing the user) ? 
is  it documented somewhere ? 

Thx !

**Comment by ksikorsk** [comment]
Yes, you can create an `InvitationParticipantInfo` with `EndpointType = EndpointType.Voicemail` when inviting the user.

**Comment by LucidBijay** [comment]
@mwerghemmi  and @ksikorsk 
When I hit Inivite API by setting `EndpointType = EndpointType.Voicemail` , I am getting this issue:

`could not obtain destination from voicemail workflow`

Can you please help me with this?

**Comment by bijaykush** [comment]
@mwerghemmi and @ksikorsk
When I hit Inivite API by setting `EndpointType = EndpointType.Voicemail` , I am getting this issue:
`
could not obtain destination from voicemail workflow`

Can you please help me with this?

**Comment by mwerghemmi** [comment]
Hi @ksikorsk,  

are there any way to prevent a call to nbe transferred to voicemail. 
in my scenario now i want to transfer a call to a user but i dont want it to be transferred to its voicemail. 
by any chance are there a value for the EndpointType to say it should not be voicemail. 

Many thanks, 
Mefteh.

**Comment by mwerghemmi** [comment]
Hi @ksikorsk , 
The transfer to voicemail stops working starting Feb 2022. Any change on the API side (still possible )  ?
may be we just need to change body of our request when we transfer ? 

Many thanks for your response ! 
Mefteh.
