### ISSUE TITLE
Can not invite participant/participants to an active call

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-comms-samples#128]
I initiated a call from PSTN number to the Incident Bot. In the IncomingCallHandler.cs, I added the following code snippet to invite a team's user participant of the same tenant. Transfer to the same user works but invitation API doesn't.

**Code Snippet**
 var identity = new IdentitySet
                {
                    User = new Identity
                    {
                        Id = "user id of the participant from the same tenant",
                    },
                };

this.Call.Participants.InviteAsync(identity).ConfigureAwait(false);

**Expected behavior**
It should invite the participant of the same tenant. And the participants should be:
a) PSTN number
b) Incident Bot
c) Invited participant of the same tenant 

**Graph SDK (please complete the following information):**
 - Version [1.1.0-prerelease]

**Call ID**
Call Id: 451f0400-441f-4a82-8711-1ed759fc5cb6
Time:  11/22/2019 11:37 AM

**Logs**
 CommunicationsClient[1313972621]
      2019-11-22T11:36:17.4101Z 98484501-15a0-415c-bc69-d9bb0dbd624c pid:11588 tid:14 (CommunicationsClientExtensions.cs:217 LogRequestAndCreateResponse):
      {
        "@odata.type": "#microsoft.graph.commsNotifications",
        "value": [
          {
            "@odata.type": "#microsoft.graph.commsNotification",
            "changeType": "deleted",
            "resourceUrl": "/communications/calls/451f0400-441f-4a82-8711-1ed759fc5cb6/operations/1f215e0d-faac-45e3-b296-f97ddc803669",
            "resource": "(Generic: VxYVhw/w)",
            "resourceData": {
              "@odata.type": "#microsoft.graph.inviteParticipantsOperation",
              "participants": [
                {
                  "@odata.type": "#microsoft.graph.invitationParticipantInfo",
                  "identity": {
                    "@odata.type": "#microsoft.graph.identitySet",
                    "user": {
                      "@odata.type": "#microsoft.graph.identity",
                      "id": "user id the participant from the same tenant",
                      "tenantId": "(Generic: PLeWwKeL)"
                    }
                  }
                }
              ],
              "status": "failed",
              "clientContext": "f1b115f9-d1b1-4ae4-b25c-e7d4b8e63847",
              "resultInfo": {
                "@odata.type": "#microsoft.graph.resultInfo",
                "code": 500,
                "subcode": 9999,
                "message": "**addParticipantsfailed for participants: 8:orgid:7f8430e3-f688-41e7-b385-2731b68c4e9f reason: Audio-video modality controller could not invite participant to this conversation., code=580 subcode=5201**",
                "subcode": "(Generic: MWZZkZLK)"
              },
              "id": "1f215e0d-faac-45e3-b296-f97ddc803669"
            }
          }
        ]
      }
      {
        "AadApplicationIdentity": {
          "AppId": "xxxxxxxxxxx",
          "AppName": "IncidentBot"
        },
        "HttpLogData": {
          "TransactionDirection": "Incoming",
          "TraceType": "HttpRequest",
          "Url": "http://localhost:9442/callback/calling?webInstanceId=local",
          "Method": "POST",
          "Headers": [
            "Accept: application/json",
            "Authorization: (redacted)",
            "Host: localhost:9442",
            "User-Agent: Microsoft-Skype/3.0,(Calling/1.0)",
            "Scenario-Id: 98484501-15a0-415c-bc69-d9bb0dbd624c",
            "X-Forwarded-For: (redacted)",
            "X-Forwarded-Proto: (redacted)",
            "X-Microsoft-Skype-Chain-Id: 98484501-15a0-415c-bc69-d9bb0dbd624c",
            "X-Microsoft-Skype-Message-Id: 00fa12dc-0346-4568-a3c1-af91f7f40ada",
            "X-Original-Host: (redacted)",
            "Content-Type: application/json; charset=utf-8",
            "Content-Length: (redacted)"
          ]
        }
      }

**Additional context**

**Comment by ksikorsk** [comment]
Thanks for the thorough post.

I see that the original call was a P2P call.  Escalation of P2P to group call has been disabled as it was not fully supported.  @VinodRavichandran for timeline when this will be added.

Regards,
Kamil

**Comment by bijaykush** [comment]
Do we have any future plans to add this feature and support it fully? If yes, what would be the approximate time period?

**Comment by VinodRavichandran** [comment]
I can anticipate this to be available in CY20Q2.

**Comment by jingxianli** [comment]
We tested user in the same tenant and it works. 
However, if we invite a PSTN destination from the group call/bot, does not work.

If the caller of the original call which is converted to a group call is PSTN number, we receive this error:
"403 forbidden Call does not contain the metadata required for making this PSTN dial out".

If the caller of the original call which is converted to a group call is a teams user within the tenant, we receive this error:
"412 conditional failure Could not find the PSTN content for the sponsor of this PSTN leg".

Is there any configuration required for PSTN INVITE or is this feature not available for PSTN destination yet?

Any feedback is appreciated.
