### ISSUE TITLE
Forward the incoming call events from the calling bot to own application for call handling functions like answer, mute, unmute, transfer, etc

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-comms-samples#129]
I am building a unified communication channel platform. 

I had used Incident bot to receive an incoming call from a user (PSTN and Teams user). And also tried call control functionality like the answer, transfer, mute, unmute, outbound call, recording, etc. It worked as expected.

Now instead of handling call control functions like the answer, reject, transfer directly from the bot, I want to forward that incoming call events to my own application. 
My application will use Microsoft.Graph.Communication.Call to handle the call flow on the incoming events from bot application, as currently, Incident Bot is doing in the sample application. So that the incoming call events flow through the workflow of my application and find an agent based on the business logic and then the agent will answer, reject, transfer, etc the call.

Is it necessary to include calling bot in the active call or we can just forward the incoming call events from Bot to our own application and can control the call flow as per our need?

**Comment by mwerghemmi** [comment]
Hi @bijaykush , 
I am able to receive calls directly on my application. all what you need to do is to set its url in the Azure bot calling cllback url. ( my be i missunderstood the questions ? )  
I think you need to start from the sample bot and update the code to implement you business logic. 

For my side i was not able to get calls from PSTN to my bot/ aplication. Can you please share how you acheived that ? 
Mefteh.

**Comment by bijaykush** [comment]
@mwerghemmi 

I just tried with this approach and was able to receive the incoming call from PSTN (Mobile hangout for now).

I am also looking to know if we can use Sip.JS for receiving and making calls from the front-end. To be specific, I want to receive the incoming call from my own application (like call.Answer) and then after invoke a calling box in my front-end app for an agent, then the agent will accept the call (hit call.invite API to add that agent to the active call). 

I think we need SIP.JS to communicate the with call control functionality of MS-Teams from front-end, and I am not sure about the configuration to start?

**Comment by mwerghemmi** [comment]
Thx @bijaykush, 
can you please share the permissions you granted to your application ?  
I bleive SIP.js is not compatible with Teams client. someone from MS wuld have more details may be.

**Comment by bijaykush** [comment]
@mwerghemmi 
The permission I granted to my app is:
Calls.AccessMedia.All
Calls.Initiate.All
Calls.JoinGroupCall.All
Calls.InitiateGroupCall.All
Calls.JoinGroupCallAsGuest.All

Do you have any idea how to handle the situation like sending an invitation to the front-end (agent) and make him accept the call by clicking an "Accept Call" button? I am now clear about the process of back-end but not sure about the font-end handling process.

**Comment by bijaykush** [comment]
I found the way to use directly our custom application instead of the BOT application.

Since I have created a new issue regarding front-end scenario, I am closing this ticket.

**Comment by babunirwan** [comment]
Hi,

I am also trying incoming PSTN calls. Set up is done and assigned number to BOT too. When I call that number I reach bot and I am using calling bot sample which plays an audio file. But how to change logic to send it to some queue or some agent.
The webhook url is also set up and working. Can you please help with some sample logic how to send call to some queue or agent from bot for incoming calls. Thanks
