### ISSUE TITLE
Compliance Bot does not fire OnVbssMediaReceived and no media received in application

### ISSUE THREAD

**Issue by pavanjains** [microsoftgraph/microsoft-graph-comms-samples#130]
I am using the Compliance Bot from Sample. When I make a video call to Bot things works fine I see OnVideoMediaReceived getting called and also buffers with data however when I do only screen share I do not see  OnVbssMediaReceived getting called. I can see media reaching my setup in wireshark but the call back does not get called.

Below is the logs from VS 

'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Tokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Protocols.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating the RenderMediaSession for modality Audio
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the RenderMediaSession for modality Audio
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Audio Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Recvonly audio socket created
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.Skype.Internal.Media.H264.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Recvonly video socket created with mediaType: Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the RenderMediaSession for modality Video
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Video Render Media Session
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Creating Video SourceProvider and attaching to consumer
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created Video SourceProvider and attached to consumer
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Recvonly video socket created with mediaType: Vbss
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Binding MPMediaSession Id 8476d896-ad79-40da-87aa-cdbde7d4f234 to the VideoSocket: 0
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Binding MPMediaSession Id 8476d896-ad79-40da-87aa-cdbde7d4f234 to the VideoSocket: 1
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Binding MPMediaSession Id 8476d896-ad79-40da-87aa-cdbde7d4f234 to the VideoSocket: 2
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Binding MPMediaSession Id 8476d896-ad79-40da-87aa-cdbde7d4f234 to the VbssSocket
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Binding MPMediaSession Id 8476d896-ad79-40da-87aa-cdbde7d4f234 to the media Sockets
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Adding a reference on MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket with Id 0 is bound to the mpMediaSession with id 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Adding a reference on MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket with Id 1 is bound to the mpMediaSession with id 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Adding a reference on MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket with Id 2 is bound to the mpMediaSession with id 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Adding a reference on MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Adding a reference on MPMediaSession with ID: 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket with Id 0 is bound to the mpMediaSession with id 8476d896-ad79-40da-87aa-cdbde7d4f234
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] MpMediaSession 8476d896-ad79-40da-87aa-cdbde7d4f234 is bound to all the media sockets
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] Created the media configuration: {{
  "mpUri": "net.tcp://pavan-media.XXXXX.com:25605/MediaProcessor",
  "audioRenderContexts": [
    "d460b5ef-bb5f-4163-aec8-d1f4db939380"
  ],
  "videoRenderContexts": [
    "7eaa754d-a835-4ba8-841f-d82824f97909",
    "fc2331c2-4e34-450c-bd56-4b4d93c12e45",
    "af0bc651-ab5e-4c34-8033-846991c65a27"
  ],
  "vbssRenderContexts": [
    "54d3778a-b61d-47a6-8a7e-e67f8a6dc533"
  ],
  "audioSourceContexts": [
    null
  ],
  "videoSourceContexts": [],
  "vbssSourceContexts": [
    "20897f27-77b4-41e3-a87d-a8326dc08054"
  ],
  "dataRenderContexts": null,
  "dataSourceContexts": null,
  "supportedAudioFormat": "Pcm16K",
  "videoSinkEncodingFormats": [
    "H264",
    "H264",
    "H264"
  ],
  "vbssSinkEncodingFormats": [
    "H264"
  ],
  "initialScreenSharingRole": "Viewer",
  "mpMediaSessionId": "8476d896-ad79-40da-87aa-cdbde7d4f234",
  "regionAffinity": null,
  "skypeMediaBotsVersion": "1.13.1.0324",
  "mediaStackVersion": "2019.28.1.6",
  "mpVersion": "7.2.0.5523",
  "callId": "4d1f0500-421f-4547-8b46-3e7b17d7e9b9"
}}
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.30::12/02/2019-16:11:28.683.00000176 (AVMP,GetCapabilitiesWorkItemBegin:MediaProcessor.cs(1781)) [MP] MPProxy client's Service Contract version (63) is newer than current Service Contract Version (57).
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:29.688.000001F8 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:30.029.00000270 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:30.091.000002A7 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:30.099.000002DF (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:30.112.00000317 (AVMP,BeginCreateStream:Endpoint.cs(305)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e][MP] Failed to get public ip mapping. Endpoint type  
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket 1 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket 0 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : [SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket 2 Video: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Information: 0 : 'WaWorkerHost.exe' (CLR v4.0.30319: WaWorkerHost.exe): Loaded 'C:\vbrick\microsoft-graph-comms-samples-master\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\csx\Debug\roles\CRWorkerRole\approot\Microsoft.Rtc.Internal.Media.MediaApi.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[SkypeBotsMediaPlatform][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] [CallId:4d1f0500-421f-4547-8b46-3e7b17d7e9b9] VideoSocket 0 Vbss: Not raising video receive status changed event, the VideoReceiveStatusChanged handler is null
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.26::12/02/2019-16:11:30.757.000005BB (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e]Raising media quality changed event for Stream: ca32f044-2a64-4e3c-8562-ca7db938e272
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.24::12/02/2019-16:11:30.776.000005C1 (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e]Raising media quality changed event for Stream: eb06e671-dd5c-41b8-95b6-4e9031a2ab1a
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.49::12/02/2019-16:11:30.776.000005C5 (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e]Raising media quality changed event for Stream: 00cf8cfe-ac2f-491c-87e0-73a47743c9f9
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.29::12/02/2019-16:11:30.801.000005F7 (AVMP,ProcessMediaQualityChanged:Stream.cs(1864)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]:[pid:4c4cbe46-131b-4d3d-840b-53ed04902a9e]Raising media quality changed event for Stream: 806bbdda-bc4a-4ff8-9ff4-b5678bd085a9
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.23::12/02/2019-16:11:30.870.0000061C (AVMP,ProcessDominantSpeakerChanged:Context.cs(3252)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13]ProcessDominantSpeakerChanged: PreviousDominantAudioChannel field of RtpDominantSpeakerChangedEvent is null.
TraceSource Warning: 0 : [AvMP][AppId:e8459a67-c315-445f-abf4-588c8da4bdb5] TL_WARN(TF_COMPONENT) [EN-PJAIN]117980.23::12/02/2019-16:11:30.875.00000627 (AVMP,RaiseDominantSpeakerChangedEvent:Context.cs(3976)) [cid:6df77b61-d05b-4c48-ba74-912e37015a13][MP] Raising dominant speaker changed event. MediaSourceId: 4294967295, DSHistory is null

**Comment by ssulzer** [comment]
@pavanjains 
I don't see any evidence of the bot subscribing to the VBSS source (MediaSourceId 2) in the meeting associated with CallId 4d1f0500-421f-4547-8b46-3e7b17d7e9b9, hence the bot will not receive any screen sharing video frames.

(Note, it's sufficient to give just the CallId, and an approximate timestamp if available, and not all this log output. Thanks.)

@ksikorsk Do you know if the sample bot handles VBSS?

**Comment by ksikorsk** [comment]
I don't see any logic in the bot that handles VBSS... this should be added as it is relevant for all CR bots.

**Comment by pavanjains** [comment]
Thanks @ssulzer  and @ksikorsk How can I stay tuned to know when it is added will you be opening another issue for this?

**Comment by saraswat40** [comment]
@pavanjains how do you get the bot to join the call? What is the exact request you are sending? Thanks

**Comment by pavanjains** [comment]
@saraswat40 I added the Bot into teams and then share the content thru Share content button. I noticed that when video call is made this way share content is disabled

**Comment by saraswat40** [comment]
@pavanjains I am not sure how you added the bot to teams. Typically the bot needs to be invited to a call via an HTTP request. This is how it was done in the AudioVideoPlaybackBot.

**Comment by pavanjains** [comment]
@saraswat40 I created the zip file using App studio and then did a custom upload of app. I know how to make the Bot join the meeting and that worked but I didnt know how to call a participant or do a pt-pt call from Bot, is there a API similar to joinCall with url for pt-pt call that I can use?

**Comment by saraswat40** [comment]
@pavanjains Are you calling the bot directly in msteams?

For a multiparty call, I usually create a meeting in msteams calendar. There is a join url in the meeting invite and anyone can join the call using that meeting invite. I have not tried an experiment where the bot starts the call and invites other people to join.
