### ISSUE TITLE
ComplianceBot Grant-CsTeamsComplianceRecordingPolicy not working ( probably )

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#133]
**Describe the issue**
I am trying to follow the documentation as described in the ComplianceBot. The Grant-CsTeamsComplianceRecordingPolicy step goes thru without any errors, but I don't think the policy actually gets associated with the user. See powershell commands below.

PS > Get-CsTeamsComplianceRecordingPolicy

Identity                        : Global
ComplianceRecordingApplications : {}
Enabled                         : False
WarnUserOnRemoval               : True
Description                     :

Identity                        : Tag:TESTPOLICY
ComplianceRecordingApplications : {Id=37553c7e-831e-4087-968f-79ea3eabed9c;RequiredBeforeMeetingJoin=True;RequiredBeforeCallEstablishment=True;RequiredDuringMeeting=True;RequiredDuringCall=True;ConcurrentInvitationCount=1}
Enabled                         : True
WarnUserOnRemoval               : True
Description                     : Test policy created by Prashant

PS > Grant-CsTeamsComplianceRecordingPolicy -Identity prashant@thetalake.com -PolicyName TESTPOLICY -Tenant cd2c5a75-c821-42a8-8c41-775b48d8d206

PS > Get-CsOnlineUser prashant@thetalake.com | ft sipaddress, tenantid, TeamsComplianceRecordingPolicy

SipAddress                 TenantId                             TeamsComplianceRecordingPolicy
----------                 --------                             ------------------------------
sip:prashant@thetalake.com cd2c5a75-c821-42a8-8c41-775b48d8d206

Please let me know if I missed something.

**Comment by saraswat40** [comment]
Overnight this issue got resolved somehow. Now, the policy is associated with the user:
Get-CsOnlineUser prashant@thetalake.com | ft sipaddress, tenantid, TeamsComplianceRecordingPolicy

SipAddress                 TenantId                             TeamsComplianceRecordingPolicy
----------                 --------                             ------------------------------
sip:prashant@thetalake.com cd2c5a75-c821-42a8-8c41-775b48d8d206 TESTPOLICY

When I start a call as this user, I get a message that the recording has started. About 60 seconds later, I get another message that the recording has ended. Is there a way to increase the length of the recording? Also where is the recording stored?

**Comment by ksikorsk** [comment]
It normally takes 30-60 seconds for the policy to be applied.  Please let me know if you find it takes much longer than this.

**Comment by saraswat40** [comment]
Helllo, it took significantly longer than that. More like several days. As you can see the logs I posted, yesterday the policy was not associated with the user. This morning it somehow got associated with the user.

Can you kindly please answer the other two questions?

**Comment by ksikorsk** [comment]
> When I start a call as this user, I get a message that the recording has started. About 60 seconds later, I get another message that the recording has ended. Is there a way to increase the length of the recording? Also where is the recording stored?

The bot has logic to publish the recording states.  It does not actually do any recording.
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/06b6ef2849a03123ea5177bd02d1eb4a83ec56ba/Samples/BetaSamples/LocalMediaSamples/ComplianceRecordingBot/FrontEnd/Bot/CallHandler.cs#L136-L138
