### ISSUE TITLE
SDK update for the communications API

### ISSUE THREAD

**Issue by paulnearney** [microsoftgraph/microsoft-graph-comms-samples#135]
Now that the calls and online meetings functionality has moved from Beta into GA under v1.0 of the Graph API, when can we expect an updated and supported SDK?

**Comment by ksikorsk** [comment]
We just published the v1.0 SDKs :)

Next steps is to update the samples to leverage these SDKs, that will come in the coming days.

**Comment by ksikorsk** [comment]
https://www.nuget.org/profiles/GraphCommunications

**Comment by paulnearney** [comment]
Wow, that was genuinely in the last few minutes wasn't it :) Thanks!
