### ISSUE TITLE
ICall.CancelMediaProcessingAsync missing in SDK 1.2.01 

### ISSUE THREAD

**Issue by paulnearney** [microsoftgraph/microsoft-graph-comms-samples#136]
ICall.CancelMediaProcessingAsync appears to have been removed in v1.2.0.1 of the communications SDK, and I can't see an equivalent. Is there another way to stop prompts playing, or is this feature unavailable for now?

**Comment by ksikorsk** [comment]
That's right, this endpoint has not yet been released to v1.0.  If you require this please continue to use the `-beta` SDK and endpoint.

**Comment by ksikorsk** [comment]
> Is there another way to stop prompts playing, or is this feature unavailable for now?

You cannot stop playing prompts, but you can barge-in with another prompt.  This endpoint will be released, but I don't yet have a timeline.  Perhaps @VinodRavichandran  can help here.

**Comment by paulnearney** [comment]
OK, thanks - it's not a showstopper for me at the moment, I'll check again in a few weeks
