### ISSUE TITLE
Error 403 inviting a federated user to a meeting - Request authorization tenant mismatch (7505)

### ISSUE THREAD

**Issue by paulnearney** [microsoftgraph/microsoft-graph-comms-samples#144]
**Describe the issue**
Using the Beta API, Tenant A runs a multi-tenant bot which creates an onlineMeeting and invites a participant to it. The organizer is a user belonging to Tenant A. If the participant being invited belongs to Tenant A, the Invite succeeds.

However, When a user belonging Tenant B is invited, the request is forbidden. Tenant A and Tenant B both have open federation (no entries at all in the allow/block lists). Tenant B has also granted admin consent to the Bot Application (although i'm not sure yet if this is necessary)

**Code Snippet**
Request
```
POST https://graph.microsoft.com/beta/communications/calls/4b1f0900-461f-4c4b-a2ff-eb4d14e9699c/participants/microsoft.graph.invite HTTP/1.1
Host: graph.microsoft.com
Scenario-Id: 8dc44ce5-1e96-4b9f-b632-222fb94e42fe
Client-Request-Id: a03e068a-35ae-42a8-9b1f-aa6e8d1cea68
User-Agent: GraphCommunicationsClient-Bot/1.1.0.2237
Authorization: Bearer *****
Request-Context: appId=cid-v1:*****
Request-Id: |d52f4f3a2aceec47bf7a6467525bc7ca.7a7ee64d7b912c4b.
traceparent: 00-d52f4f3a2aceec47bf7a6467525bc7ca-7a7ee64d7b912c4b-00
Content-Type: application/json; charset=utf-8
Content-Length: 362

{
  "participants": [
    {
      "@odata.type": "#microsoft.graph.invitationParticipantInfo",
      "identity": {
        "@odata.type": "#microsoft.graph.identitySet",
        "user": {
          "@odata.type": "#microsoft.graph.identity",
          "id": "*****",
          "identityProvider": "AAD",
          "tenantId": "*****"
        }
      }
    }
  ],
  "clientContext": "bd345a3e-a426-40f5-9977-21f3045773c9"
}
```

Response
```
HTTP/1.1 403 Forbidden
Cache-Control: private
Content-Type: application/json
request-id: 298899d5-5416-47e5-a748-c3a274bae716
client-request-id: a03e068a-35ae-42a8-9b1f-aa6e8d1cea68
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_2"}}
scenario-id: 8dc44ce5-1e96-4b9f-b632-222fb94e42fe
Strict-Transport-Security: max-age=31536000
Date: Fri, 03 Jan 2020 15:11:43 GMT
Content-Length: 228

{
  "error": {
    "code": "7505",
    "message": "Request authorization tenant mismatch.",
    "innerError": {
      "request-id": "298899d5-5416-47e5-a748-c3a274bae716",
      "date": "2020-01-03T15:11:44"
    }
  }
}
```

**Expected behavior**
I would expect the federated user to be invited to the meeting

**Graph SDK (please complete the following information):**
Beta

**Comment by paulnearney** [comment]
Hi all, any update on this? Is inviting federated users to a meeting supported?

**Comment by ksikorsk** [comment]
> Is inviting federated users to a meeting supported?

@satyakonmsft

**Comment by ananmishr** [comment]
Hi @paulnearney , no we don't support inviting federated users to a meeting

**Comment by paulnearney** [comment]
I'm trying this again, and still getting the same response, so I assume this is still not supported. Can you confirm if there are any plans to support this feature? @satyakonmsft, @ananmishr

**Comment by satyakonmsft** [comment]
Hi @paulnearney , we do not have plans to support this at this time.
