### ISSUE TITLE
Spec of Complaint Bot feature

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#149]
I understand that this feature is beta because the sample is currently under beta folder. Is it still possible to give us some spec document or reference of PowerShell commands used in README.md? I myself did not find such document online. If it's not available, could you answer those questions at this time?
- PowerShell script enables this recording per each user. Is it possible to enable it for all users in a specific user group?
-  If this feature is enabled for two or more of participants in the call/meeting, are multiple number of bots launched? Or, is it just one bot per each call/meeting?

**Comment by ksikorsk** [comment]
I don't know of any spec for the CR cmdlets.  A different team writes these, and I don't believe they have a github presence.  Once they are released to PROD I do believe they will be documented:
https://docs.microsoft.com/en-us/powershell/module/skype/new-csonlineapplicationinstance?view=skype-ps

> PowerShell script enables this recording per each user. Is it possible to enable it for all users in a specific user group?
- I am not sure, you would have to experiment here.  Perhaps a scheduled script that fetches all users in a user group and applies the policy.  I am not an expert in the cmdlets.

> If this feature is enabled for two or more of participants in the call/meeting, are multiple number of bots launched? Or, is it just one bot per each call/meeting?
- If a user is under compliance, there is an invite per Recorded Party (RP) endpoint.  So if RP joins via mobile and desktop, there would be 2 separate invites.  If another RP joins there will be a separate invite.  The calls are terminated for each endpoint leaving, so if the first user from the above example leaves on mobile, only that call instance will be terminated.

**Comment by hohno-panopto** [comment]
Kamil,
Thank you for the information.

> > PowerShell script enables this recording per each user. Is it possible to enable it for all users in a specific user group?
> 
> * I am not sure, you would have to experiment here.  Perhaps a scheduled script that fetches all users in a user group and applies the policy.  I am not an expert in the cmdlets.

I understand it's unclear whether PS cmdlets or not.
Putting aside cmdlets, does compliant bot feature itself support applying the policy per user group, as the spec?

**Comment by ksikorsk** [comment]
Not that I am aware of.  Only tenant admins can use the cmdlet.
