### ISSUE TITLE
Communication SDK - handling of notifications

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#150]
As far as I understand, it is Bot application's responsibility to provide webhook endpoints to receive notifications from Graph Platform and pipe it to communication SDK. [This section](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/client/index.html#notification-handling) says as simple as hooking up a single URL and passes the request through to ProcessNotificationAsync method. However, PlatformCallContrller.cs of Compliance Bot example has at least two endpoints and does more than pass through. Could you explain what exactly bot code needs to do?

**Comment by ksikorsk** [comment]
You can do everything via a single endpoint, however the sample has a separate endpoint for the initial "incoming call" notification, and all subsequent "live call" notifications.  This is done in case the bot developer (you) need to have different logic for incoming call vs subsequent notifications.

In the sample, there is space to evaluate any policies the bot may have on the Recorded Party (RP).  
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b54647fd8b2b4c7fd282291123c18bf0b3038f5/Samples/BetaSamples/LocalMediaSamples/ComplianceRecordingBot/FrontEnd/Http/Controllers/PlatformCallController.cs#L166

Once such policy may be that the the recording can only happen in Europe, and so the bot can react and redirect the incoming call request to a different region.
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b54647fd8b2b4c7fd282291123c18bf0b3038f5/Samples/BetaSamples/LocalMediaSamples/ComplianceRecordingBot/FrontEnd/Http/Controllers/PlatformCallController.cs#L230-L233

You would not want this policy evaluation to run for each request going to the bot, this is why there are 2 controllers (one with policy evaluations and one without).

**Comment by hohno-panopto** [comment]
Thank you very much for the explanation!
