### ISSUE TITLE
Scale out of Media Bots

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#153]
Can you explain or point out the code location how multiple bot instances (VMs) may run against a single Media Bot configuration? As far as I understand, calling bot may be configured with only a single webhook (by [this step](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/register-calling-bot.html)). Due to Media Bot's stateful nature, all notifications which belong to the same call/meeting must go to the same instance (VM), but I do not expect load balancer can do that automatically. Does Bot need to write a code to give any hint to the load balancer? Or, does calling SDK have any magic to handle this aspect?

**Comment by ksikorsk** [comment]
by "same instance" we mean the same instance where the call was answered, but not necessarily the same instance where other calls have been answered.

Lets say you have 3 VMs.  The LB sends the incoming call notification for call1 to VM1.  All subsequent notifications for call1 must land on VM1.  But a new incoming call call2 can land on any instance.

**Comment by hohno-panopto** [comment]
I understand that requirement is within the same call only.
It is still true that LB is expected to send *all* notifications of a single call to the same VM.
How is it achieved?

**Comment by ksikorsk** [comment]
> It is still true that LB is expected to send all notifications of a single call to the same VM.
yes, by call we mean Graph call, not for each participant involved in the group call.

> How is it achieved?
In the samples the Cloud Service cluster is behind a VIP.  Each VM is addressable from the outside via public IP and Port: (ex: https://sample.cloudapp.net:9444).  The callback URL for each instance is defined here on instance start:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/15b8070a5b65ee0829823bbd7d0fa5d527ba8879/Samples/BetaSamples/LocalMediaSamples/ComplianceRecordingBot/WorkerRole/AzureConfiguration.cs#L197-L221

**Comment by hohno-panopto** [comment]
Hi @ksikorsk 
I am sorry for a long silence. I tested a little more after that.
Are below correct understandings, if I deploy this compliance bot sample as-is to multiple VM instances (worker roles)?

1. Each worker role instance waits for the incoming call at shared endpoint https://foo.cloudapp.net/api/calling (port 443).

2. Graph notifies the incoming call at the above endpoint, and LB dispatches the request to one of instances.

3. The chosen instance tells Graph to use https://foo.cloudapp.net:1010x/api/calling/notification. This port number is unique between instances (10100, 10101, 10102,...). Therefore, the Graph continues to deliver the notifications related to this call to the same instance.

4. Also the chosen instance tells Graph to deliver media samples to net.tcp://foo.cloudapp.net:2010x/MediaProcessor. This port number is also unique between instances  (20100, 20101, 20102,...). Therefore, the Graph continues to deliver the media samples of this call to the same instance.

5. A single bot instance may handle multiple calls. Bot class is instantiated only as a singleton in VM instance. On the other hand, BotMediaStream object is created for each incoming call inside the VM instance.

6. Horizontal scaling is achieved by putting multiple  instances under LB and let LB distribute the load among available instances at step 1. Also auto scaling is applicable to this scenario.

And finally, is it the best option to use Cloud service (classic) to this type of applications? Or, should I consider to use Azure Service Fabric with some reason?

**Comment by ksikorsk** [comment]
@ananmishr @yizhenww @mathowar @paywuAtMicrosoft

**Comment by paywuAtMicrosoft** [comment]
If you are using Cloud service (classic) at the moment, there is no need to switch to Azure Service Fabric.

**Comment by hohno-panopto** [comment]
@paywuAtMicrosoft Thank you very much for the guidance that Cloud service (classic) is good enough for this type of application.

Can you or anyone lese confirm if my understanding about scaling behavior of this sample is correct?

**Comment by mathowar** [comment]
Yes, this scaling behavior is what I expect.

**Comment by hohno-panopto** [comment]
Thank you @mathowar. We'll design our product code following the same pattern.
