### ISSUE TITLE
Compliance recording bot stops recording itself and want to download the recording to local storage.

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-comms-samples#158]
@ksikorsk and others who can help with this.

I ran the compliance recording bot locally by following the instructions. I am being able to make/receive the call on a recorded user(Teams's user with assigned recording compliance policy) from/to non-recorded users as shown in the screenshot
![Compliance Recording Bot Success Case](https://user-images.githubusercontent.com/11793622/72881556-11cfb580-3d29-11ea-91df-933adc7bab03.png)

I found that call recording gets stopped in approx 1 min duration while the call continues. Do we need to do something else to record the entire call. Again I am also looking to download the recording in my local storage. **Where can we find the recorded file(i.e. audio/video file) and what is the URI to download that file?**

**Note**: I tried the compliance recording bot in by hosting in cloud service too. I am having the same limitation i.e. recording stops within 1 min.

**Comment by ksikorsk** [comment]
@bijaykush that's what the sample does, it toggles the recording status every minute, then ejects the recorded party after it's rolled over all the status`.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b54647fd8b2b4c7fd282291123c18bf0b3038f5/Samples/BetaSamples/LocalMediaSamples/ComplianceRecordingBot/FrontEnd/Bot/CallHandler.cs#L108-L147

The sample does not actually do any recording.  That is the responsibility of the bot developer.

**Comment by bijaykush** [comment]
Thanks @ksikorsk 
I will look into it.

**Comment by bijaykush** [comment]
@ksikorsk 

I m trying to record the audio in the following function of BotMediaStream.cs

```
 private void OnAudioMediaReceived(object sender, AudioMediaReceivedEventArgs e)
        {
            this.GraphLogger.Info($"Received Audio: [VideoMediaReceivedEventArgs(Data=<{e.Buffer.Data.ToString()}>, Length={e.Buffer.Length}, Timestamp={e.Buffer.Timestamp})]");

            // TBD: Compliance Recording bots can record the Audio here
            e.Buffer.Dispose();
        }
```
At this function, we get the buffer data in **AudioMediaBuffer** model. 

I am looking a way to convert this data into the audio file i.e. wav format.

Any help/pointer would be appreciated.

**Comment by bijaykush** [comment]
@ksikorsk 
I am looking for the process/pointer/sample to get those incoming buffer data into a local disk/blob and convert those files to an audio file for example wave file.

Do I need to create a new ticket for this to run a new thread about recording real-time calls in compliance recording bot, since this thread is closed by you?

**Comment by ksikorsk** [comment]
@ssulzer

**Comment by aarushi-mittal** [comment]
Hi @bijaykush  were you able to solve this ?

**Comment by WezMorris** [comment]
Did anybody get anywhere with this?

**Comment by bijaykush** [comment]
@WezMorris and @aarushi-mittal 

For recording the audio on local storage, I tried to save the audio data in a byte array and at the end of the call, I converted those byte array data into audio (mp3, wave) format.

And to remove the auto stopping the recording by MS Teams, you need to change the logic of OnRecordingStatusFlip as per your wish in compliance recording bot code sample.

**Comment by WezMorris** [comment]
Could you share a code snippet? I'm trying to save the audio (e.Buffer.Data) and getting tiny unreadable wav files.

**Comment by WezMorris** [comment]
That does help, thanks.

Then do you write the byte array to a file in the CallOnUpdated function in the callhandler?

**Comment by bijaykush** [comment]
Yup.

**Comment by lcarli** [comment]
@bijaykush Can you please share your snippet? I didn't get what is the type of finalDataBytes and how can I save into a file (after the calls end)...

**Comment by skaro** [comment]
I've done something similar to the above using the Marshal.Copy but my file is always empty - the size seems correct as though it's getting the right length of the audio stream, but the content of the file is complete blank.  If I just dump out the unmanaged buffer as a string, I get numeric values back which suggests there's something in the buffer.  Did anyone else hit this issue and if so, what's the solution :)

**Comment by WezMorris** [comment]
Could you post your function?

**Comment by skaro** [comment]
> Could you post your function?

I'm sorted now - thank you for replying though.

**Comment by ucodes** [comment]
> 
> 
> > Could you post your function?
> 
> I'm sorted now - thank you for replying though.

Hi skaro - what was the issue there? im also getting an empty managed array

        private void OnAudioMediaReceived(object sender, AudioMediaReceivedEventArgs e)
        {
            this.GraphLogger.Info($"Received Audio: [VideoMediaReceivedEventArgs(Data=<{e.Buffer.Data.ToString()}>, Length={e.Buffer.Length}, Timestamp={e.Buffer.Timestamp})]");
            var buffer = e.Buffer;
            try
            {
                    long length = buffer.Length;
                    var retrievedBuffer = new byte[length];
                    Marshal.Copy(buffer.Data, retrievedBuffer, 0, (int)length);
                    this.AudioDataBytesAdd(retrievedBuffer);
            }
            catch (Exception ex)
            {
                this.GraphLogger.Info($"got an exception while extracting media data from unmanaged array, {ex.Message.ToString()}");
            }
            finally
            {
                buffer.Dispose();
            }
        }

**Comment by skaro** [comment]
The first call never records anything.  After that it records perfectly each time.  Someone has raised it as a separate issue.

**Comment by ucodes** [comment]
> 
> 
> The first call never records anything. After that it records perfectly each time. Someone has raised it as a separate issue.

thanks for the quick response - but seems in my case the issue is somewhere else - no matter how many calls were made, its always blanks
![_Capture](https://user-images.githubusercontent.com/38291347/92471814-3bb6e900-f1e1-11ea-87f5-21b412bea614.JPG)

**Comment by skaro** [comment]
Odd - my code is taken from elsewhere in this thread and is pretty similar to yours (with finalDataBytes being a list of byte[]): -

byte[] managedArray = new byte[e.Buffer.Length];
var handler = e.Buffer.Data;
int start = 0;
int length = (int)e.Buffer.Length;
Marshal.Copy(handler, managedArray, start, length);

this.finalDataBytes.Add(managedArray);

You can try just writing down the unmanaged buffer to file using an unsafe method - this is what I did when troubleshooting: -

 try
              {
                  FileStream file = new FileStream("test.wav", FileMode.Append, FileAccess.Write);
                  UnmanagedMemoryStream ustream = new UnmanagedMemoryStream((byte*)e.Buffer.Data, e.Buffer.Length);
                  ustream.CopyTo(file);
                  ustream.Close();
                  file.Close();
              }
              catch
              {
              }

**Comment by ucodes** [comment]
> 
> 
> Odd - my code is taken from elsewhere in this thread and is pretty similar to yours (with finalDataBytes being a list of byte[]): -
> 
> byte[] managedArray = new byte[e.Buffer.Length];
> var handler = e.Buffer.Data;
> int start = 0;
> int length = (int)e.Buffer.Length;
> Marshal.Copy(handler, managedArray, start, length);
> 
> this.finalDataBytes.Add(managedArray);
> 
> You can try just writing down the unmanaged buffer to file using an unsafe method - this is what I did when troubleshooting: -
> 
> try
> {
> FileStream file = new FileStream("test.wav", FileMode.Append, FileAccess.Write);
> UnmanagedMemoryStream ustream = new UnmanagedMemoryStream((byte*)e.Buffer.Data, e.Buffer.Length);
> ustream.CopyTo(file);
> ustream.Close();
> file.Close();
> }
> catch
> {
> }

Hi skaro - getting an empty file as well using the pointer method,
![___Capture](https://user-images.githubusercontent.com/38291347/92501371-205ed480-f207-11ea-8b86-822f00c7308c.JPG)
 odd...

**Comment by gpsushil** [comment]
> @WezMorris and @aarushi-mittal
> 
> For recording the audio on local storage, I tried to save the audio data in a byte array and at the end of the call, I converted those byte array data into audio (mp3, wave) format.
> 
> And to remove the auto stopping the recording by MS Teams, you need to change the logic of OnRecordingStatusFlip as per your wish in compliance recording bot code sample.

How are you converting the byte array to wave at the end ?  I tried converting using NAudio but not getting proper audio
```
public static void ConvertRawToAudio(string prmRawFilePath, string prmOutFilePath)
        {
            var inFileFormat = WaveFormat.CreateALawFormat(16000, 1);
            var rawStream = new RawSourceWaveStream(File.OpenRead(prmRawFilePath), inFileFormat);
            using (var converter = WaveFormatConversionStream.CreatePcmStream(rawStream))
            {
                WaveFileWriter.CreateWaveFile(prmOutFilePath, converter);
            }
        }
```

sample  code to convert would help.

**Comment by gpsushil** [comment]
> > Odd - my code is taken from elsewhere in this thread and is pretty similar to yours (with finalDataBytes being a list of byte[]): -
> > byte[] managedArray = new byte[e.Buffer.Length];
> > var handler = e.Buffer.Data;
> > int start = 0;
> > int length = (int)e.Buffer.Length;
> > Marshal.Copy(handler, managedArray, start, length);
> > this.finalDataBytes.Add(managedArray);
> > You can try just writing down the unmanaged buffer to file using an unsafe method - this is what I did when troubleshooting: -
> > try
> > {
> > FileStream file = new FileStream("test.wav", FileMode.Append, FileAccess.Write);
> > UnmanagedMemoryStream ustream = new UnmanagedMemoryStream((byte*)e.Buffer.Data, e.Buffer.Length);
> > ustream.CopyTo(file);
> > ustream.Close();
> > file.Close();
> > }
> > catch
> > {
> > }
> 
> Hi skaro - getting an empty file as well using the pointer method,
> ![___Capture](https://user-images.githubusercontent.com/38291347/92501371-205ed480-f207-11ea-8b86-822f00c7308c.JPG)
> odd...

I was able to get bytes using
```
            byte[] b = new byte[this.buffLength];
            Marshal.Copy(e.Buffer.Data, b, 0, (int)e.Buffer.Length);
            Utilities.avQueue.Enqueue(b);
```

**Comment by Manojb86** [comment]
This is question is not relevant to this thread. But I asked this question in a separate issue, but no one answered. [https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/257](url)

@ucodes How did you manage to run the compliance bot in the local machine in debug mode? I tried to debug it locally, but it never worked. I tried using ngrok. If you can help me with this, that would be really great. Currently, I haven't tested or debugged a single line of code, every time made a change directly deploy it in cloud service for testing.

If you can answer this in the above-mentioned issue, that also fine.
thanks

**Comment by ucodes** [comment]
@Manojb86 im using remote debugging of the cloud service https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-debug-cloud-services-virtual-machines?view=vs-2019
And you can always rdp to a VM where your worker role is running

**Comment by jong64** [comment]
Speaking of OnRecordingStatusFlip function, it contains the following logging statement. 

                this.GraphLogger.Info($"Flipping recording status to {newStatus}");

Judging from the fact that my call is indeed terminated in about a minute, I assume this function is called. However, I do not find the above logging statement from the page reachable via "/logs" endpoint. It appears that the "/logs" page only contains those statements related to HTTP interactions (incoming/outgoing), and none of the other logging statements produced by the bot.

Does anyone see other logging statements, and if so, where can I find them?
