### ISSUE TITLE
Issue with New-CsTeamsComplianceRecordingPolicy

### ISSUE THREAD

**Issue by muralinareddy** [microsoftgraph/microsoft-graph-comms-samples#159]
**Error:**
New-CsTeamsComplianceRecordingPolicy : The term 'New-CsTeamsComplianceRecordingPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS C:\Users\mnareddy> New-CsTeamsComplianceRecordingPolicy -Tenant <actual id> -Enabled $true -Description "Test policy created by MMR" -Identity "MyPolicy"
New-CsTeamsComplianceRecordingPolicy : The term 'New-CsTeamsComplianceRecordingPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-CsTeamsComplianceRecordingPolicy -Tenant <tenant id> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-CsTeamsComplianceRecordingPolicy:String) [], CommandNotFoundExcepti
   on
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\mnareddy>

**Comment by bijaykush** [comment]
@muralinareddy 

You need to install Skype Online Connector and run the following commands to connect to the connector in windows Powershell:

$credential = Get-Credential
Import-Module SkypeOnlineConnector
$session = New-CsOnlineSession -Credential $credential -Verbose
Import-PSSession $session

**Comment by muralinareddy** [comment]
Thank you for responding.

I did install Skype Online Connector and run those commands.

I am able to create a new application instance, but creating recording policy fails.

**Comment by muralinareddy** [comment]
I didn't have admin rights to create recording policy, so I failed. Closing it. Thank you all for your time.
