### ISSUE TITLE
Outgoing call fails

### ISSUE THREAD

**Issue by bogdan-mabo** [microsoftgraph/microsoft-graph-comms-samples#17]
I modified the code to create an outgoing call to my Teams client. After getting the "Establishing" state notification, there is no more activity for about a minute. After that, I receive the Terminated state notification and a missed call notification in the client.
This is the code I used:

```C#
internal async Task StartTestCallAsync()
{
    var callInfo = new Call {
        Subject = "A subject for this call",
        Targets = new List<ParticipantInfo> { new InvitationParticipantInfo { Identity = new IdentitySet { User = new Identity { Id = "..." }, }, }, },
        TenantId = "..."
    };


    var call = await this.Client.Calls().AddAsync(callInfo, this.CreateLocalMediaSession(Guid.NewGuid())).ConfigureAwait(false);
}
```

The application works fine for incoming calls.

Could you please let me know if this functionality is supported and how can I investigate further the issue?

Thank you, 
Bogdan

**Comment by zhengni-msft** [comment]
Hi Bogdan, 
If the callee is a tenant user, the scenario is supported. If such case doesn't work, please check:
1. do you have the permission to make outbound call ("Initiate outgoing 1:1 calls from the app" in AAD app permission page) for your bot
2. If the bot is consented by the tenant which the caller user belongs to? 
It will also be good to enable log for your bot so you might be able to see specific error in log. 

If the callee is a MS Account user, we don't support such scenario so far.

Thanks, 
Zheng

**Comment by bogdan-mabo** [comment]
Hi Zheng,

Thank you for taking the time to respond.
I verified and the user is a tenant user [I am using the associated Object ID in the field for Identity.Id]:

1. The bot has all permissions enabled.
2. All requested permissions were consented by the admin of the tenant. Please see the screenshot below.

I do not see any errors in the logs of the framework. Could you please let me know if there is anything in particular that would be of interest in this case?

![permissions](https://user-images.githubusercontent.com/32553101/47189126-e7a27300-d2ef-11e8-9a8a-0f82ab938e84.jpg)

**Comment by zhengni-msft** [comment]
Please check if you get any notification after call Calls().AddAsync() in log. And, could you please send us the call ID so we can take a look in server side.

**Comment by bogdan-mabo** [comment]
The call ID is: 321a0500-5c90-45ca-b628-a9ee2a443fd3
And these are the notifications the app received:
```
{
  "@odata.type": "#Microsoft.Graph.Notification",
  "changeType": "Updated",
  "resource": "/app/calls/321a0500-5c90-45ca-b628-a9ee2a443fd3",
  "resourceData": {
    "@odata.type": "#Microsoft.Graph.Call",
    "state": "Establishing"
  }
}
```
and
```
{
  "@odata.type": "#Microsoft.Graph.Notification",
  "changeType": "Deleted",
  "resource": "/app/calls/321a0500-5c90-45ca-b628-a9ee2a443fd3",
  "resourceData": {
    "@odata.type": "#Microsoft.Graph.Call",
    "state": "Terminated"
  }
}
```

**Comment by zhengni-msft** [comment]
Thank you Bogdan for the details! 
We found an error ""Failed to parse user ID out of MRI" for this call in server side, which means that the user ID can't be found. As we can't see the value of user ID (which is obfuscated), could you let us know if you were using user object ID in the user identity or user's sipURI/phone number? Identity = new IdentitySet { User = new Identity { Id = "..." }, } support user object ID only.

**Comment by bogdan-mabo** [comment]
This is the code without obfuscation. I am using the object id:

```C#
        internal async Task StartTestCallAsync()
        {
            var callInfo = new Call
            {
                Subject = "A subject for this call",
                Targets = new List<ParticipantInfo>
                {
                    new InvitationParticipantInfo
                    {
                        Identity = new IdentitySet
                        {
                          User = new Identity
                          {
                            Id = "292cd67d-dcb9-411f-b243-e77f6a77d0f1"
                          },
                        },
                    },
                },
                TenantId = "21bab1fc-4425-450d-97d1-12e11f43d1b7"
            };


            var call = await this.Client.Calls().AddAsync(callInfo,
                //this.Client.CreateMediaSession(
                //new AudioSocketSettings
                //{
                //    StreamDirections = StreamDirection.Sendrecv,
                //    SupportedAudioFormat = AudioFormat.Pcm16K,
                //})

                this.CreateLocalMediaSession(Guid.Empty)
                
                ).ConfigureAwait(false);

            
        }
```

**Comment by zhengni-msft** [comment]
Thank you Bogdan for the details! 
We are involving another team to investigate this issue as it related to SfB inter-op. The beta calling API are major focus on Teams so far. We are working on the inter-op scenario and some of them are not working as expected yet. Will update you when we get more updates.

**Comment by mwerghemmi** [comment]
Hi @zhengni-msft, @bogdan-mabo,

Thanks already for sharing theses infos already helped 👍 
in this same context i have another question:  is it supported to call from a Teams bot a PSTN number ? 
and also is it possible to assign somehow a PSTN DID number to teams calling  bot ? 

Thanks  in advance  ! 
Mefteh.

**Comment by ksikorsk** [comment]
Are there still any outstanding issues here?

**Comment by mwerghemmi** [comment]
Hi @ksikorsk, 
it was said in other threads that You are working on the PSTN capabilities for bot. 
unless you have other info, we can close this one :)

**Comment by bogdan-mabo** [comment]
The outgoing calls are working now. 
NOTE: Did not test the PSTN scenarios.

**Comment by ksikorsk** [comment]
We have a separate tracking item for PSTN calling:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/29

**Comment by sipsorcery** [comment]
@bogdan-mabo how did you get the outbound calls working? I'm stuck on the same thing.
