### ISSUE TITLE
Could not get any response for Huebot

### ISSUE THREAD

**Issue by josehui** [microsoftgraph/microsoft-graph-comms-samples#172]
**Describe the issue**
I have deployed the solution to SF on Azure but couldn't get any response with postman.
.I checked the load balancer and the port 9441 should be forwarded successfully.

![image](https://user-images.githubusercontent.com/35291068/74702965-b10f9c00-5246-11ea-97a4-45419177c97c.png)

I am also not able to access https://huebotxxxxx.xxxx.cloudapp.azure.com:9445/calls through browsers.

**Comment by aarushi-mittal** [comment]
Hello @josehui , 

how did you resolve this ?

Regards,
Aarushi
