### ISSUE TITLE
Compliance recording extra notifications for users with pstn number

### ISSUE THREAD

**Issue by jsweiler** [microsoftgraph/microsoft-graph-comms-samples#176]
I am using the compliance recording sample and notice different behavior when I call a user that has a pstn number assigned to them vs a user that does not. (It doesn't matter whether I call from pstn or from a Teams client). On the users that have a pstn number I get two notifications from graph with different calls ids that are both created. (Only the user that is being called has a compliance recording policy assigned to it.) The only difference I see in the commsNotification object is the source endpoint type is "skypeForBusinessVoipPhone" for the one and "default" for the other one. Then the callId with endpoint type "skypeForBusinessVoipPhone" soon goes into a terminated state and the other one is the actual call that I answer.

Here is the part of the json that I am referring to.
``` json
"source": {
                    "@odata.type": "#microsoft.graph.participantInfo",
                    "id": "826fa9ab-3d94-49e4-a95f-17fdbe07a71e",
                    "identity": {
                        "@odata.type": "#microsoft.graph.identitySet",
                        "user": {
                            "@odata.type": "#microsoft.graph.identity",
                            "id": "guid",
                            "tenantId": "guid",
                            "identityProvider": "AAD"
                        }
                    },
                    "endpointType": "skypeForBusinessVoipPhone",
                    "region": "amer"
                },
```

**Expected behavior**
I would only expect there to be notifications for just one call id not two. The same as if I would call a user that doesn't have a number assigned to them.

**Graph SDK (please complete the following information):**
 - 1.2.0-beta.1

**Call ID**
CorrelationId: 2fd7caa9-1c92-4767-875e-cd59b5c5374e, CallIds: 431f1100-441f-4256-8cee-02531d48895a, 4a1f1100-4d1f-4e2b-8c0f-ccbe77fba8bb

**Comment by ksikorsk** [comment]
@mathowar FYI

This is expected.  When a user is called there is a dial out to all their registered endpoints (mobile client, desktop client, web client, etc...).  If this user has a phone number assigned there is also a dial out to their `VoipPhone` endpoint.  

If this user is under compliance, there is a dial out to the associated bot for each of the users endpoint (if you were logged in on a desktop and a web client, you would see 2 invites to the bot).

If the user does not answer at a given endpoint, all the calls to the bot associated with that endpoint are also terminated.
