### ISSUE TITLE
Unable to successfully make calls from Huebot on Azure

### ISSUE THREAD

**Issue by vganapathy-lifesize** [microsoftgraph/microsoft-graph-comms-samples#18]
I have been trying to get this sample hue bot up and working but without success. Initially I created a service fabric cluster manually from the Azure console and I published the app from VS. It worked to an extent. I was able to get the app running and respond to apis. I was able to fire the join api but the call was stuck in the establishing state. When I looked into the event logs it appeared to me that the app was not receiving any callbacks from the service. The call creation succeeded with 201 but it never received further updates. I wasn't sure what could have gone wrong there.
AppId - 6731d14c-dece-469e-a6d3-bde23ca712c9

Following are the calls I that tried
391a0b00-9b7a-4997-be10-d6480624ab1c
331a0b00-d22c-4d60-8054-2a6b86852820
391a0b00-9b7a-4997-be10-d6480624ab1c

**Comment by vganapathy-lifesize** [comment]
Would anyone be able to help me out with this?

**Comment by kanchm** [comment]
Investigating the first call (`391a0b00-9b7a-4997-be10-d6480624ab1c`), it looks like your SSL certificate is invalid.
  https://vijayteam1.centralus.cloudapp.azure.com:9444/api/calls

An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by vinaychandra** [comment]
@vganapathy-lifesize, your current cert is only valid for `*.lifesizecloudbeta.com, lifesizecloudbeta.com`. Please provide a DNS CNAME from that site to `vijayteam1.centralus.cloudapp.azure.com:9444/api/calls` and use the corresponding new url as callback url. For example, `contoso.lifesizecloudbeta.com:9444/api/calls`.

**Comment by vganapathy-lifesize** [comment]
Hi Vinay,

Thanks a lot for that clarification. I am trying that out right now.

**Comment by vganapathy-lifesize** [comment]
I changed the bot base url to point to a vijayteam1.lifesizecloudbeta.com. I tried joining a call  and still the bot's outgoing leg is stuck at establishing state. Following is call detail. Can you please let me know if something else is wrong now.

    {
        "callId": "331a0b00-d6aa-4cba-b8cf-5913521a171e",
        "correlationId": "527d7908-e673-4752-9596-83e6769a3840",
        "call": "https://vijayteam1.lifesizecloudbeta.com:9443/calls/331a0b00-d6aa-4cba-b8cf-5913521a171e/",
        "screenshots": "https://vijayteam1.lifesizecloudbeta.com:9443/calls/331a0b00-d6aa-4cba-b8cf-5913521a171e/scr",
        "hue": "https://vijayteam1.lifesizecloudbeta.com:9443/calls/331a0b00-d6aa-4cba-b8cf-5913521a171e/hue"
    },

call info returned by the bot
Call Created:
{
  "@odata.type": "#Microsoft.Graph.Call",
  "state": "Establishing",
  "direction": "Outgoing",
  "callbackUri": "https://vijayteam1.lifesizecloudbeta.com:9444/api/calls",
  "callRoutes": [],
  "source": {
    "@odata.type": "#Microsoft.Graph.ParticipantInfo",
    "identity": {
      "@odata.type": "#Microsoft.Graph.IdentitySet",
      "application": {
        "@odata.type": "#Microsoft.Graph.Identity",
        "id": "6731d14c-dece-469e-a6d3-bde23ca712c9",
        "displayName": "HueBot",
        "identityProvider": null,
        "tenantId": null
      },
      "user": null,
      "device": null,
      "phone": null
    },
    "region": null,
    "languageId": null
  },
  "targets": [],
  "requestedModalities": [
    "Audio",
    "Video"
  ],
  "activeModalities": [],
  "mediaConfig": {
    "@odata.type": "#Microsoft.Graph.AppHostedMediaConfig",
    "blob": "{\"mpUri\":\"net.tcp://vijayteam1.lifesizecloudbeta.com:8000/MediaProcessor\",\"audioRenderContexts\":[\"d45f3288-df18-4282-84fd-18ddf4ccd1e9\"],\"videoRenderContexts\":[\"b728dff9-3cc6-48bd-8fd7-ca3ae46b53f7\"],\"audioSourceContexts\":[null],\"videoSourceContexts\":[\"d887435c-9a51-4132-9749-83d194ad6e65\"],\"dataRenderContexts\":null,\"dataSourceContexts\":null,\"supportedAudioFormat\":\"Pcm16K\",\"videoSinkEncodingFormats\":[\"Yuv\"],\"mpMediaSessionId\":\"9ab98ed6-aef8-47ce-8419-392e62f82fd3\",\"regionAffinity\":null,\"skypeMediaBotsVersion\":\"1.9.0.0146\",\"mediaStackVersion\":\"2018.30.1.17\",\"mpVersion\":\"7.2.0.2868\",\"callId\":\"527d7908-e673-4752-9596-83e6769a3840\"}",
    "removeFromDefaultAudioGroup": false
  },
  "chatInfo": {
    "@odata.type": "#Microsoft.Graph.ChatInfo",
    "threadId": "19:meeting_YzI0NTU4ODYtOTY0Yy00YzBkLTg0MmYtMjQyNDlmODRmODk1@thread.skype",
    "messageId": "0",
    "replyChainMessageId": null
  },
  "meetingInfo": {
    "@odata.type": "#Microsoft.Graph.OrganizerMeetingInfo",
    "organizer": {
      "@odata.type": "#Microsoft.Graph.IdentitySet",
      "user": {
        "@odata.type": "#Microsoft.Graph.Identity",
        "id": "0bfcc5e4-b90b-4468-9328-da41dfb540af",
        "displayName": null,
        "TenantId": "c97866f5-de4e-4b0c-99a0-f2fc2d16283e",
        "identityProvider": null
      },
      "application": null,
      "device": null,
      "phone": null
    },
    "allowConversationWithoutHost": null
  },
  "routingPolicies": [],
  "tenantId": "c97866f5-de4e-4b0c-99a0-f2fc2d16283e",
  "myParticipantId": "3ee04231-e178-452d-a985-94e3f595b173",
  "id": "331a0b00-d6aa-4cba-b8cf-5913521a171e",
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#app/calls/$entity",
  "terminationReason": null,
  "ringingTimeoutInSeconds": null,
  "subject": null,
  "error": null,
  "answeredBy": null,
  "meetingCapability": null,
  "toneInfo": null
}

**Comment by kanchm** [comment]
`The remote name could not be resolved: 'vijayteam1.lifesizecloudbeta.com'`

Please check if your service is reachable and DNS entries have been setup.

**Comment by vganapathy-lifesize** [comment]
If I try to do an nslookup by pointing to one of the azure DNS servers I am able to resolve the host
nslookup vijayteam1.lifesizecloudbeta.com ns1-08.azure-dns.com.
Server:		ns1-08.azure-dns.com.
Address:	40.90.4.8#53

Name:	vijayteam1.lifesizecloudbeta.com
Address: 23.99.200.61

Any idea what could be going wrong?

**Comment by vinaychandra** [comment]
@vganapathy-lifesize, Please make sure your your DNS is setup properly and DNS entry is propagated to global DNS. We do not target just the azure DNS but the global DNS to get entries. 
```
nslookup vijayteam1.lifesizecloudbeta.com
Server:  UnKnown
```

**Comment by vinaychandra** [comment]
@vganapathy-lifesize, it looks like your DNS authoritative servers are AWS and not Azure. Please configure your DNS properly. Otherwise the mapping would not work as expected.

**Comment by vganapathy-lifesize** [comment]
Vinay,

Thanks a lot for checking the DNS and I was able to get past that. I am seeing an updated event from teams now with establishing state and then a deleted. Callid for that call is 331a0b00-df31-440e-ad85-2fac70ced12f

**Comment by vinaychandra** [comment]
@vganapathy-lifesize, Please follow [this](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples/HueBot/HueBot#introduction) guide completely. You cannot create a cluster with Azure using VS directly as that would not setup the required NAT Pool forwarding to Media Stack.

**Comment by vinaychandra** [comment]
Please also make sure there are no other services listening on the same port. Note that you cannot create more than one service with media on a single node because a node conflict can happen.
```
Exception occurred in ServiceHost.Open(). Exception details: 
System.ServiceModel.AddressAlreadyInUseException: 
There is already a listener on IP endpoint 0.0.0.0:8000. This could happen if there is another application already listening on this endpoint or if you have multiple service endpoints in your service host with the same IP endpoint but with incompatible binding configurations. 
---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by vganapathy-lifesize** [comment]
@vinaychandra Just wanted to let you know that moment I set the load balancer rule for port 8000 the call connected and I was able to change the hue of the video. Thanks a ton once again for your help. But this is on the cluster I created manually.

I will retry the VS auto deploy once again tomorrow following the steps given. Does that take care of automatically creating the Service Fabric Cluster on Azure? Because the last time I tried it I chose the option on VS to create a new cluster which it did, however, it created its own certificates and did not use the cert I had created. So was wondering if there is any step missing in the documentation related to deploying on Azure.

**Comment by vinaychandra** [comment]
@vganapathy-lifesize, glad to be of help. You need to follow the doc, specifically [this](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples/HueBot/HueBot#azure-deployment) to setup your cluster. It sets up your certificate as expected. Be sure to follow [Prerequisites](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples/HueBot/HueBot#prerequisites) where you upload the certificate.

**Comment by vganapathy-lifesize** [comment]
@vinaychandra I was able to successfully auto deploy the cluster based on steps outlined in the doc. Thank you. I will be closing this ticket
