### ISSUE TITLE
[App-Hosted Media] Vbss (content) Timestamps are Wrong

### ISSUE THREAD

**Issue by pavanjains** [microsoftgraph/microsoft-graph-comms-samples#207]
Hi,

I am using AudioVideoPlayback sample, I registered callback to receive, Audio, Video and VBSS frame and all work great. However I noticed that in my case I am seeing the VBSS timestamps to OFF and sometimes about 10-15 sec ahead with respect to Video/Audio Timestamps. 

Has anyone encountered this? Are these  timestamps coming from different timebase from Teams? 
Or these Timestamps are local to AudioVideoPlayback and are generated at the sample program?

Any help would be appreciated. 

Regards,
Pavan

**Comment by ssulzer** [comment]
@pavanjains 
Can you please share a call-id of an example call in which this occurred? Thanks.

**Comment by pavanjains** [comment]
@ssulzer It turned out to be my setup issue, however can you please help me with this answer please, are these timestamps coming directly from Teams?

**Comment by pavanjains** [comment]
@ssulzer I am seeing timestamps in callback which are back in time from the previous one for ex my frame 5 has timestamp smaller than frame 4. What could be the cause of this? Are these local timestamps based on the arrival time?

**Comment by ssulzer** [comment]
@pavanjains  Timestamps are expressed in a local clock domain. What media type are you observing this with? Also, is this on a VM running in Azure or somewhere else? Thanks.

**Comment by pavanjains** [comment]
@ssulzer I am seeing this on mostly on Video Media and on rare occasion on VBSS. I noticed this when running on my local laptop and also on VM running in AWS

**Comment by pavanjains** [comment]
@ssulzer Any comments on this? When would BOT receive duplicate packets?

**Comment by pavanjains** [comment]
Figured out my issue so closing

**Comment by philomathikus** [comment]
@pavanjains In the spirit of helping to avoid someone ask the same question - could you describe the solution pls?
