### ISSUE TITLE
No audio channel from Landline/Mobile in ReceiveUnmixedMeetingAudio=true

### ISSUE THREAD

**Issue by vnguyenau** [microsoftgraph/microsoft-graph-comms-samples#210]
I have been working on audio recording in Team via this API.

If ReceiveUnmixedMeetingAudio=true, Calling from Team to Team, the audio is perfect with different channels. However, Team to Mobile/landline or Mobile call to Team, there is only 1 audio channel of Team. It is missing audio from Mobile/landline.

If ReceiveUnmixedMeetingAudio=false then Team and mobile/landline audio are in 1 channel and it work fine both side audio in 1 channel. 

It must be a bug when ReceiveUnmixedMeetingAudio=true and no audio from mobile/landline.

This is audio setting I have 
var mediaSession = this.Client.CreateMediaSession(
                new AudioSocketSettings
                {
                    StreamDirections = StreamDirection.Recvonly,
                    SupportedAudioFormat = AudioFormat.Pcm16K,
                    ReceiveUnmixedMeetingAudio=true,
                 },                
               mediaSessionId: mediaSessionId);

**Comment by ssulzer** [comment]
@vnguyenau 
Can you share a call-id please?

Currently, Teams handles meeting participants who join via phone differently than participants who join using a Teams client, and the ReceiveUnmixedMeetingAudio feature will not 'unmix' the audio from the phone participants - but you should at least receive a mix of them. We'll need to take a look.

**Comment by vnguyenau** [comment]
This is the call ID : a11f2c00-641f-4d12-afbf-4db77928688e

**Comment by ssulzer** [comment]
Hi @vnguyenau 
We have enabled special logging within our infrastructure for your bot application. Can you please conduct another test, same steps as before, with the bot requesting Unmixed audio and involving a phone participant. Please confirm that the Teams and phone participants could hear each other but that the bot received audio only from the Teams user, and then share the new call-id. Thank you very much!

**Comment by vnguyenau** [comment]
Call ID : 581f2c00-451f-424f-900a-0bfe725ed153
caller : vouk@callndemo.com.au (participantID : f5d11756-c4c7-4b76-b02f-a8346e4d9187)
to callee +442070354848

**Comment by vnguyenau** [comment]
I can confirm that in Unmixed audio both side could hear each others but the bot only can record from Team side not others(mobile/landline). 
I have done some other tests if you need:
Outgoing call
CallID : 6d1f2c00-401f-4c82-9233-c002a0e5393f
Caller f5d11756-c4c7-4b76-b02f-a8346e4d9187 ( vouk@callndemo.com.au) 
Callee : +442070354848
Incoming call
CallID : 5d1f0d00-761f-462d-8fc1-2763dcca7a0a
Callee f5d11756-c4c7-4b76-b02f-a8346e4d9187 ( vouk@callndemo.com.au) 
Caller : +61406245137
Hopefully it helps.

**Comment by ssulzer** [comment]
Thanks, we will investigate.

**Comment by ssulzer** [comment]
@vnguyenau 
Update: It looks like we are close to a root cause and are planning a fix. Thanks for reporting this!

**Comment by vnguyenau** [comment]
Brilliant :) Do you have any timeline for that fix?

**Comment by ssulzer** [comment]
It will be a fix that we will deploy within our meeting infrastructure (and will not involve a Graph/Media SDK update). I don't have concrete ETA to share, but current best (conservative) guess is that we'll have the fix deployed by end of May. I'll update here once I know more. Thanks.

**Comment by vnguyenau** [comment]
Did we have any update ? Thanks

**Comment by ssulzer** [comment]
Great - thanks! The deployment roll-out is still in progress and may not finish until next week, however.

**Comment by vnguyenau** [comment]
@ssulzer  : Actually the outgoing call have both callee and caller audio but the incoming call does not have caller audio. I think I should wait till next week to test again.

**Comment by vnguyenau** [comment]
I tested and inbound/outbound have 2 way audio. Thanks
