### ISSUE TITLE
Controlling Active/Dominant speaker when using application hosted media

### ISSUE THREAD

**Issue by paulnearney** [microsoftgraph/microsoft-graph-comms-samples#215]
I have created a bot that uses application hosted media to send audio from an external source into a Teams meeting. The external source sends a constant stream of audio packets, which are sent in to the teams meetings. This works really well, apart from the fact that active speaker for that audio source is always triggered, even when the external source is playing silence.

Am I right in saying that, for Active speaker, there is no automatic silence detection on audio being sent in to a Teams meeting using Call.GetLocalMediaSession().AudioSocket.Send(audioBuffer)? So as long as audio packets are streaming into the Teams meeting (even if those audio packets are sending silence or close to silence), Active Speaker will be triggered for that participant?

If so, what is the recommended approach in this situation to have a more natural Active Speaker experience? I've looked at the IsSilence flag on the AudioSendBuffer, but this is only set for received audio. There doesn't seem to be any other settings that control this. The only thing that seems to work is when I artificially pause sending audio to the meeting.

I'm coming to the conclusion that I need to implement my own silence detection on the audio stream, and hold back any audio packets where silence is detected. Is this really my only option? If so, is there anything built in to the API or underlying assemblies that would help me with this?

**Comment by ssulzer** [comment]
@paulnearney 
This is correct - the media platform does not perform silence detection or automatic silence suppression of the audio sent by the bot. And we don't have any API in the platform to help with this, although it certainly would be useful.

**Comment by paulnearney** [comment]
OK, thanks @ssulzer. Good to know. Yes, this would be useful - any chance of it getting added to the backlog would be greatly appreciated!

**Comment by pavanjains** [comment]
@paulnearney Were you able to get around this? Also how did you pause sending Audio?
