### ISSUE TITLE
How to supply real-time media to AudioVideoFramePlayer

### ISSUE THREAD

**Issue by sipsorcery** [microsoftgraph/microsoft-graph-comms-samples#217]
I am doing some prototyping with a console application (will be deployed to Azure at a later stage) that implements a bot that can join a Teams meeting and can send and receive audio. The issue I have is that the audio from my application is coming from a VoIP source and is real-time.

Receiving audio from the Teams meeting works fine the `audioSocket.AudioMediaReceived` delivers the PCM 16K packets every 20ms and I can forward them as required.

Sending audio into Teams is where I have a problem. The `audioVideoFramePlayer.EnqueueBuffersAsync` seems designed to take a large number of samples at once which is fine if the audio source is a pre-recorded file. In my case I'm supplying one 20ms sample at a time and the audio that gets played in the Teams meeting is very choppy. Is this expected? Is supplying a single frame every 20ms to `audioVideoFramePlayer.EnqueueBuffersAsync`  expected to result in a smooth stream?

Here's the method I use to supply the audio samples to send into the Teams meeting. The byte[] buffer is a 640 byte PCM 16k 16bits/sample.

````
public Task EnqueueAudioBuffer(byte[] buffer)
{
	if (this.shutdown != 1)
	{
		if (audioVideoFramePlayer == null || !this.audioSendStatusActive.Task.IsCompleted || !this.startAudioPlayerCompleted.Task.IsCompleted)
		{
			//this.logger.Warn("BotMediaStream sending not yet active.");
		}
		else
		{
			// here we want to create buffers of 20MS with PCM 16Khz
			IntPtr unmanagedBuffer = Marshal.AllocHGlobal(buffer.Length);
			Marshal.Copy(buffer, 0, unmanagedBuffer, buffer.Length);
			var audioBuffer = new AudioSendBuffer(unmanagedBuffer, buffer.Length, AudioFormat.Pcm16K, DateTime.Now.Ticks);

			return this.audioVideoFramePlayer.EnqueueBuffersAsync(new List<AudioMediaBuffer> { audioBuffer }, null);
		}
	}

	return Task.CompletedTask;
}
````

**Comment by ssulzer** [comment]
@sipsorcery 
In this case where the audio source is generated in real-time, the bot can pass the audio frames directly into the AudioSocket.Send API, rather than using the AudioVideoFramePlayer. AudioVideoFramePlayer is intended to make it easy to play out pre-recorded/generated audio/video content.
If there is a lot of jitter or "burstiness" in the audio stream coming from the VoIP source, this will get reflected in the audio stream sent to the Teams meeting. It may help to monitor the timestamps of the audio frames received from the VoIP source to see if delivery from it is reliable (i.e., a frame received every 20ms with little deviation).

**Comment by JPialot76** [comment]
Hello Guys, sorry I know the case is closed but I try to make my bot speak into my ms teams meeting and I didn't succeeded.
Do you have some sample about the use of AudioSocket.Send ?
I have some noïsy sound going with AudioVideoFramePlayer, and it doesn't work at all using direct AudioSocket.Send raising an exception like: The supported buffer sizes for the format Pcm16K are: 10ms 20ms 
And and..I suppose I have to manage kind of temporisation and paquetisation, but "how" ?
Thanks in advance

**Comment by JPialot76** [comment]
I got it :-)
Have to be managed as a Swiss watchmaking
