### ISSUE TITLE
Is The Graph API for Creating Calls Outdated?

### ISSUE THREAD

**Issue by speschka** [microsoftgraph/microsoft-graph-comms-samples#22]
NOTE:  Moving this issue over from the general Microsoft Graph API issues list.

After having every request for creating a new call fail with a 400 - Bad Request error, I finally just copied and pasted the entire payload from microsoft-graph-docs/api-reference/beta/api/application_post_calls.md into my code...and it also fails with a 400 - Bad Request error. Is this really working somewhere? Seems more likely the documentation is outdated, in which case, how can we get it updated?

@ksikorsk responded to this initial issue with this:
Hi, thanks for reaching out. We can certainly help you with your issue. First if you don’t mind I’d like to get some more information.

Are you using any of our SDKs, or are you using the REST API directly?
Are you able to attach the full http response (including headers)?

Once I can track down your request in our logs, I can troubleshoot why you are getting the 400 response.

-------------------------------

Here's the headers that I get back in response when I just do a straight copy and paste from the documentation:

{Transfer-Encoding: chunked
request-id: b5d05f2c-0971-499e-a723-1600eb8d2b5e
client-request-id: b5d05f2c-0971-499e-a723-1600eb8d2b5e
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US","Slice":"SliceC","Ring":"5","ScaleUnit":"003","Host":"AGSFE_IN_12","ADSiteName":"WUS"}}
Duration: 28.2203
Strict-Transport-Security: max-age=31536000
Cache-Control: private
Date: Wed, 07 Nov 2018 01:14:52 GMT
}

Here's the headers I get back in response when I use the JSON I've configured to try and create an outgoing call:

{Transfer-Encoding: chunked
request-id: a0324852-fafd-4805-8cb6-b7f921b0bcf3
client-request-id: a0324852-fafd-4805-8cb6-b7f921b0bcf3
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US","Slice":"SliceC","Ring":"5","ScaleUnit":"003","Host":"AGSFE_IN_27","ADSiteName":"WUS"}}
Duration: 27.2388
Strict-Transport-Security: max-age=31536000
Cache-Control: private
Date: Wed, 07 Nov 2018 01:16:40 GMT
}

I've also attached two JSON files so you can see what my payload looks like if you want to see that.

[sdk.json.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/2555673/sdk.json.txt)
[steve.json.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/2555674/steve.json.txt)

**Comment by speschka** [comment]
Sorry - see I missed one other question - we are using the REST API directly, no SDKs.

**Comment by kanchm** [comment]
From the two payloads, I see these are application-hosted media.  You would need to use our Media libraries and C# SDK.  The use cases are listed in our [calls-api-overview](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/calls-api-overview#media).  `mediaConfig` gets filled in by the SDK that helps identify the URL and ports to use for delivering media to the bot.

For service-hosted media, you have more choices for the SDK and provides IVR functionality but will not let you get direct access to the media.

In this particular time-range, I don't see the request reaching our service.  I suspect the auth bearer token is missing or invalid.  The other issue could be a bad payload but that does not seem to be the case.

**Comment by speschka** [comment]
Thanks, I did also try it as a service-hosted media call, but with the same results (i.e. 400 Bad Request).  The media is really irrelevant to my scenario, just meaning I'm simply trying to create a call and verify that I can get connected to the call recipient.  I tried both a straight copy and paste from the Graph API page as well as a slightly customized version that I've attached to this post - both give a Bad Request error.

The auth token is definitely there.  This code is executing in the callback code after having received an access code from Azure, which is then used to obtain an access token and that token is added as the Bearer header.  If the header were not present or did not represent adequate permissions in fact the error would be 401 Unauthorized, but that is not the case here.

I'd really like to get this working directly against the REST API, so I guess let me ask this - is there a fully functional REST API only example somewhere that I can work off of?  I haven't found one yet but maybe I'm looking in the wrong location.  I can always go back and try and use the SDK if needed, I'm just trying to avoid that because we try not to have those kinds of additional dependencies in our service.
[Steve_ServiceCall.json.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/2560083/Steve_ServiceCall.json.txt)

**Comment by speschka** [comment]
So, not to beat a dead horse here but...is there a *working* sample using the REST API directly to make a call?  The payload appears correct in every way based on the current documentation but both mine and a copy and paste from the SDK returns a 400 - Bad Request response.

Is there any chance it's not a payload thing, i.e. are there any other headers besides the Bearer token that need to be set or something else?  I guess a working REST sample would/should clear all of that up though.

**Comment by speschka** [comment]
To try and get some additional debugging info, I used Fiddler to post to the Calls endpoint, with the same data and authorization info I'm using in my MVC app.  It still really looks like this REST endpoint is just broken, or at least not making much sense.  It says it can't read the JSON payload, and says to ensure valid JSON is sent and a content-type request header is included.  As you can see from the two screenshots I took of the Fiddler client, the payload is valid JSON and the content-type header is included and correct. 

So...can someone either just confirm it isn't working, or point me to a working REST sample?

<img width="927" alt="createcall_payload_and_response" src="https://user-images.githubusercontent.com/6234543/48294392-2637d300-e441-11e8-8a64-d06f2359d90a.PNG">
<img width="809" alt="createcall_httpheaders_and_response" src="https://user-images.githubusercontent.com/6234543/48294393-2a63f080-e441-11e8-9458-07c4132947f5.PNG">

**Comment by kanchm** [comment]
Graph gateway reports this failure when the payload is invalid.  Please check your payload is correctly formatted.  e.g. Steve_ServiceCall.json.txt has a missing comma. jsonlint.com or other online sites are useful to validate this.

```json
{
	"callbackUri": "https://localhost/teamspreview/api/developer/processcall",
	"mediaConfig": {
		"@odata.type": "#microsoft.graph.serviceHostedMediaConfig"  <--MissingComma
		"preFetchMedia": []
	},
```

The JSON payloads in our [Graph documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/call) is to be used as a guide.  They are not directly usable because we scrub personally identifiable data as well as remove the auth headers.  We strive to keep them in sync with our schema but there are times where the documentation may not be in sync with the implementation because of different release schedules.  In this specific case though, the payloads are getting rejected by Graph gateway and not making its way to our service because of the invalid structure.

Once the payloads reach our service, please send the payload (scrubbed) and the timestamp of the request.  We can look at any issues with the service not accepting the payload.

**Comment by speschka** [comment]
Sorry for the slow response, but thank you, I appreciate you getting back to me on this.  You are correct, I fixed that up and have now moved on to a 403 Forbidden error.  No sarcasm intended here, this is making progress.  :-)   I'll do some digging on that next.  Thanks again, I do really appreciate the feedback here!
