### ISSUE TITLE
How to set up the DNS CNAME 

### ISSUE THREAD

**Issue by verdua** [microsoftgraph/microsoft-graph-comms-samples#220]
Hi guys, I'm trying to run a Bot locally using Ngrok for tunneling but, I get confused when I have to create the **DNS CNAME** entry in the local Ngrok configuration step number V.

![image](https://user-images.githubusercontent.com/37675560/80593237-38bc1880-89f7-11ea-8e73-20185fdada12.png)

My question is. Where does this **DNS CNAME** have to be created? does this **DNS CNAME** have to be created in my local machine? in case the answer is yes, is it possible to create a **DNS CNAME** in Windows 10?

**Comment by verdua** [comment]
Finally I created a **DNS zone** in Azure and configure my **DNS CNAME** entry for _my_domain.contoso.com_ pointing to my ngrok tunnel _id.ngrok.io_ and the Bot could join to a meeting and received the streams from the participants.

**Comment by aarushi-mittal** [comment]
Hello @verdua ,

What was your parameters for -dns and -cn field while configuring the files in this case?
 I am stuck on the same issue

Regards,
Aarushi
