### ISSUE TITLE
Invite a bot to a Live Event

### ISSUE THREAD

**Issue by pagella42** [microsoftgraph/microsoft-graph-comms-samples#221]
Hey,

I was wondering if its possible to have a bot join a Live Event, since the documentation does not talk about it.

I have already tried the [ PlayBack Bot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot) , and i wanted to know if its possible to do something like that, but in a Live Event, since the sample its done on a regular call.

Considering this, i would also like to know if its possible to assign it a presenter role, and if so how do you assign it.

The  bot im trying to build is a **hosted media application** , which could access to the video and audio data streams from the call.

**Comment by pagella42** [comment]
**[Update]**  Been working further into this issue, and we came through a situation:

We hosted a private Live event within an organization. Here we were able to have a bot join the event, but there's  few things to consider. 
             *Why was the _external_ bot able to join an event from an organization?
             *Our bot is hosted in a tenant (lets call it X), and our live event in a tenant (Y).

So from this,arises the question, is this a supported scenario? Can we actually invite a bot to a live event? If not, could that be a security flaw?

**Comment by pagella42** [comment]
**[update]** What was causing the behavior i mentioned in my last comment was that we, before, had given consent to the tenant y, and so it was able to join.

**Comment by pagella42** [comment]
Hey, 
I'm still trying to invite the bot to a Live event. 

The problem is the bot will always join as a presenter, even if it joins after the event started.
The thing is, i am trying to capture the media from the live event, and as a presenter, i only have access to the internal stream, being the presenters video. But what i'm trying to capture, is the feed that attendees get, the one that the producer chooses.

Is there actually a way to do that? If so, How?
If not, is it a feature on the road map? Is there an ETA?

**Comment by ssulzer** [comment]
@pagella42 @jrebagliatti

For a Live Events inner meeting hosted on Teams, your bot should be able to access the video feed the producer has selected, see https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/229#issuecomment-626081482.

For a Live Events using an External Encoder, there is currently no support in the Graph API. Are you looking to access the live ingest RTMP feed, or the finished recording URL in Stream? (Or both?) Thanks.
cc: @zhengni-msft @ananmishr

**Comment by pagella42** [comment]
@ssulzer We could finally do this following your recommendations, and we are getting the producer feed.

Now we are having a problem, when trying to differentiate whether our bot is joining a regular call or if it is a Live Event. Is there an actual way to do this by this time? Could you please guide us on how?

Any help will be appreciated,
Thanks

**Comment by jrebagliatti** [comment]
Hi @ssulzer 

Regarding:
> For a Live Events using an External Encoder, there is currently no support in the Graph API. Are you looking to access the live ingest RTMP feed, or the finished recording URL in Stream? (Or both?) Thanks.

None of them actually, I'm just wondering if we can subscribe to the camera/encoder/device video feed as we do with other participants in a "regular" Teams meeting. But as was mentioned in the issue https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/233 this is not possible as live events produced with an external devices are not handled by the bot's media platform.

Regarding:
> Also, can you share for what purpose your bot needs the live events video feed, what is the scenario? Thanks.

I'm just exploring calling bot capabilities, trying to understand what can be done with it and which are the limitations.

Thank you very much for all your help.

**Comment by ssulzer** [comment]
@pagella42 

> Now we are having a problem, when trying to differentiate whether our bot is joining a regular call or if it is a Live Event. Is there an actual way to do this by this time?

Currently the Graph API [onlineMeeting resource type](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0) does not provide an indication whether it's a Live Event meeting or not. cc: @zhengni-msft if this is in our backlog to update.

However, what was the identity of the bot whose video source provided you the producer's feed? In other Live Event inner meetings, you should find the same bot identity present. As a short-term solution, you might simply use the presence of this "Live Events Broadcast/Composer" bot as an indication of a (Teams meeting-hosted) Live Event; this particular bot is not used in other meeting contexts. Thanks.

**Comment by pavanjains** [comment]
@ssulzer @pagella42 @jrebagliatti Is it possible to make bot join as attendee? I tried using the attendee link but it still joins as participant
