### ISSUE TITLE
Unique ID of a call

### ISSUE THREAD

**Issue by hohno-panopto** [microsoftgraph/microsoft-graph-comms-samples#223]
My app needs to handle mutliple calls from mutliple tenants.
Can I assume that ICall.Id is unique across all calls and use it as the primary identifier to distinguish a call from other calls? Or, should I use something else?

If it is the right identifier, can I assume that ICall.Id is always GUID even though it's defined as string? It would be helpful to determine the type of database column to store it.

**Comment by ssulzer** [comment]
@zhengni-msft

**Comment by ssulzer** [comment]
@hohno-panopto 
ICall.Id should be unique for 1:1 calls, but all call legs in a group call or meeting will have the same Id.
@satyakonmsft is that correct? Thanks.

**Comment by zhengni-msft** [comment]
@hohno-panopto , Yes, ICall.ID is unique even for group call. The same bot join a group call multiple times will get different call ID. It is actual a 'call leg' ID and global unique. 
It will be good that we don't have the assumption that it is always a GUID though right now it looks like so.

**Comment by hohno-panopto** [comment]
Thank you, @ssulzer @zhengni-msft !!
