### ISSUE TITLE
Bots on National clouds

### ISSUE THREAD

**Issue by pagella42** [microsoftgraph/microsoft-graph-comms-samples#226]
Hey,

I was doing some research on National clouds for a bot i want to build, and i yet haven't found if it is possible to deploy a calling bot on Azure Gov or on national clouds.
Is there a way to do this? and if so, how?

I also would like to know if the Graph communications API is available for use to Azure Gov.

**Comment by ssulzer** [comment]
@zhengni-msft @ananmishr

**Comment by ssulzer** [comment]
@ananmishr
