### ISSUE TITLE
Publishing to cloudapp.net not working

### ISSUE THREAD

**Issue by ncannings** [microsoftgraph/microsoft-graph-comms-samples#228]
The instructions are clear not to use a self-signed cert

I have a custom domain (CNAME associated with my cloudapp.net domain) and a CA signed cert uploaded to the app.  If I put the domain and the cert thumbnail  into the configure_cloud.ps1 script as suggested, I get the following error when I publish:

` Recovering role... Application startup task "E:\approot\Startup.cmd" > Startup.cmd.log finished successfully. [2020-05-05T16:25:39Z] Last exit time: [2020/05/05, 16:24:54.596]. Last exit code: 0. Last role exception: System.Net.Sockets.SocketException, Details: Exception: No such host is known at System.Net.Dns.GetAddrInfo(String name) at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) at System.Net.Dns.GetHostEntry(String hostNameOrAddress) at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in C:\Users\nigel\Source\Repos\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 380 at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in C:\Users\nigel\Source\Repos\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 231 at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\Users\nigel\Source\Repos\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 92 at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum) at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart() '.`

Any suggestions as to how to get these samples working using Cloud Services (classic)?

Thanks

**Comment by ssulzer** [comment]
Sounds like the same issue as #218

**Comment by ncannings** [comment]
Thanks, solved it.  In the end, once I'd solved the DNS issue, it was a misconfigured certificate.  Always read the error message!
