### ISSUE TITLE
Teams :Cannot read file .wav

### ISSUE THREAD

**Issue by mwerghemmi** [microsoftgraph/microsoft-graph-comms-samples#23]
**Describe the issue**
Hello,
Trying to play a prompt after answering a call (call established).
The API Call is not retrurning any answer no error...

I am using the Graph Javascript SDK for the API calls.

**Expected behavior**
      receive a http code 
      and  audio file is expected to be played on the call ( prompt). 

**Graph SDK  Javascript SDK:**
 - Version beta

**Call ID**
2d1a0300-d7da-4e0a-8899-9799773ab01e

  "status": "Completed",
  "createdDateTime": "2018-11-07T17:14:53.3464657+00:00",
  "lastActionDateTime": "2018-11-07T17:14:54.6236122+00:00",

By the way the /subscribeToTone is working but same i am not receiving any rest code... 

Mefteh.

**Comment by mwerghemmi** [comment]
Hi @kanchm  

Do you have all required infos above please ? 

Thx! 
Mefteh.

**Comment by kanchm** [comment]
Inspecting the server logs. Just to confirm that your bot received the subscribeToTone events like these:

```http
POST https://77a14a33.ngrok.io/api/call
Authorization: (redacted)
X-Microsoft-Skype-Chain-ID: f9bc7683-69b6-49b9-8dd2-61bdc3c92296
Accept: application/json
User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
X-Microsoft-Skype-Message-ID: 718c9699-b1a8-4137-b31b-fedfc1088267
Content-Type: application/json; charset=Windows-1252
```
```json
{
  "@odata.type": "#Microsoft.Graph.Notifications",
  "value": [
    {
      "@odata.type": "#Microsoft.Graph.Notification",
      "changeType": "Updated",
      "resource": "/app/calls/2d1a0300-d7da-4e0a-8899-9799773ab01e",
      "resourceData": {
        "@odata.type": "#Microsoft.Graph.Call",
        "state": "Established",
        "toneInfo": {
          "@odata.type": "#Microsoft.Graph.ToneInfo",
          "sequenceId": 1,
          "tone": "Tone1"
        }
      }
    }
  ]
}```

**Comment by mwerghemmi** [comment]
Hi @kanchm

Here is an example of what i receive when i press 1 from Teams client: 

"x-microsoft-skype-chain-id": "2dc72e54-01d0-4336-972c-e49ebcc1ea7c",
 "accept": "application/json",
 "user-agent": "Microsoft-Skype/3.0 (Calling/1.0)",
 "x-microsoft-skype-message-id": "e2420b66-5fca-4571-9cee-9db0e46292f1",
 "content-type": "application/json; charset=Windows-1252",
 "host": "659dbfb5.ngrok.io",
 "content-length": "352",
 "x-forwarded-proto": "https",
 "x-forwarded-for": "104.40.192.188"
}

{
app.js:18
 "@odata.type": "#Microsoft.Graph.Notifications",
 "value": [
  {
   "@odata.type": "#Microsoft.Graph.Notification",
   "changeType": "Updated",
   "resource": "/app/calls/351a0300-62c5-4531-ada1-c71f3900987c",
   "resourceData": {
    "@odata.type": "#Microsoft.Graph.Call",
    "state": "Established",
    "toneInfo": {
     "@odata.type": "#Microsoft.Graph.ToneInfo",
     "sequenceId": 1,
     "tone": "Tone1"
    }
   }
  }
 ]
}

as mentioned in the first message, when i send the /subscribetotones, i am not receiving any response but then i can send tones.. 
for prompt no response code and the music is not being played .. 

Mefteh.

**Comment by mwerghemmi** [comment]
Hi @kanchm,  

Just in case you need anyd further test,  let me know :) 
hope you have already  some results 👍 
Mefteh.

**Comment by kanchm** [comment]
Please check out issue #25 if that helps you get the HTTP status codes.

**Comment by mwerghemmi** [comment]
Hello, 
Indeed that helps regarding thé status of the opération but still the prompt itself is not working (thé audio file is not being played)

**Comment by kanchm** [comment]
@ssulzer could you please take a look?  Skype-chain-id: 7b5e9263-0566-4e53-94c5-514e6cd3c2fe

**Comment by ssulzer** [comment]
@mwerghemmi @kanchm 
The .wav file is in stereo format but we support only mono/1-channel .wav files.

**Comment by mwerghemmi** [comment]
Many thanks @ssulzer @kanchm 👍

**Comment by kanchm** [comment]
Created a bug on our end to emit a better error message.

**Comment by mwerghemmi** [comment]
Hi @ssulzer, 
The loop is also not working, is it a known limitation ? 
Are there any other requirement maybe ? 

Thanks in advance ! 
Mefteh.

**Comment by ssulzer** [comment]
Hi Mefteh,

Please open a new Issue on the github site for this, along with a Call-ID.

Thanks,
Stephen

**Comment by ksikorsk** [comment]
Are there still any outstanding issues here?

**Comment by mwerghemmi** [comment]
Hi @ksikorsk, 
no this is solved now :) 
sorry i missed to close the issue. 

Thx . !
