### ISSUE TITLE
Application Hosted Media and Government Cloud - any limitations?

### ISSUE THREAD

**Issue by paulnearney** [microsoftgraph/microsoft-graph-comms-samples#235]
More of a question than an issue. I can see a `HostingEnvironmentConfiguration` enum in the `MediaPlatformSettings`, which has values referring to Government Cloud. Are there any differences/restrictions/limitations when using an Application Hosted Media app against Government Cloud?

**Comment by jrebagliatti** [comment]
Similar question here: https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/226

**Comment by paulnearney** [comment]
Hi, any update on this at all? Thanks

**Comment by ssulzer** [comment]
@zhengni-msft 
I don't think there is a way to register a bot for the government cloud regions.

**Comment by paulnearney** [comment]
Thanks @ssulzer. Is that a definite 'no', or needs confirmation from @zhengni-msft @ananmishr?

**Comment by ssulzer** [comment]
@paulnearney It's a definite 'no' for now. We don't have a timeframe to share when it will be possible to register a bot app for the government cloud regions.

**Comment by paulnearney** [comment]
Great, thanks @ssulzer - good to have confirmation
