### ISSUE TITLE
H264 Loop back fails

### ISSUE THREAD

**Issue by vganapathy-lifesize** [microsoftgraph/microsoft-graph-comms-samples#24]
I tweaked the Huebot sample code to receive H264 frames instead of the NV12 frames from the video socket and I tried to send back the frame over the video socket. However, I haven't been able to successfully get the media to loopback to the teams meeting.

I changed the following in the Huebot
1. Changed the CreateLocalMediaSession (in Bot.cs) to set the ReceiveColorFormat to VideoColorFormat.H264 instead of VideoColorFormat.NV12. And also changed the SupportedSendVideoFormats to include the supported H264 formats instead of the VN12 formats.
2. Change the GetSendVideoFormat (in Utilities.cs) to return the appropriate H264 format for a given width.
3. Changed OnVideoMediaReceived to copy the incoming H264 buffer ti another buffer and send it to the remote. The Bot does not change the hue or take snapshots. 
Following is the changed code I made to create a copy of the H264 buffer
                    // Use the real length of the data (Media may send us a larger buffer)
                    VideoFormat sendVideoFormat = e.Buffer.VideoFormat.GetSendVideoFormat();
                    int size = (int)e.Buffer.Length;
                    IntPtr ptr = Marshal.AllocHGlobal(size);
                    CopyMemory(ptr, e.Buffer.Data, size);
                    var videoSendBuffer = new VideoSendBuffer(ptr, size, sendVideoFormat);
                    this.Call.GetLocalMediaSession().VideoSocket.Send(videoSendBuffer);

The looped back video is not seen in the teams meeting.
The send on the first few frames does not throw any exception however, subsequent ones continuously throws the following exception

{
  "Timestamp": "2018-11-08T10:01:09.4860889-06:00",
  "ProviderName": "Sample.HueBot",
  "Id": 1,
  "Message": "Sample.HueBot(CallHandler.cs:317 OnVideoMediaReceived) 2018-11-08T16:01:13.6035038Z: [301a0400-326b-4d67-bc79-3aa784ce0f21] Exception in VideoMediaReceived
    exception: Exception of type 'Microsoft.Skype.Bots.Media.SkypeMediaException' was thrown.
    Deliver video source media buffer
    StackTrace:    at Microsoft.Rtc.Internal.Media.MediaApi.VideoSourceConsumer.DeliverBuffer(MediaBuffer A_0)
       at Microsoft.Skype.Bots.Media.SourceConsumerWrapper.DeliverBuffer(MediaBuffer buffer, BufferDisposeDelegate bufferDisposeDelegate)
    , Properties: null",
  "ProcessId": 8776,
  "Level": "Informational",
  "Keywords": "0x0000F00000000000",
  "EventName": "Message",
  "ActivityID": "0000518f-0001-0000-4822-0000ffdcd7b5",
  "RelatedActivityID": null,
  "Payload": {
    "message": "Sample.HueBot(CallHandler.cs:317 OnVideoMediaReceived) 2018-11-08T16:01:13.6035038Z: [301a0400-326b-4d67-bc79-3aa784ce0f21] Exception in VideoMediaReceived
      exception: Exception of type 'Microsoft.Skype.Bots.Media.SkypeMediaException' was thrown.
      Deliver video source media buffer
      StackTrace:    at Microsoft.Rtc.Internal.Media.MediaApi.VideoSourceConsumer.DeliverBuffer(MediaBuffer A_0)
         at Microsoft.Skype.Bots.Media.SourceConsumerWrapper.DeliverBuffer(MediaBuffer buffer, BufferDisposeDelegate bufferDisposeDelegate)
      , Properties: null"
  }
}

If someone could throw light on what could be going wrong here would be great.

**Comment by kanchm** [comment]
Could you start looking through our other sample that demonstrates H.264 streaming?  It is not an echo bot scenario like what you are attempting (great idea btw) but plays back pre-recorded streams.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/LocalMediaSamples/AudioVideoPlaybackBot/FrontEnd/Bot/BotMediaStream.cs

**Comment by ssulzer** [comment]
@vganapathy-lifesize 

Hello,

It is not appropriate to loop back video using the H.264 encoded video format, especially if the bot is joined to a meeting or group call. Use of the H.264 format is to support advanced scenarios where the  bot is receiving its video source from its own H. 264 video encoder, and can respond promptly to incoming VideoKeyFrameNeeded events (to supply an IDR frame) and changes in the PreferredEncodedVideoSourceFormats property (given by the VideoSendStatusChanged event) to adapt to requested resolution/framerate/bitrate. The bot must ensure that it does not send video at a bitrate exceeding the requested VideoFormat.BitRate value.

If joined to a meeting, the bot should also be able to supply H.264 encoded video in multiple formats concurrently (per its VideoSocketSettings.MaxConcurrentSendStreams setting); for example, the bot may be requested to supply its video source at both 720p/30fps and 240p/15fps simultaneously.

With loopback, the bot does not have sufficient control over what video resolution size, framerate, and bitrate it is receiving to ensure it can satisfy what formats it is required to send.

Thanks,
Stephen

**Comment by vganapathy-lifesize** [comment]
@ssulzer Thanks for your clarification. Fair enough, I can perfectly understand what you are saying. That's eventually what we are trying to get to. Right now I am at a very initial stage trying to see how I can get a H264 frame out of the Bot and  also to send a H264 frame to it. Loop back as you say may not be a good idea, as it cannot service the key frame, resolution or bitrate requests originating from the far end. I need to generate a video stream of my own to deal with all the dependencies you have mentioned above.

I am trying to understand right now is how to get a frame out and how to feed it a frame. I have basic question on receiving a frame which you can help me answer. The VideoMediaReceivedEventArgs object that I receive in the VideoMediaReceived callback has  Buffer member which internally has a Data (IntPtr). Is that an unencrypted and depacketized H264 Frame? Or is it a reference to an instance of some other class like H264Frame?

**Comment by ssulzer** [comment]
@vganapathy-lifesize 

The frame data is an unencrypted, depacketized H.264 elementary stream. VideoMediaBuffer.Data points to the start code of the first NALU of the frame and the whole buffer contains all the NALUs of the frame in sequence separated by their start codes.

**Comment by ksikorsk** [comment]
@ssulzer is there a github repo I can transfer this issue to?

**Comment by ssulzer** [comment]
@ksikorsk 
No. This issue can be closed: we advise **not** to do video loop back using the encoded H.264 video format. Loop back will work reliably only when using the "raw" NV12 video format. Thanks.

**Comment by Mishra-Saurabh** [comment]
I am trying to get one .mp4 file from byte array  with .h264 color format but I am not able to do that. i am using this code to write the video file:  Stream t = new FileStream("C:\\ganesha.MP4", FileMode.Create);
            BinaryWriter b = new BinaryWriter(t);
            b.Write(arrbyte);
            t.Close();
            
            
            After i see your post where it is mentioned that we should use Nv12 in place of h264 so i used that but i am getting error:    (Array dimensions exceeded supported range). How we can fix this issue. We are stuck here.
