### ISSUE TITLE
MS Teams API don't send statusCode when answering to a call

### ISSUE THREAD

**Issue by Githamza** [microsoftgraph/microsoft-graph-comms-samples#25]
I have a bot which should answer to calls, here's [the documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/call_answer)

Actually I can Answer a call (MS Team unhook  the call ) but I get no response status code or error. In documentation it mentioned that **I should get a 202 accepted status code** [Microsoft Graph SDK](https://www.npmjs.com/package/@microsoft/microsoft-graph-client)  ( `api` method right after initialisation):
```
client
    .api('/users/me/sendMail')
    .post({message: mail}, (err, res) => {
        console.log(res)
    })
```

I think that the post request is working because my bot is answering to call, but `res` is `undefined`

I have tried to check `res.statusCode` but I get no content.
How can I get response from MS Teams API ?

**Comment by kanchm** [comment]
Please check this link on [rawResponse](https://www.npmjs.com/package/@microsoft/microsoft-graph-client#full-service-response) to be able to get to the status code.  [Answer](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/call_answer#response) does not reply with a body.

**Comment by Githamza** [comment]
Thanks that's working
