### ISSUE TITLE
How to join other tenants' meetings?

### ISSUE THREAD

**Issue by rubenrumu** [microsoftgraph/microsoft-graph-comms-samples#254]
**Describe the issue**
I am able to run AudioVideoPlaybackBot and make it join my tenant's meetings, but when I try to join other organizations' meetings I get a HTTP 403 response.

Is it possible to join another tenant's meeting with a bot configured in my tenant?

**Comment by JonatanMedinilla** [comment]
Hi @rubenrumu, as far as I know, it's possible to join another tenant's meeting with a bot configured in  another tenant. To do this, you have to ask the administrator of the other tenant for permissions' consent. 
According to the samples' documentation, you should use the following url "https://login.microsoftonline.com/common/adminconsent?client_id=<app_id>&state=<any_number>&redirect_uri=<any_callback_url>" to ask for consent.
I've tested this scenario by registering the bot channel registration in a tenant A, passing the mentioned url to a co-worker that is admin of the tenant B, and creating a meeting in a tenant B where I have access.

**Comment by rubenrumu** [comment]
Thank you very much! We had some confusion with the fields "state" and "redirect_uri" but we finally figured it out :)
