### ISSUE TITLE
Try to redirect call to resource account

### ISSUE THREAD

**Issue by Janath** [microsoftgraph/microsoft-graph-comms-samples#260]
**Describe the issue**
Teams user calls bot then bot tries to redirect or transfer to application. 

**Code Snippet**
            InvitationParticipantInfo target = new InvitationParticipantInfo
            {
                Identity = new IdentitySet
                {
                    User = new Identity
                    {
                        Id = ConfigurationManager.AppSetting["AutoAttendantId"],
                        DisplayName = "Auto Attendant"
                    },
                },
            };

await this.GraphApiClient.SendAsync(this.RequestBuilder.Communications.Calls[callId].Transfer(target).Request(), RequestType.Create, tenantId, scenarioId).ConfigureAwait(false);

**Expected behavior**
Expecting the bot able to transfer call to application.

**Comment by Janath** [comment]
Solution is use application instead of user

Application = new Identity

Therefore, this can be closed.

**Comment by jsweiler** [comment]
@Janath When I try that using Application = new Identity I get a request authorization tenant mismatch error. Just curious did you ever get that?

**Comment by bijaykush** [comment]
@Janath and @jsweiler 

I am also having the same issue as @jsweiler is facing. Getting tenant mismatch error. Any way to get rid of this?

**Comment by Janath** [comment]
@jsweiler @bijaykush 

I added to comment based on documentation but never tested the solution. However, I tried this recently with many combination and got the same error. Did you guys find any work around?

**Comment by bijaykush** [comment]
@Janath 
Workaround for now is, we can use PSTN number for transferring a call from one resource account to another resource account. I have tested this by transferring call from a resource account of one bot to another resource account of another bot. 
For refernce: https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=http#example-3-call-transfer-to-pstn-number
