### ISSUE TITLE
[PolicyRecordingBot] - TryCheckTcpConnectivity exception: System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by JSGund** [microsoftgraph/microsoft-graph-comms-samples#263]
PolicyRecordingBot run locally, but catch by below exception.

TraceSource Error: 0 : [SkypeBotsMediaPlatform][AppId:55de836f-248c-4d26-822c-405080517ecc] TryCheckTcpConnectivity exception: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it xx.xx.xx.xx:13016
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
   at Microsoft.Skype.Bots.Media.PlatformEnvironment.TryCheckTcpConnectivity(String fqdn, Int32 port)

Can anyone help to resolve this issue?

Thanks,
Jeetendra

**Comment by unicornlab-aranyakg** [comment]
Hi @JSGund 

I'm facing the same issue when running the AKS Teams Recording bot solution. Please advise on how this was resolved.
