### ISSUE TITLE
Media Platform Azure Region

### ISSUE THREAD

**Issue by JonatanMedinilla** [microsoftgraph/microsoft-graph-comms-samples#266]
Hi, I would like to know if there is way to know in which Azure Regions the audio/video sockets connections are being established. I am implementing together with my team a different approach to deploy an Application-Hosted Media Bot dynamically, and we want to deploy it in an Azure Region closest to the region where the live content (for a live event)/participants feeds (normal meeting) is/are being delivered. Is it possible to do that?

**Comment by ssulzer** [comment]
@JonatanMedinilla 
I don't think there's a way for a bot to discover in which Azure region a particular meeting instance is hosted.
Meetings are hosted in one of several different regions. The main ones are:
North America: East US 2 , East US, Southcentral US, West US
Europe: North Europe, West Europe, France Central, UK South
Asia/Pacific: East Asia, Southeast Asia, Japan West, Australia East
But this list is subject to change; e.g., as new regions are added (such as Brazil South).

**Comment by JonatanMedinilla** [comment]
@ssulzer thanks for the answer. Do you know if the call region is being determined by the same region of Microsoft Office 365 Tenant or is it dynamic?

**Comment by ssulzer** [comment]
It's dynamic. Typically where the first meeting participant joins from influences where the conference media server is allocated. E.g., if the first participant to join is based in Europe, then the conference media server will be hosted in one of the EU regions. You can deploy your bot in all 4 of those main EU Azure regions to help ensure your bot is at least within the same geo but there's no guarantee it will be co-located within the same Azure region as the meeting server.
