### ISSUE TITLE
Sample Compliance policy recording Bot Issues DNS

### ISSUE THREAD

**Issue by doucheface1** [microsoftgraph/microsoft-graph-comms-samples#268]
I have followed the instructions exactly and assigned the compliance policy to a user 

the crworker role is running and shows all green but I get nothing appearing when I start a call.... and the call just tries to go to voicemail.

I think the issue is DNS related as Microsoft don't say anywhere in their instructions what DNS needs to be set. do I need to setup CName or A record in external DNS?

I'm using their cloudapp.net domain and not my own i don't understand what the 

webhook for calling is, i have it set to https://soteriacompliancecloud.cloudapp.net/api/calling 

the crworker role is called soteriacompliancecloud.cloudapp.net 

i have set both Cname and DNS within the sample code to soteriacompliancecloud.cloudapp.net

what am i doing wrong....

I have the below setup but nothing seems to work

**Comment by doucheface1** [comment]
can anyone assist with this we are really stuck with this and need assistance

**Comment by doucheface1** [comment]
can anyone assist is there anywhere else i can gain assistance if no one want to assist on here

**Comment by paulnearney** [comment]
> can anyone assist is there anywhere else i can gain assistance if no one want to assist on here

Apologies in advance if this breaks any rules, but my company offers consultancy services on the communications API if you are looking for any outside assistance. I wouldn't normally post on github like this, but it's clear that there's a sense of urgency and I can't see any other way to get hold of you to offer assistance. https://chimusoftware.com

Mods, please feel free to delete if this blatant advert is against the rules!

**Comment by doucheface1** [comment]
thanks for reply but i feel we are 1 setting away from getting sample to work. we have inhouse developers that are writing code to do recording piece. i need somene to show us in this forum what im missing from Microsofts instructions in code section. can you do that?

**Comment by paulnearney** [comment]
It's heard to give you a definitive answer, as there are a few moving parts, but the instructions for the [HueBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot) sample are more detailed about certificate and DNS requirements, and should fill some of the gaps that are missing in the policy bot instructions

**Comment by doucheface1** [comment]
ok so do i follow these as this is for a different BOT? i have done everything in the origional instructions that seem complete from a certificate side but not DNS. are there any logs in teams i can see as these would help. i have clients set with policy so surley if there are logs in teams they would give me an answer as to whats wrong. I.E wrong DNS or cert problems

**Comment by doucheface1** [comment]
also ive looked at the HueBot instructions and ive done all that except for the ngrok account section as thats not relevant to sample code here

**Comment by doucheface1** [comment]
[
![image](https://user-images.githubusercontent.com/45433448/85300362-5a3cfc00-b49e-11ea-929e-2588605772a3.png)
](url)

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85300444-7476da00-b49e-11ea-9bc6-e62c7660f3bf.png)

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85300622-b43dc180-b49e-11ea-9fd0-d798d08a70d6.png)

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85300859-0252c500-b49f-11ea-9d73-eef4fb8eddbc.png)

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85300984-2d3d1900-b49f-11ea-964f-091eec2d1472.png)

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85301063-45149d00-b49f-11ea-91d1-3627f85254b9.png)

**Comment by doucheface1** [comment]
all screen shots uploaded can you see anything wrong?

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85302248-d2a4bc80-b4a0-11ea-931c-23c1e114800d.png)

**Comment by doucheface1** [comment]
this is policy i created and assigned to me

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85303641-aa1dc200-b4a2-11ea-9423-92715f916dbf.png)

**Comment by doucheface1** [comment]
this is visual studio config please note origionally Cname was set to default soteriacompliancecloud.cloudapp.net and it didnt work same results as now. i changed it to soteriacompliancecloud.itechdemo.co.uk this is our domain. it still doesnt work same results.... 

i have a cname in our dns pointing soteriacompliancecloud.itechdemo.co.uk to soteriacompliancecloud.cloudapp.net

**Comment by doucheface1** [comment]
can you still assist?

**Comment by doucheface1** [comment]
![image](https://user-images.githubusercontent.com/45433448/85395971-dee45480-b548-11ea-929c-c3787dcab46f.png)

this is what i have set at teams level

**Comment by WezMorris** [comment]
Did you ever get this working?

**Comment by doucheface1** [comment]
no its a joke the instructions if you follow them just simply dont work. i currently have an open ticket with microsoft and they cant even get it working...

**Comment by WezMorris** [comment]
okay so I've managed to get a bot to join my calls now. A couple of things that helped;

I changed the bot channel registration webhook to something from https://webhook.site and it wasn't getting any hits, which told me the problem wasn't with my service or dns but likely either the application permissions or the powershell policy. 

So I added in the CallRecords.Read.All permission (it seemed relevant) and checked my policy again. Turns out the policy I'd made had an Enabled flag set to false. Once that was changed the bot started to join calls

**Comment by doucheface1** [comment]
my policy is already enabled And I have the correct permissions. It sure what you mean by changed webhook to something from webhook.site

I've looked at this site and can't find any info 

My issue is with certificate I'm sure as I get the error cannot access private key of certificate

Can I ask how did you create your externally signed certificate as when I do it in GoDaddy with private key it says it can't access it

Thanks

**Comment by WezMorris** [comment]
I had a wildcard certificate for my domain already in pfx format with a password. I didn't need to include anything else. 

When are you getting the error? When browsing to https://<sitename>/logs?

**Comment by doucheface1** [comment]
I have a wildcard in pfx too but when I deploy code the roles keep recycling saying Cannot access private key

Can I ask what you have set in the cloud service under properties for 

Servicednsname
Servicecname

And also what you set your webhook for calling to


Thanks

**Comment by WezMorris** [comment]
So my dns is the cloudapp site, and the cname is my domain (which I've set up as a cname in my domain management panel)

like so:
![image](https://user-images.githubusercontent.com/38036485/87660908-b589a380-c757-11ea-92f3-9d4d6d0f5e87.png)

Check your thumbprint maybe?

**Comment by doucheface1** [comment]
My thumbprint is correct and matches wildcard.

What do you have webhook for calling set to 

Thanks

**Comment by WezMorris** [comment]
My webhook is pointing to the site i have in cname (sitename.mydomain.com/api/calling).

Are you sure the webhook is being hit when you receive a phone call? If it's not then there's likely a problem at the policy side rather than your bot or web service

**Comment by doucheface1** [comment]
How do I check that is there a way to debug this or any logs I can check

**Comment by doucheface1** [comment]
Also when you created your policy what did you use for

Set-CsTeamsComplianceRecordingPolicy -Identity <policyIdentity> -ComplianceRecordingApplications ` @(New-CsTeamsComplianceRecordingApplication -Parent <policyIdentity> -Id <objectId>)

**Comment by WezMorris** [comment]
> How do I check that is there a way to debug this or any logs I can check

Go to https://webhook.site/ and copy the url given, then paste that in the bot channel webhook url. 
After about 30 mins or so it'll take effect. Then call the user who you have set up with the policy. If the policy is correct, you should see requests start to appear in the left hand pane. This is the data that teams should be sending to your bot. 

If there's nothing there, check your policy. If there is something, and there's still an issue, then it's likely a problem with your service

**Comment by WezMorris** [comment]
> Also when you created your policy what did you use for
> 
> Set-CsTeamsComplianceRecordingPolicy -Identity -ComplianceRecordingApplications ` @(New-CsTeamsComplianceRecordingApplication -Parent -Id )

Set-CsTeamsComplianceRecordingPolicy -Identity TestPolicy -ComplianceRecordingApplications ` @(New-CsTeamsComplianceRecordingApplication -Parent TestPolicy -Id fc78d84b-5875-4226-b56f-4dc8dc4d6752)

(test policy being the name of the policy you just made and the guid being the application id of your bot)

**Comment by doucheface1** [comment]
ill follow the above you have been a great help


thanks

**Comment by doucheface1** [comment]
if i use the bot app id for policy it fails as below


![image](https://user-images.githubusercontent.com/45433448/87682027-43c15200-c777-11ea-8663-09de997fe4d4.png)
![image](https://user-images.githubusercontent.com/45433448/87682028-44f27f00-c777-11ea-961d-0609e1a6b31b.png)

**Comment by doucheface1** [comment]
PS C:\WINDOWS\system32> Set-CsTeamsComplianceRecordingPolicy -Identity soteria.compliance -ComplianceRecordingApplications ` @(New-CsTeamsComplianceRecordingApplication -Parent soteria.compliance -Id 177949ec-7257-4cb9-bbdf-0c5785d04599)
T id 177949ec-7257-4cb9-bbdf-0c5785d04599 is not a valid application instance ObjectId.
    + CategoryInfo          : InvalidArgument: (Id=177949ec-725...vitationCount=1:ComplianceRecordingApplication) [New-CsTeamsCom 
   p...dingApplication], ArgumentException
    + FullyQualifiedErrorId : CustomValidationFailed,Microsoft.Rtc.Management.Internal.NewTeamsComplianceRecordingApplicationCmdl 
   et
    + PSComputerName        : admingb1.online.lync.com

**Comment by doucheface1** [comment]
in the instructions it tells you not to use the bot app ID for poicy

**Comment by WezMorris** [comment]
Oh sorry, that's my mistake. When you made the Application Instance with New-CsOnlineApplicationInstance, it provided a new object id. We used that.

**Comment by doucheface1** [comment]
using webhook site i get 

![image](https://user-images.githubusercontent.com/45433448/87781750-319fec00-c829-11ea-8b34-c77d58840f83.png)

so policy is working

**Comment by doucheface1** [comment]
what do you set below to in bot

Configuration
Messaging endpoint


Enable Streaming Endpoint

**Comment by doucheface1** [comment]
under settings

Configuration
Messaging endpoint


Enable Streaming Endpoint

**Comment by WezMorris** [comment]
Messaging endpoint: empty

Enable Streaming Endpoint: unticked. 

I guess next we look at your service, is that up and running?

**Comment by doucheface1** [comment]
whats the service called?

**Comment by WezMorris** [comment]
I mean the cloud service, where you deployed this sample

**Comment by doucheface1** [comment]
ok ill post screen shots the error the cloud service throws out is cannot access certificate private key

**Comment by doucheface1** [comment]
`ok made progress change my cert to a legacy cert with key exchange with godaddy and services are running!!!! calls still dont connect and go to voicemail but maybe im being too quick and need to give it time

**Comment by doucheface1** [comment]
its working!!! was the cert all along cloud service is up and running. for everyones info if youm use godaddy for a cert then when creating CSR you need to choose legacy Key on first request screen. 

2048 bit encryption 

and make sure you select Exchange not signature in key type

Big thanks to @WezMorris what a legend for assistance

**Comment by devanshuGit** [comment]
@doucheface1 @WezMorris i am trying to setup solution but for me cloud service is not getting up. I keep getting this issue
Using domain generated from freenom and have wildcard certificate for the domain issued from lets encrypt. Same is uploaded in the cloud service.

Servicednsname - fa7be9a07a064238ab453b0bdd21b708.cloudapp.net
Servicecname - buildingplatform.tk

I have followed all the instructions but still not able to make it up. Any help in this regard would be helpful
DNS record
![image](https://user-images.githubusercontent.com/9657686/128589621-57fe301c-79aa-4c55-8270-45ad1893b0e4.png)


Recovering role... Unhandled Exception: No such host is known at System.Net.Dns.GetAddrInfo(String name) at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) at System.Net.Dns.GetHostEntry(String hostNameOrAddress) at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in C:\My Workspace\Teams Recording\PolicyRecording\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 380 at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in C:\My Workspace\Teams Recording\PolicyRecording\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 231 at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\My Workspace\Teams Recording\PolicyRecording\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 92 at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum) at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0() at

**Comment by devanshuGit** [comment]
@WezMorris @doucheface1 i got the issue resolve at least it seems so as worker role is now in running status. However when i deployed from VS, Azure activity log initially couple of times it throws error for System.Net.Http dll error not found from the path specified. This assembly particularly being referenced in Sample.Common project. 
I noticed that targetframework specified in Sample.Common is .Net 4.6.1 or net2.0 but other projects are targeting V4.6.2. I am suspecting this could be the issue and cloud service is getting the problem

As i place call from non-recorded user to recorded user, it never succeed and gives this error
![Recording policy error in teams](https://user-images.githubusercontent.com/9657686/129361203-160916ec-5c74-4d60-9eef-782cc097406c.png)
