### ISSUE TITLE
Microsoft.Graph namespace conflict

### ISSUE THREAD

**Issue by ravriel** [microsoftgraph/microsoft-graph-comms-samples#27]
**Describe the issue**
Latest Microsoft.Graph package (1.12.0) cannot be added to a project with latest graph communications packages (1.0.0-prerelease.494) because of namespace conflicts.

For example: 
'Microsoft.Graph.Identity', 'Microsoft.Graph.IdentitySet', exist in both 'Microsoft.Graph.Communications.Core' and 'Microsoft.Graph' packages.

'Microsoft.Graph.EnumConverter' exists in both 'Microsoft.Graph.Communications.Core' and 'Microsoft.Graph.Core' packages.

**Expected behavior**
No conflicts.

**Graph SDK (please complete the following information):**
 - Version 1.0.0-prerelease.494

**Comment by ksikorsk** [comment]
Hi,
We are working on resolving file collisions with MSGraph SDK.

Thanks,
Kamil

**Comment by pheemery2** [comment]
Any update ? I also ran into this.

**Comment by ksikorsk** [comment]
@pheemery2 latest sample and SDK sync is compatible with Microsoft.Graph SDK.
