### ISSUE TITLE
Using the PolicyRecordingBot outside of Azure

### ISSUE THREAD

**Issue by hwilliamsdtx** [microsoftgraph/microsoft-graph-comms-samples#275]
For the PolicyRecordingBot, is it possible to run it outside of Azure?

I'm not referring to the DNS side, but to the VM deployment - currently we use it in Azure Cloud Services.

I looked at https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/143, and there it seems the problem is the Microsoft.Skype.Bots.Media SDK.  

That issue was in January 2020.  Is this still the case?

Thank you in advance.

**Comment by ssulzer** [comment]
There's no change: running the Bot Media SDK outside of Azure is not supported.

In general, it's also not recommended: assuming the bot is joined into a Teams meeting, the bot's peer is an endpoint running in Azure, and it's best to keep the real-time media session between the bot and the Teams meeting within the Azure network.

**Comment by hwilliamsdtx** [comment]
Thank you.
