### ISSUE TITLE
Question: Can the PolicyRecordingBot be run locally?

### ISSUE THREAD

**Issue by andir78** [microsoftgraph/microsoft-graph-comms-samples#278]
Please excuse my ignorance here but I'm new to Bot Framework and Microsoft Graph.  I have downloaded this sample and working with my Tenant Admin (who did all the 'setup' type activities in the Azure Portal side) I have updated the code to contain the necessary values for the cert thumbprint, appID, etc.  After overcoming initial build issues around having a CNG cert and not a CSP one we can now get the project to build and run without throwing an exception.   However, the problem I have is that I cannot seem to access the web/api interface (i.e. http://localhost:9441/logs) so that I can step into the controllers within the CRFrontEnd projectjust so I can have a nosey and how this thing works before i start looking into the areas triggered by the call events.

When i access the NGrok URIs they return a 502 Bad Gateway due to the above mentioned endpoint(s) not being there.

I do have some MVC and WebAPI experience and to sanity check myself I have even created a simplistic 'do-nothing' bot from the VS2019 template and i can spin that up and access it's web interface (granted it's hosted in IISExpress) and step into the controller code fine....................so, what am i missing here......been puzzled for a couple of days now :(

**Comment by ovninosa** [comment]
+1 please, I want to know the same thing here.

**Comment by andir78** [comment]
What fixed it for me was editing file [https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot/FrontEnd/Http/HttpConfigurationInitializer.cs](url) to have         
`httpConfig.DependencyResolver.BeginScope();` right before the `httpConfig.EnsureInitialized();`.  After doing that i was able to at least talk with the Localhost endpoint(s)

**Comment by ovninosa** [comment]
@andir78 so with that modification you can run the entire sample on your local enviroment? or there is another issue?
thanks

**Comment by andir78** [comment]
@ovninosa apologies for the tardy response.  To answer your question, I honestly cannot remember as i feel like i've had to modify and rewrite so much to get to where i am.  It's pretty hard to get any meaningful support from anywhere too as it seems so 'bleeding edge'.
Closing now though, as i forgot to do so in July
