### ISSUE TITLE
Unable to raise an Incident with IncidentBot from RemoteMediaSamples

### ISSUE THREAD

**Issue by Whitefern** [microsoftgraph/microsoft-graph-comms-samples#28]
**Describe the issue**
Hi,

I've been following this article [Getting Started with the Remote Media Graph Calling Bot Samples](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/RemoteMediaSamples/Getting%20Started%20with%20the%20Remote%20Media%20Samples.md) and unable to get the bot to raise an incident.

When I make a post request from Postman Desktop is returns an error.
If I'm using the website publish to Azure I get '502 - Web server received an invalid response while acting as a gateway or proxy server.'

If I'm using IIS Express and Ngrok and can debug my code and get this exception "Code: UnknownError\r\nMessage: {\"message\":\"Not Found\"}\r\n\r\nInner error\r\n".

I'm sending the below JSON as a post request and the last line it attempts before throwing the expect is from the OnlineMeetingHelper.cs Line 57 (var meeting = await meetingRequest.GetAsync().ConfigureAwait(false);). It does seems to matter if the meeting is in the future, happening now or in the past.

Can anyone give me tell me what I'm doing wrong

**Code Snippet**
{
  "name": "ABC", 
  "time": "2018-10-19T14:54:23Z", 
  "tenantId": "_TenantGuid_",
  "objectIds": [
    "_MyUserGuid_",
    "_TestUserGuid_"
  ],
  "meetingId": "82562484#",
  "joinURL": "https://teams.microsoft.com/l/meetup-join/_ChannelId_@thread.skype/_MessageId_?context={'Tid':'_TenantGuid_','Oid':'_MyUserGuid_'}",
  "removeFromDefaultRoutingGroup": true,
  "allowConversationWithoutHost": true
}

**Graph SDK (please complete the following information):**
 - Version beta

**Comment by kanchm** [comment]
Please supply either the `meetingId` or the `joinURL`. Assuming this is not a cloud-video-interop enabled meeting, provide only the `joinURL`.  We will update the sample documentation to address this confusion.  [Get OnlineMeeting](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta) is reserved for CVI scenarios.

Refer to our other [sample](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/LocalMediaSamples/HueBot/HueBot#test) to obtain a valid join url.

**Comment by Whitefern** [comment]
Thanks @kanchm,

Working great. Just need to understand the code to add something similar to my bot. :)

Kind Regards
Darren
