### ISSUE TITLE
How Bot may detect video/vbss starts/stops sharing

### ISSUE THREAD

**Issue by franciscojgonzalez** [microsoftgraph/microsoft-graph-comms-samples#282]
I would like to know if there is an event (or some way) to detect when a Participant has started sharing video and vbss, and also when he stops sharing in both cases. 

I first tried with 

```
        event EventHandler<VideoReceiveStatusChangedEventArgs> VideoReceiveStatusChanged;

        event EventHandler<VideoSendStatusChangedEventArgs> VideoSendStatusChanged;
```
but it seems that those events only detect when the media stream is available to send/receive subscriptions.

Any suggestions on this would be much appreciated.

**Comment by 1fabi0** [comment]
You can achieve this by using the  `Call.Participants.OnUpdated` Event and then the ` participant.OnUpdated` Event just like used in the [Hue Bot Sample](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/18f54fb75b091ad57c840da3016f3d013fbd18f5/Samples/V1.0Samples/LocalMediaSamples/HueBot/HueBot/Bot/CallHandler.cs#L93) (you should adjust it with your own logic)

**Comment by ovninosa** [comment]
@1fabi0 how can I get that info on the HueBot?

I run the enviroment local on my pc, the joinCall method return the information, I think that is the connection from the bot, but when I activate the camera of any of the members of the call I never receive anything in the participant.OnUpdated

**Comment by franciscojgonzalez** [comment]
Hey, I thought I did answer in this post, but I now see I didn´t!

So, first of all, @1fabi0 thank you very much for your reply, this did actually worked for me!. One important thing to take care of is that the OnUpdated event is not raised only with video/vbss on/off, but it may come with other updates, as expected. So you´d have to detect the first event when the participant started/stopped sharing video or vbss, and you get it working.

@ovninosa , could you please share more details on your issue? I tried this with my own code, but similar to HueBot, and it worked.

**Comment by ovninosa** [comment]
@franciscojgonzalez por tu nombre me imagino que hablas español.

tengo corriendo la aplicacion localmente con ngrok. 
hice todos los pasos correspondientes del readme.md.
cuando llamo al metodo joinCall desde postman me devuelve por ejemplo esta respuesta:

`{
    "callURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/",
    "callSnapshotURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/scr",
    "callHueURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/hue",
    "callsURL": "http://11bddb9bc358.ngrok.io:9444/calls/",
    "serviceLogsURL": "http://11bddb9bc358.ngrok.io:9444/logs/421f3000-ed1f-466b-b501-a5143e0cd17a"
}`

No veo que ningun bot entre a la llamada pero debugueando el proyecto retorna bien ciertos valores como el appId y demas, pero ya en participantes veo que el count es 0.
Ingreso desde mi PC donde configure al aplicacion del bot en teams, pero en ningun momento salta algun breakpoint en los metodos: 

`OnVideoMediaReceived
OnDominantSpeakerChanged
OnParticipantsUpdated`

Ademas si llamo al metodo changehue, debugueando veo que cambia el color, en la llamada no veo ninguna diferencia.

Puede ser que me este faltando algun paso que no este en la documentacion?

----------------

@franciscojgonzalez by your name I imagine you speak Spanish.

I have running the application locally with ngrok.
I did all the corresponding steps of the readme.md.
when I call the joinCall method from postman it returns for example this answer:

`{
    "callURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/",
    "callSnapshotURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/scr",
    "callHueURL": "http://11bddb9bc358.ngrok.io:9444/calls/421f3000-ed1f-466b-b501-a5143e0cd17a/hue",
    "callsURL": "http://11bddb9bc358.ngrok.io:9444/calls/",
    "serviceLogsURL": "http://11bddb9bc358.ngrok.io:9444/logs/421f3000-ed1f-466b-b501-a5143e0cd17a"
}`

I do not see any bot enters the call but when debugging the project returns certain values ​​such as the appId and others, but already in participants I see the count is 0.
I enter from my PC where I configure the bot application in teams, but at no time does any breakpoint jump in the methods:

`OnVideoMediaReceived
OnDominantSpeakerChanged
OnParticipantsUpdated`

Also if I call the changehue method, on debug I see the property color changes, in the call I don't see any difference.

Could it be that I am missing a step that is not in the documentation?

**Comment by franciscojgonzalez** [comment]
@ovninosa 

Si! Bueno, sobre el error, a mí me pasó lo mismo y estaba relacionado con el certificado SSL. Tiene que ser **obligatoriamente** un certificado `wildcard` y **no puede ser** `self-signed`. Si estás desplegando en local, me temo que la versión gratuita de ngrok no te permite generar certificados SSL de este tipo. Sin embargo, si tienes una licencia de ngrok, puedes generar el certificado desde la propia web.

_________________________________________

Yes! Well, about the error, the same thing happened to me and it was related to the SSL certificate. It **MUST** be `wildcard` certificate and **CANNOT** be` self-signed`. If you are deploying locally, I´m afraid that the free version of ngrok does not allow you to generate SSL certificates of this type. However, If you own a license for ngrok, then you just need to generate that certificate from ngrok´s website.

**Comment by ovninosa** [comment]
@franciscojgonzalez tengo un certificado ssl wildcard, lo configure en el portal de azure en un vault como explican en el readme, luego cree un dns cname que apunta a los distintos endpoints de ngrok.

las pruebas que lograste hacer funcionar fueron locales o deployando en azure?

muchas gracias

-----------------

I have an wildcard  ssl certificate, It was alredy configured in the azure portal on a vault as explained in the readme, then I create a dns cname that points to the different ngrok endpoints.

to run the HueBot, did you run on local or deployed to azure?

thank you

**Comment by 1fabi0** [comment]
First of all you don't really need a wild card certificate for debug essential is that it is not self signed and for the right address. Also the public port of ngrok should not be in the dns CName it should be in the appsettings right behind your Address that points to ngrok. 

But the web interface of ngrok can really help out to find out what is happening with the bot on debug, but I think it does not belong in this thread anymore

**Comment by ovninosa** [comment]
Repo:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot

Local test:
---------------------------

Register the bot on azure:
```
https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/register-calling-bot.html

Download AppStudio
Create the bot app 
```

---------------------------

teams calls webhook url:
`https://bot.contoso.com/api/calls`

---------------------------

Permissions granted to the teams registration:
```
Calls.AccessMedia.All
Calls.Initiate.All
Calls.JoinGroupCall.All
Calls.JoinGroupCallAsGuest.All
```

---------------------------

wildcard certificate:
`*.contoso.com`

---------------------------

DNS config:
```
*.contoso.com

0
CNAME
0.tcp.ngrok.io

1
CNAME
1.tcp.ngrok.io

2
CNAME
2.tcp.ngrok.io

bot
CNAME
xxxxxxxx.ngrok.io

0.bot
CNAME
0.tcp.ngrok.io

1.bot
CNAME
1.tcp.ngrok.io

2.bot
CNAME
2.tcp.ngrok.io

```
---------------------------

powershell configuration:
```
.\configure_cloud.ps1 -p .\V1.0Samples\LocalMediaSamples\HueBot `
    -dns bot.contoso.com `
    -cn bot.contoso.com `
    -thumb xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx `
    -bid xxxxxxx `
    -aid xxxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxxxx `
    -as xxxxxxxxxxxxxxxxxxxxxx
```
	
---------------------------

Ngrok config:

```
authtoken: xxxxxxxxxxxx
tunnels:
    signaling:
        addr: 9442
        proto: http
        
    media: 
        addr: 8445 
        proto: tcp
```

---------------------------
	
Postman:

```
url: http://xxxxxxxx.ngrok.io/joinCall
body:
{
  "JoinURL": "https://teams.microsoft.com/l/meetup-join/xxxxxxxxxxxxxxxxxxxx"
}	
response:
{
    "callURL": "http://xxxxxxxx.ngrok.io:9444/calls/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx/",
    "callSnapshotURL": "http://xxxxxxxx.ngrok.io:9444/calls/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx/scr",
    "callHueURL": "http://xxxxxxxx.ngrok.io:9444/calls/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx/hue",
    "callsURL": "http://xxxxxxxx.ngrok.io:9444/calls/",
    "serviceLogsURL": "http://xxxxxxxx.ngrok.io:9444/logs/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx"
}
```

---------------------------

With 9444 port:
```
url: http://xxxxxxxx.ngrok.io:9444/calls/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx/hue
response:
Fail (timeout)
```


Without the port:
```
url: http://xxxxxxxx.ngrok.io/calls/ef1f3000-a01f-4391-a3a6-xxxxxxxxxxxx/hue
response:
{
	"Blue"
}
```



---------------------------

I can debug this methods:
```
change hue (change the hue in memory, but I don't see any change over the call)
get hue (return the setted hue)
getsnapshot (bitmap = null always)
```

---------------------------

I never receive any type of video or audio on these methods even when users come to the call, talk, or start video:
```
OnVideoMediaReceived 
OnDominantSpeakerChanged 
OnParticipantsUpdated
```

---------------------------

App on teams client:
q1) Install on the client? the documentation doesn't have any type of tip on that, just "save" is the last step
q2) There is a chance to run the bot on mobile client? Teams on mobile doesn’t have apps option

Rest use:
q3) The 9444 port doesn't work on local, is okay without port? or there is a problem with the load balancer in Fabric? without port I get a few responses

Video and audio frames:
q4) What is missing to receive video frames and audio?

**Comment by ovninosa** [comment]
@franciscojgonzalez @1fabi0 

If any of you can help me with my previous question will be amazing.
I think i'm too close to get the differents video frames but I don't know where is the issue.

Thanks

**Comment by 1fabi0** [comment]
@ovninosa can you please share your ngrok requests you can review them in the ngrok web interface

**Comment by ovninosa** [comment]
@1fabi0 

Yes, here are a few calls from the ngrok inspect.
I have my user joined to the call, then use the joinCall or before my user join the call from teams clients.
In any case there is no video or audio frames coming to:
```
OnVideoMediaReceived 
OnDominantSpeakerChanged 
OnParticipantsUpdated
```

POST /joinCall | 200 OK | 7.05s
```
{
    "callURL": "http://a379a235227a.ngrok.io:9444/calls/591f3000-ca1f-4aed-9513-43697167e9b3/",
    "callSnapshotURL": "http://a379a235227a.ngrok.io:9444/calls/591f3000-ca1f-4aed-9513-43697167e9b3/scr",
    "callHueURL": "http://a379a235227a.ngrok.io:9444/calls/591f3000-ca1f-4aed-9513-43697167e9b3/hue",
    "callsURL": "http://a379a235227a.ngrok.io:9444/calls/",
    "serviceLogsURL": "http://a379a235227a.ngrok.io:9444/logs/591f3000-ca1f-4aed-9513-43697167e9b3"
}
```

If I use the 9444 port any request works:
GET /calls/591f3000-ca1f-4aed-9513-43697167e9b3/hue | 200 OK | 17.99ms
```
200 OK
"Green"
```

GET /calls/591f3000-ca1f-4aed-9513-43697167e9b3/scr | 404 Not Found | 3.27s
`404 Not Found`

PUT /calls/591f3000-ca1f-4aed-9513-43697167e9b3/hue | 200 OK | 2.84s
`200 OK`

**Comment by franciscojgonzalez** [comment]
I think @1fabi0 might shade more light on this, but, shouldn´t you use the same url in the postman requests which you have configured over your CNAMEs and Powershel script? 

I mean, I can see you´ve created CNAME entries for domain `contoso.com`, and configured the powershell script to set up the cn, and dns using the url `bot.contoso.com`. But later you´re doing the requests in postman using the ngrok endpoints. Have you tried to make requests to `bot.contoso.com/joinCall` ?

**Comment by 1fabi0** [comment]
No the URL configured in the Power shell is only for Media but it's likely that ngrok does not forward to port 9444 what is fine try to execute the links you get back after join localhost instead of forwarding them to ngrok when still nothing works please share the incoming requests of ngrok you can review them in the [Ngrok Web Interface](http://localhost:4040/inspect/http)

**Comment by franciscojgonzalez** [comment]
Yeah, makes sense. I did no test my bot in local, but directly within Azure SF, so maybe I´m misleading some concepts. I feel like I´m making a bit noise with this guys, so I leave the conversation. Regarding my thread question, it was solved so please, feel free to close this thread whenever you consider.

Thank you!

**Comment by franciscojgonzalez** [comment]
Closing this issue as my inital question was solved.
