### ISSUE TITLE
Bot doesn't receive participants notifications from Graph API when the participants join to the meeting as guest

### ISSUE THREAD

**Issue by JonatanMedinilla** [microsoftgraph/microsoft-graph-comms-samples#285]
**Describe the issue**
I've been testing the bot in a meeting with guest participants and the bot didn't receive the graph notification from some of those participants. In this scenario, the Bot has Graph API permissions for the tenant A (tenant that hosts the meeting), and the invited participants are from tenant B and tenant C. We received the notifications of the tenant A and tenant B participants, but couldn't received the participants notifications from tenant C.

**Expected behavior**
I expected to receive the notifications of all guest participants.

**Graph SDK (please complete the following information):**
SDK Version 1.19.0.25-alpha

**Comment by philomathikus** [comment]
@JonatanMedinilla We are soon attempting to receive similar notifications - would you mind sharing the fix?

**Comment by JonatanMedinilla** [comment]
@philomathikus Hi philo, I don't know if your scenario is gonna be the same, but something that we detected while debugging the bot's samples is that we receive all the user's notifications, including the guests but the notifications aren't the same.  For example, we were filtering the participants by following the same logic as one of the bot's samples. This sample considers a participant as user if the User identity property is not null, but we found that the guests' participants always have that property in null but contain a "guest" key inside the identity additional data. So, as mentioned before, you are gonna to receive all the participants notifications (including guests) but you should check the participants' resources data in order to know what to do with the notification.

**Comment by philomathikus** [comment]
@JonatanMedinilla Thank you for the quick and insightful reply!

**Comment by philomathikus** [comment]
@JonatanMedinilla FYI: added you on LinkedIn (Max) to stay in touch :)
