### ISSUE TITLE
H264 video delivered with artifacts

### ISSUE THREAD

**Issue by JonatanMedinilla** [microsoftgraph/microsoft-graph-comms-samples#289]
**Describe the issue**
I’ve been testing the Bot in a meeting and saving the H264 buffers in a file but, when I play the video content in different players like gst-play, ffplay (not VLC, it works fine) I get a poor video quality. The video frames are displayed with artifacts specially during fast movements. Few weeks ago, I was able to save the H264 buffer into a file and play it with not quality issues (artifacts in frames) using the players mentioned before (gst-play, ffplay from ffmpeg and VLC).

Also, I requested the raw NV12 video rendition for the video socket and saved the stream into a file without any kind of compression and when I play this stream it has good quality and all frames are displayed correctly (without artifacts).

Moreover, why I was able to play the H264 content with good quality using different players and not now, a change in the elementary H264 stream was introduced recently?

Last but not least, regarding the color format should received video be delivered in, I assume when we specify NV12 we got raw video but analyzing the pc network bandwidth I found it has a similar bandwidth consumption as when we specify H264. Is it correct to assume that the bot receives compressed video and decompresses it to deliver NV12? Despite the bandwidth consumption is the same, the size of the files written to the disk are different.

**Sample pictures**
*H264 video captured with gstreamer*
![image](https://user-images.githubusercontent.com/23441277/88843153-09b07100-d1b7-11ea-82e6-99ab929f3bd6.png)

*H264 video buffers written in disk and reproduced in ffplay after closing the file*
![image](https://user-images.githubusercontent.com/23441277/88843896-34e79000-d1b8-11ea-96a6-12ea4b9ecef3.png)

Same video file reproduced in VLC
![image](https://user-images.githubusercontent.com/23441277/88843958-4c267d80-d1b8-11ea-9dae-8383335ab83c.png)

*NV12 video captured with gstreamer*
![image](https://user-images.githubusercontent.com/23441277/88843719-f356e500-d1b7-11ea-969f-2149d6089e9e.png)

*NV12 video buffers written in disk and reproduced in yuvplayer after closing the file*
![image](https://user-images.githubusercontent.com/23441277/88843800-12557700-d1b8-11ea-9546-c2294a4a21d2.png)

**Graph SDK (please complete the following information):**
SDK Version 1.19.0.25-alpha

**Comment by andir78** [comment]
How are you saving the H.264 buffers to a file/disk?  I cannot for the life of me find an example.

**Comment by lcarli** [comment]
Same here as andir78 said:  I'm struggling to save Audio and Video into a file...

**Comment by andir78** [comment]
@lcarli I've figured out the 'save' side of things now.........

For the audio I took inspiration from [HERE](https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling/issues/19)

for the video I simply appended the buffer (containing the H.264 Frame) to a byte array field using [this approach ](https://stackoverflow.com/a/415839/1841939) and then on the dispose wrote the final array out to disk with a H.264 extension.

VLC can play it....the initial couple of seconds is jittery though.  The frames appear to be the ones from the dominant speaker so in my case i was testing with 2 of my own accounts one on the desktop app and one on the iOS app.  So when i spoke it jitters awkwardly between the 2 'feeds' which are in different aspect ratios so i still have to figure out.

Finally for me there's no audio therefore there's still another step for the solution i'm creating whereby i'll have to combine the audio and video into a finished article.....which i have no idea at present how to do :(

**Comment by lcarli** [comment]
Thanks, @andir78 ! Now I got it how can I handle all audios!

**Comment by JonatanMedinilla** [comment]
Issue closed. We found the bug that was causing it. Looks like we subscribed to the VideoMediaReceived event handler twice, so we sent two frames for each one received. @andir78 @lcarli We were saving only the video buffers to disk just for testing and didn't use the metadata. We didn't try to mux audio & video from C#. If you want to do that, I will recommend do some research on GStreamer, and push the buffers to a gstreamer pipeline, so then you can use a fileSink to write the muxed content to a file.

**Comment by vivekmurli** [comment]
> Issue closed. We found the bug that was causing it. Looks like we subscribed to the VideoMediaReceived event handler twice, so we sent two frames for each one received. @andir78 @lcarli We were saving only the video buffers to disk just for testing and didn't use the metadata. We didn't try to mux audio & video from C#. If you want to do that, I will recommend do some research on GStreamer, and push the buffers to a gstreamer pipeline, so then you can use a fileSink to write the muxed content to a file.

@JonatanMedinilla  the comment is useful and I have started researching on GStreamer , However since you mentioned that you are saving just the streams to the disk , is the video quality good and do we have to compulsorily use GStreamer to achieve this? , would you mind helping me out with the code sample you have used for both Audio and Video recording in the respective events? 

My end goal is to create a bot for auditing purpose that would record over 100+ calls automatically on daily basis and then save the recorded content to streams.

Any help would be appreciated.

Regards,
Vivek

**Comment by irwinwilliams** [comment]
Hey @JonatanMedinilla did you start with a sample? If so, which one please?

**Comment by sahilupadhye** [comment]
Hi Vivek, I am working for similar project which is a bot recording for audit purpose. Can you please enlighten how did you finally settle with saving the content? and do you face A/V sync issue ?

**Comment by sahilupadhye** [comment]
> > Issue closed. We found the bug that was causing it. Looks like we subscribed to the VideoMediaReceived event handler twice, so we sent two frames for each one received. @andir78 @lcarli We were saving only the video buffers to disk just for testing and didn't use the metadata. We didn't try to mux audio & video from C#. If you want to do that, I will recommend do some research on GStreamer, and push the buffers to a gstreamer pipeline, so then you can use a fileSink to write the muxed content to a file.
> 
> @JonatanMedinilla the comment is useful and I have started researching on GStreamer , However since you mentioned that you are saving just the streams to the disk , is the video quality good and do we have to compulsorily use GStreamer to achieve this? , would you mind helping me out with the code sample you have used for both Audio and Video recording in the respective events?
> 
> My end goal is to create a bot for auditing purpose that would record over 100+ calls , meetings [with good audio and video quality] automatically on daily basis and then save the recorded content to MS streams.
> 
> Any help would be appreciated.
> 
> Regards,
> Vivek

Hi @vivekmurali
 
I am working for similar project which is a bot recording for audit purpose. Can you reply how did you finally settle with saving the content? and do you face A/V sync issue ?
