### ISSUE TITLE
[ComplianceRecordingBot] Use of self-signed wildcard SSL certificate for cloud service -testing

### ISSUE THREAD

**Issue by Manojb86** [microsoftgraph/microsoft-graph-comms-samples#299]
Hi,

I'm working on a compliance policy recording bot sample.

I would like to know, whether it is okay to use self-signed wildcard certification for cloud service deployment? or is it causing to any errors or service not working properly because of the self-signed SSL? have any try or experience related to this?

if anyone can help me with this, that would be really great.

Thanks

**Comment by ashagraw91** [comment]
You have you use real SSL for cloud deployment, self signed will not work. For local debugging self signed will work

**Comment by Manojb86** [comment]
Oki. Thanks.
I used a self-signed cert for cloud deployment. All went well without an error. But compliance bot not getting the call and cloud service logs or calls URLs are not working. Maybe the use of a self-signed cert can be the reason. But need to check more.
