### ISSUE TITLE
Auth related questions

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-comms-samples#309]
Hi guys, 

building something loosely related on the audio visual playback bot and confused about a few bits - would be great if anyone could give an answer/indication to the questions below

1. I'm using the v2 endpoints for auth, I can only get the app call permissions to return in a token when a tenantId is populated (i.e. using "common" or "organizations" doesn't return them) - is that expected? The example code does have a fall back to use "common" but presumably this fallback cannot ever work assuming that permissions won't be returned in the token in this scenario?? (or am I misunderstanding something)? 

2. In `AuthenticateOutboundRequestAsync` of the `AuthenticationProvider` - where would tenant Id actually be populated from? this is a call handled by the sdk, and so I'm just trying to understand when to expect this value to be set.

**Graph SDK (please complete the following information):**
 - https://graph.microsoft.com/v1.0

thanks guys.

**Comment by 1fabi0** [comment]
Sorry for the late response
1. for "common" or "organizations" you would need to be priveleged by microsoft then you would be able to use "common" or "organizations" with your application
2. normally tenant id is provided from the teams join link or if you call the bot from teams it is provided with the call request

**Comment by AlexSapple** [comment]
thanks @1fabi0 - I'll close this off.
