### ISSUE TITLE
Could not load file or assembly 'Microsoft.Rtc.Internal.Media.DLL' or one of its dependencies. The specified module could not be found

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-comms-samples#318]
**The issue**
Hi Guys, this may well be related to [122] (https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/122). I'm getting the same error (see title). I've been through that issue and I don't have a solution that is working for me. I'm not at this moment trying to deploy anything in to service fabric - i'm just trying to test locally on my machine. I'm not entirely sure if it's valid setup - but.. I can get as far as joining a call/ending a call and reading webhook notifications via ngrok. My issue starts as soon as I try to pull in the **Microsoft.Skype.Bots.Media** dll. 

* First issue is the version of the dll - if you pull in Microsoft.Graph.Communications.Calls.Media (latest stable version) using Nuget, it's isn't happy as it states that there is no corresponding version of the Skype bots media dll. I had to go back as far as **V1.1.0** of that dll before it pulls in the skype dll dependency. 

* The above error occurs when attempting to debug. In my case, I'm just trying to fire up a webapi layer in to the bot and I'm running that on IISExpress. (so that's a .net framework 4.7.2. API with a .net framework 4.7.2 class library as the bot). I see that a load of project references get added under a folder called "Skype_media_lib". Do I need to do anything with these? they just appear with the nuget pull.

other things I've tried - I'm running on x64 config and I've installed visual c++. 

I gather there is more work needed to get these working beyond simply pulling from nuget, but I haven't really got any idea what. Would love to get some more advice.

many thanks.

**Comment by AlexSapple** [comment]
I believe this has already been answered in various forms - but keeps coming up. For me, re-writing as a console application with a self hosted owin webapi seems to resolve (well at least this particular issue).

**Comment by bijaykush** [comment]
@AlexSapple 
I am getting same type of error running the Policy Recording bot with ReceiveUnmixedMeetingAudio = true.
![image](https://user-images.githubusercontent.com/11793622/104739339-b3d48300-576e-11eb-8761-4130f1052ef4.png)

And without this ReceiveUnmixedMeetingAudio flag, everything is working fine. I am testing this locally. 

Can you please help me with this?

**Comment by AlexSapple** [comment]
Hi @bijaykush 

This is a different error arising from a different usecase - my original issue was associated with Skype media dll dependencies running in windows rather than an iis environment. You error above looks like a null argument somewhere in amongst it all.

Without knowing anything much about this - the docs state that 

> In UnmixedMeetingAudio mode, the bot will receive only unmixed audio and not both unmixed and mixed.

and 

> In order to receive both mixed and unmixed audio simultaneously, the bot must establish two separate calls into the meeting.

so as a complete guess, I'd firstly say, make sure you are not trying to do anything that requires both mixed and unmixed.
