### ISSUE TITLE
[PolicyRecordingBot] - Http not working after successful deployment from VS2017

### ISSUE THREAD

**Issue by simonso1224** [microsoftgraph/microsoft-graph-comms-samples#321]
Apologies for being a newbie here, and possibly this might be a very dumb question to ask. 

**What has been done**
My goal is to setup PolicyRecordingBot and test out Teams compliance recording setup. Following readme.md file closely, with the original unchanged cloned PolicyRecordingBot solution/project, I am able to publish/deploy using VS2017 successfully to Azure Cloud Service. I have only set 1 instance in Standard D2_v3 for the CRWorkerRole, and it is reported as Running. 

**The Issue**
https://<myname>.cloudapp.net/logs is not accessible. RDP-ing into the VM and tried in IE http://localhost:9441/ is also unreachable. AzureTools -> Utils -> Check Input Endpoints indicates that https://10.218.0.4:9441/, :10110/, :8445 are all showing ConnectFailure. netstat /n /a does not show that any of the TCP ports 9441, 10110 or 8445 are opened.

**The Question**
I am running out of ideas on how to troubleshoot this. Is there something missing or an error that I've missed? Could you point me to the right direction for this issue? Any comment or help is appreciated. 

Thank you in advance.

**Comment by hwilliamsdtx** [comment]
Check on Cloud services whether the software is running.
When I tried the D2v3, I think the bot media SDK gave errors that the machine must have at least 2 CPU cores.
Running the D2v2 worked.

**Comment by simonso1224** [comment]
Thanks a lot for your reply. That worked and got me to the next stage.

**Comment by hwilliamsdtx** [comment]
That's great.  I found these two related links afterwards that may help:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/146
https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/222

**Comment by angieleba** [comment]
@simonso1224 I am having the same error but in local environment with ngrok. Do you have any idea why that might be?
