### ISSUE TITLE
Captured audio: extremely jittery/stuttery and 'sped up'

### ISSUE THREAD

**Issue by andir78** [microsoftgraph/microsoft-graph-comms-samples#331]
**Describe the issue**
Captured audio is extremely jittery/stuttery, sounds 'sped up' as it's about a quarter of the expected duration.

**Code Snippet**
Within my callhandler i have the following....my 'plan' is to try and hive off the received buffer asap.........
```
private async void OnAudioMediaReceived(object sender, AudioMediaReceivedEventArgs e)
{
  try
  {
    if (e.Buffer.IsSilence) return;
    var managedArray = new byte[e.Buffer.Length];
    Marshal.Copy(e.Buffer.Data, managedArray, 0, (int)e.Buffer.Length);
    using (var fs = new FileStream($"c:\\tmp\\{statefulCall.Id}.raw",FileMode.Append))
    {
      fs.Write(managedArray, 0, managedArray.Length);
      fs.Close();
    }
  }
  catch (Exception exception)
  {
    Console.WriteLine(exception);
    throw;
  }
  finally
  {
    e.Buffer.Dispose();
  }
}
```

......then once the call has ended i process the .raw file created above into a .wav by basically generating a wav file header and appending the wav content from the raw file.

**Expected behavior**
A clear and audible recording of the call lasting the expected duration.

**Graph SDK (please complete the following information):**
 - Microsoft.Graph (Nuget) - v3.12.0
 - Microsoft.Graph.Core (Nuget) - v1.21.0
 - Microsoft.GraphCommunications.Calls (Nuget) - v1.2.0.1702
 - Microsoft.GraphCommunications.Calls.Media (Nuget) - v1.2.0.1702
 - Microsoft.GraphCommunications.Client (Nuget) - v1.2.0.1702
 - Microsoft.GraphCommunications.Common (Nuget) - v1.2.0.1702
 - Microsoft.GraphCommunications.Core (Nuget) - v1.2.0.1702
 
**Call ID**
66200300-5d1f-48ee-a66c-b0bcf170901b - LegId

[66200300-5d1f-48ee-a66c-b0bcf170901b.zip](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/5245132/66200300-5d1f-48ee-a66c-b0bcf170901b.zip)

Attached is a zip with the 'mangled' wav in....this was supposed to be 6.5minutes long

**Comment by andir78** [comment]
I forgot to mention that for a time I thought of the possibility of maybe the audio 'frames' were coming to me/being processed by me slightly out of sync/order....therefore i did try storing the frames in a dictionary where the key was the timestamp of the frame/buffer.....then i could order by the timestamp before attempting the conversion to the wav file.

Also after looking around [online ](https://www.colincrawley.com/audio-file-size-calculator/) at expected wav file sizes, i.e. 10MB/min, etc.. it appears that the amount of data i'm capturing currently is a lot lower than expected for the assumed values, i.e. mono (1 channel), PCM 16K, with 32K sample rate, etc.

final note... **every time** when debugging OnAudioMediaReceived(), the buffer only has 640 bytes, meaning i'm appending at a rate of 640 per time...is this the same for anyone else?

**Comment by AlexSapple** [comment]
Hi @andir78 - I'm not sure my advice will make any difference, but writing to the file stream within the OnAudioMediaReceived might create a bottle neck - given that the event is raised 50 times per second. I don't know if copying the buffer out somewhere and then a separate thread writing the file might help? The other thing is the check against the buffer.IsSilence. I could be wrong, but by continuing without writing the silence to the file, does that mean your audio will be out of sync by 20ms each time you skip over a silent buffer? 

I'm working on the audio feed for the first time myself and so I don't know if any of these points makes any difference for you - my trouble is how to actually playback the audio feed. What codec and format works? (because VLC doesn't want to play anything I've tried so far).

**Comment by 1fabi0** [comment]
Hi @AlexSapple how is your modality for the Local Media Session configured it seems like your file only accepts 44khz and receives 16khz audio data

**Comment by andir78** [comment]
Hi @AlexSapple, since posting this i have altered the logic in OnMediaReceived so that it no longer drops the isSilence frames, and pushes the buffers into a in memory queue. Then another thread dequeues items to append to an Azure Storage blob. Then once the call ends i can do the raw -> wav conversion. 

The problem i have is that the final recording has audio artefacts (glitches).  Have you had this problem and if so how did you solve it?

**Comment by andir78** [comment]
Hi @1fabi0 I have made my own `LocalMediaSessionFactory` that has a method returns me a `ILocalMediaSession` object with a audio socket set to PCM16K.

**Comment by AlexSapple** [comment]
Hi @andir78 to be honest, I was only guessing - if those steps haven't helped then I'm afraid I don't really have experience at this.

I've not actually got working playback and so I don't know if my feed has artefacts - can you let me know how you added the wav header (ffmpeg command??? or some other mechanism?) and I'll try myself.

**Comment by andir78** [comment]
I basically followed [this ](http://soundfile.sapp.org/doc/WaveFormat/) to write the header to a stream and then append the content of the captured data being sure to set subChunkSize2 t be the size of the captured data

**Comment by AlexSapple** [comment]
thanks @andir78 I'll see where i can get with that - just a thought, what values are you using in the header? 

I believe the values are expected to be (for PCM16k) - 16 bits per sample, rate of 16000, single channel/mono, little endian.

**Comment by 1fabi0** [comment]
@andir78 if your `ILocalMediaSession` is set to PCM16K the PCM is the format of the audio and 16K says 16 kHz if you changed the wave file writer to be for stereo 44khz PCM data you have to change your audio in your media session to PCM44K, or however it is called you can simply numerate threw the enum

**Comment by AlexSapple** [comment]
Hi @andir78 - I've added a header with FFMpeg and it worked nicely for my stream, clear and smooth without any artifacts; 

    ffmpeg -f s16le -ar 16k -ac 1 -i inputFile.pcm outputFile.wav

**Comment by andir78** [comment]
@AlexSapple Nice one :) are you running that command programmatically or by hand after the call?

**Comment by AlexSapple** [comment]
I ran that by hand just to test - but if you are writing in c#, you can use a wrapper around FFMpeg - something like https://github.com/tomaszzmuda/Xabe.FFmpeg - you need to have FFMpeg executables available and the library take care of the rest (or at least that's the idea). 

If you want the most fine grain control, you can skip the wrappers and spin up a process and point to the FFMpeg executable directly - using System.Diagnostics.Process.

**Comment by 1fabi0** [comment]
@andir78 @AlexSapple https://github.com/Microsoft/BotBuilder-RealTimeMediaCalling/issues/19#issuecomment-311433357 please use this technique to record audio in PCM16K

**Comment by andir78** [comment]
Closing as issue was resolved some time ago.  Root cause in my situation was a failure to handle the 50 (audio) frames per second in a timely manner.  This effectively resulted in missed frames similar to that of a low sample rate at the point of capture which i then (incorrectly) handled as 50 frames/sec.  Therefore leaving me with a shorter than expected recording that was very 'jittery'.
