### ISSUE TITLE
[PolicyRecordingBot] Recording bot Doesn't seem to be working anymore.  Was there any changes on this functionality or on teams server?

### ISSUE THREAD

**Issue by gerrosc** [microsoftgraph/microsoft-graph-comms-samples#337]
PolicyRecordingBot doesn't seem to be working anymore, though deployed app is report as running ok on the cloud.  Call always shows "Forwarding to voicemail" message then immediately Leaves the Call.

This was working fine from last week.  I haven't made significant changes on my code but its not working anymore after deployment to the cloud, even reverting those changes does nothing.  

I tried to deploy the original code from this repo [PolicyRecordingBot] with just those changes required on the settings, and its not working as well.  :-(

Are there any changes/updates made on this project that are not yet pushed to fix this?  Or maybe changes made on the server (Call/Media session) that we do know of broke the functionality of the project?

Please advice.

Thank you.

**Comment by simonso1224** [comment]
A moment ago, I deleted the bot channel registration and app registration and started fresh. Without changing the actual code, I just got it working for the first time. Previously, I couldn't even get packets into the webhook link https://mydomain.com/api/calling. Not exactly sure if it's that issue for you but that's what I had been going through.

**Comment by gerrosc** [comment]
hmm... checked that already and also followed the execution of powershell scripts for creation of application instance, creation and assignment of policy, but call still not connecting.

I'm on a new tenant now and on the previous tenant I was working on, it was working fine, following the steps/guide from the readme of the project.  Now on this new tenant, its not working.  I'm still finding out what I'm missing out and did wrong. :-(

**Comment by gerrosc** [comment]
ok found the issue.  the domain name was pointing on different server.
