### ISSUE TITLE
[PolicyRecordingBot] Frame rates of captured videos vary

### ISSUE THREAD

**Issue by mryderie** [microsoftgraph/microsoft-graph-comms-samples#338]
I'm capturing video with the PolicyRecordingBot and writing the raw data to files.

I've found that the video sizes (width & height) for each participant can vary over time, so I start writing a new file each time the size changes. I'm also seeing that the frame rate varies between participants and between calls. My guess is that it can be either 15 or 30 fps, based on what I've seen. Unfortunately, the frame rate isn't set when video data arrives:

![image](https://user-images.githubusercontent.com/1796058/94161786-f865a700-fe7d-11ea-8d5c-4fcc5fcdc897.png)

My intended strategy is to produce a single video for each participant. To do that, I'll use ffmpeg to combine all of their individual videos (of varying sizes), and the audio data.

Unfortunately, without knowing the frame rate, I don't see how this is possible. The duration of the videos may not match the duration of the audio, as the rate of playback for the videos may be incorrect.

An input file that was captured by the recorder is attached. You can see that the second hand on the clock ticks too quickly. It seems to have been captured at 15fps, but defaults to playing back at 30fps.

[input.zip](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/5277106/input.zip)

Based on suggestions in other threads I tried some parameters with ffmpeg to see if it would produce an output with the correct frame rate, but I didn't have any success.

Here are some commands I tried. They all produced an output that played at the same rate as the input (too fast).

```
ffmpeg -i input.h264 -vsync 2 output.mp4
ffmpeg -i input.h264 -framerate 15 output.mp4
ffmpeg -i input.h264 -vsync 2 -framerate 15 output.mp4
```
So, how do I process captured videos so that they play back at the correct rate?

**Comment by doucheface1** [comment]
same issue here we can never get audio and video to sync up

**Comment by mryderie** [comment]
The solution I came up with for this was to get the Timestamps of the first and last video buffers, and then subtract the first timestamp from the last timestamp. That gives clip duration in ticks. Each tick is 100ns, as per https://docs.microsoft.com/en-us/dotnet/api/system.datetime.ticks?view=netcore-3.1 Video buffers are delivered 50 times per second, so the calculated clip duration should be accurate to ~20ms.

Next step is to count the number of frames in the clip. You can do this with ffprobe, e.g.:
`ffprobe -v error -count_frames -show_entries stream=nb_read_frames input.h264`

Finally, divide the number of frames by the clip duration to get the frame-rate.


This approach give acceptable results. If anyone knows a better way, please chime in!

**Comment by sahilupadhye** [comment]
@mryderie can you pls reply how are you writing the input.h264 files ?

**Comment by MaslinuPoimal** [comment]
Same here, I do not believe that this solution is the correct one even though this was the end result I also came up with.

**Comment by mosoftwareenterprises** [comment]
@mryderie thanks for your input here. Did you come up with a better solution than above? I see the same problem, and come to the same conclusion as you did.

**Comment by mryderie** [comment]
@mosoftwareenterprises I never came up with a better solution, and the project was cancelled (for business reasons) shortly after I posted my last message. Good luck!

**Comment by Oreneo** [comment]
Has anything changed with this? I am experiencing the same issue

Is there a chance someone from MSFT will take a look at this?

**Comment by mosoftwareenterprises** [comment]
I am not aware of another way of doing it.
