### ISSUE TITLE
BOT receiving higher resolution that requested in Subscription

### ISSUE THREAD

**Issue by pavanjains** [microsoftgraph/microsoft-graph-comms-samples#341]
I am using LocalMedia sample and subscribing to VBSS for HD.720 but receiving 1080p is this a bug?

CallID: 611f2f00-0c20-4154-bc45-dc00427b3c14

**Comment by ssulzer** [comment]
@pavanjains 
That is by-design: vbss content will be delivered in its native resolution, to avoid downscaling.

**Comment by pavanjains** [comment]
@ssulzer Thanks
