### ISSUE TITLE
Question: is it possible to deploy Bot to Windows containers?

### ISSUE THREAD

**Issue by adoronin** [microsoftgraph/microsoft-graph-comms-samples#346]
As the documentation says, application-hosted media bot can be deployed only to: VMs, Cloud Service, or Service Fabric. 
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#application-hosted-media-bot-development-requires-cnet-and-windows-server

But what about Windows containers? Is it possible to deploy there?

**Comment by ssulzer** [comment]
@adoronin 
This is something we are just starting to test, running an application-hosted media bot within a Windows Container using Azure Kubernetes Service. It looks promising; hopefully we will publish an updated sample showing this.
The Windows Container must be running a full Windows Server operating system (not Server Core), and must have Server Media Foundation installed.
The underlying VM must have an instance-level public IP address (IL-PIP).
There must be unique TCP ports configured on the load balancer (e.g. via VMSS NAT port forwarding) which map to each specific VM/node instance.

**Comment by adoronin** [comment]
@ssulzer 
Thank you for the detailed answer! We'll try to implement that

**Comment by 4c74356b41** [comment]
@ssulzer any updates? from what I can tell its supposed to work in AKS, but I'm not sure how to do NAT port forwarding properly in AKS? I dont think its possible?

**Comment by ssulzer** [comment]
We are looking into this, to see if we can recommend something - it is certainly a challenge.

**Comment by dongkyunn** [comment]
In VMSS used in SF and AKS, you can create an inbound nat pool to do port mapping, but this assumes that only one pod is deployed in a VM. Also, I haven't found a way to do it during AKS deployment, so the following steps are one of workarounds after deployment to enable the port forwarding.

// Create inbound nat pool
az network lb inbound-nat-pool create --backend-port [backend_port_num] --frontend-port-range-start [starting_port_num] --frontend-port-range-end [ending_port_num] --lb-name [loadbalancer_name such as "kubernetes"] --name [name] --protocol Tcp --resource-group [resource_group_name] --frontend-ip-name [name at Azure portal -> resource_group -> lb -> Frontend IP configuration]

// Assign nat pool to VMSS
az vmss update -g [resource_group_name] --name [aks_pool_name] --set virtualMachineProfile.networkProfile.networkInterfaceConfigurations[0].ipConfigurations[0].loadBalancerInboundNatPools="[{​​\"id\": \"/subscriptions/[your_subscription_id]/resourceGroups/[resource_group_name]/providers/Microsoft.Network/loadBalancers/kubernetes/inboundNatPools/[inbound_nat_pool_name]\"}​​]"

// update vmss
az vmss update-instances --instance-ids "*" --no-wait -n [aks_pool_name] -g [resource_group_name]

**Comment by adoronin** [comment]
Thank you. We've seen the AKS sample and will discover that.

**Comment by 4c74356b41** [comment]
sorry, I'm not sure what you are talking about @adoronin

**Comment by adoronin** [comment]
@4c74356b41 
I'm talking about that sample:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/AksSamples/teams-recording-bot

**Comment by 4c74356b41** [comment]
mhm, i dont see any AKS specific configuration out there? like natting mentioned in the comment above (all the funky not supported az vmss stuff). do they use nginx ingress to publish it? I'm not sure whats going on there, sample is called `AksSampes`, but the readme talks about anything BUT AKS

**Comment by adoronin** [comment]
@4c74356b41 
They described AKS config here:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md

**Comment by bezua** [comment]
I’m working o migration from Cloud Services to VMSS, hopefully someone of you can have a tip for me.
In VMSS architecture it seems that proper NAT  inbound pool and port mapping is absolutely a key feature, since external machines shall be able to communicate to specific VM instance directly.
As @dongkyunn wrote before  it this thread, I faced the problem:
**“how to pass Public IP port to the VM instance, or retrieve it on the VM once it’s provisioned”**.
 VM instance itself doesn’t know too much about surrounding environment.
I think this could be workaround by a reverse proxy, but this complicates the architecture.
Another option would be going straight to AKS.
