### ISSUE TITLE
Key frame interval?

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-comms-samples#348]
**Describe the issue**
So I'm looking at a scenario where the call bot is consuming the video stream from a Teams call. Whilst this all works, I have a question about the key frames in relation to H264 type media. It's somewhere between "a curiosity" and "might be useful to understand" kind of question. 

The Api allows us to Request a key frame using;

    Call.GetLocalMediaSession().VideoSocket.RequestKeyFrame()

but that gets me wondering - is there a documented key frame interval? or should we expect this to be dynamic (such as key frames being sent as the underlying Teams/Skype libraries deem appropriate). One would assume that if I can specifically request a key frame, then the interval is not going to be static? 

If I do request a key frame - is there an expectation for how quickly I might expect that keyframe to be received - and I mean I'm not necessarily thinking about network latency etc - more long the lines of - "yes Teams/Skype will action that request as soon as possible and you should probably get the key frame pretty dam quickly :) "

thanks!

**Comment by AlexSapple** [comment]
Hi all, 

doesn't look like an answer will be forthcoming - but ok, maybe if I were to rephrase the question slightly - let's say I wanted to identify a key frame from the VideoMediaReceived event buffer - is this possible?

**Comment by ssulzer** [comment]
Hi @AlexSapple 
Key frames are not received on any kind of regular interval. The bot application should rarely need to request a key frame, unless it is decoding the incoming H.264 video stream in real-time and somehow encounters an error with decoding (e.g., the application happens to lose a keyframe before it gets to its decoder).
To tell if the received video buffer contains a key frame (IDR) you would need to lightly parse the first NALU of the video frame to check if its NAL unit type is 7 (SPS).

**Comment by AlexSapple** [comment]
thanks @ssulzer for the reply - I appreciate the info. Closing this now.
