### ISSUE TITLE
 Warning MSB3270 caused by Microsoft.Skype.Bots.Media reference 

### ISSUE THREAD

**Issue by andir78** [microsoftgraph/microsoft-graph-comms-samples#349]
**Describe the issue**
When building my solution based on the ComplainceRecordingBot i receive the warning:-

Warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.Skype.Bots.Media, Version=1.17.0.39, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Code Snippet**
N/A

**Expected behavior**
Warning to no exist

**Graph SDK (please complete the following information):**
-Where do i see/find the SDK version?

**Call ID**
N/A

**Logs**
See issue description

**Additional context**
N/A

**Comment by ssulzer** [comment]
The Microsoft.Skype.Bots.Media library is x64-only, so please try changing your project build target to x64.

**Comment by andir78** [comment]
Thank you....that sorted it
