### ISSUE TITLE
Calling and Online meeting examples

### ISSUE THREAD

**Issue by arun-msft** [microsoftgraph/microsoft-graph-comms-samples#35]
We are trying Calling and online meetings examples, In that examples we are trying Incident Bot and online meeting bot.
 
Incident Bot:
We are able to run, use the postman to send request incident/raise method as per documentation. It is working fine but we are not getting audio prompt.
 
Online Meeting Bot:
 
We are able to build the solution and provided all the values as per documentation but we are unable to find the meeting id value from teams meeting request. 

![image](https://user-images.githubusercontent.com/38062693/50878962-27fd2300-13ff-11e9-9904-9b8917bf3789.png)

Could you please let us know what should be value for meeting id?

**Comment by kanchm** [comment]
Please regenerate a new appSecret and not share that in the issues.

Refer to #11 for the meetingId question.

For the incident bot question, could you send us the details of the call id and timeframe?

**Comment by ksikorsk** [comment]
Closing as no response to question.
