### ISSUE TITLE
Can't lookup Call IDs in Microsoft Graph

### ISSUE THREAD

**Issue by codeBuilderUK** [microsoftgraph/microsoft-graph-comms-samples#351]
Hi

When recording a call using the Compliance Recording Bot sample, I write down the Call.ID from CallHandler but I cannot then look the details of that call back up.  I may have misunderstood what this Call ID is, but I am trying to pass it to 

https://graph.microsoft.com/v1.0/communications/callRecords/

And I always get an error back saying call record not found.

Could anyone advise?

Thanks,
Mike.

**Comment by hwilliamsdtx** [comment]
The Call ID you want to use is in the Call structure under ScenarioId, if I remember correctly.

**Comment by codeBuilderUK** [comment]
Thanks - I've tried grabbing the call ScenarioId and get the same issue when trying to pull it's call record: -

"Could not find the requested call record. Records about calls or online meetings that started more
than 30 days ago are not available.

**Comment by hwilliamsdtx** [comment]
I can't give much other help.

Some short recordings with silence don't get a call record - I think it's Teams connecting to the bot before the actual call takes place.  I also seem to remember a short delay before call records were available on Microsoft Graph.

The only other suggestion I have is to check your permissions - the app id/secret you use must have access to CallRecords.Read.All and also have been given access by a tenant admin.

**Comment by codeBuilderUK** [comment]
Thanks, appreciate the support.  Having looked at the callRecord documentation again it does actually say to use the callChainId which I'd missed but that hasn't made a difference either!  I'll double check permissions and keep digging.  Thanks 👍

**Comment by codeBuilderUK** [comment]
I've sorted it now - thanks for your help, it was indeed down to permissions and also the tenant name.  ScenarioId is the correct field to use as you suggested.
