### ISSUE TITLE
SILK Audio Not Available

### ISSUE THREAD

**Issue by philomathikus** [microsoftgraph/microsoft-graph-comms-samples#367]
**Describe the issue**
In the Graph Media SDK [documentation](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/index.html?q=silk), it states that "The bot has "raw" access to the voice, video and screen sharing media streams" and that it uses "codecs such as SILK and G.722 for audio and H.264 for video". However, the SupportedAudioFormat only allows to set Pcm16K orPcm44KStereo. Based on the fact that we can get "raw" encoded H264 video, why can we not get audio encoded in SILK? 

**Expected behavior**
Ability to specify SILK as an audioFormat

**Additional context**
This would save us having to re-encode it and therefore minimise latency.

**Comment by ssulzer** [comment]
@philomathikus 

The media SDK does not provide access to encoded audio; audio is always in "raw," decoded PCM format. Only video supports both raw (NV12, RGB) and encoded (H264) formats.

In the RTP media stream, audio can be encoded in one of several different codecs, and the codec can change dynamically.

**Comment by philomathikus** [comment]
@ssulzer Thanks for the reply! Would be great to get access to the encoded audio stream at some point (even if this means we would handle different codecs). 

I will close this issue
