### ISSUE TITLE
Azure Cloud Service (Classic) SITE URL not found

### ISSUE THREAD

**Issue by MurtazaMultanWala** [microsoftgraph/microsoft-graph-comms-samples#375]
Hello Community members. I am trying to build  the MS teams recording. For that I am following the policy based recording sample code and while going through the readme file, I found that for application based media bot, you required SSL certificate for your service DNS Name i.e. azure portal "SITE URL" of the services. This will then used in creating MediaPlateformSettings.  

The problem is I have created the azure web service (classic) but cannot found any site URL on the portal.
<img width="529" alt="sample" src="https://user-images.githubusercontent.com/49652147/100315375-89442600-2f86-11eb-8c9d-29f800045e2f.PNG">

is there any solution for this?

**Comment by BohdanM19** [comment]
Site URL will appear after deploy

**Comment by MurtazaMultanWala** [comment]
Thankyou @BohdanM19 for your response. Can you please guide me how to create the two files they require in deployment section. Actually I am creating this for first time, and I don't know hoe to do this.
<img width="390" alt="deployment" src="https://user-images.githubusercontent.com/49652147/100341131-282e4980-2faa-11eb-8d34-04a536c6cd5c.PNG">

**Comment by BohdanM19** [comment]
@MurtazaMultanWala https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-model-and-package

**Comment by MurtazaMultanWala** [comment]
@BohdanM19 One more thing, I am creating a console application and using HttpSelfHostConfiguration for listening the call events. Now setting up the media platform it requires the thumbprint. Can you please guide if there is a way to get SSL certificate and the domain name? because I was reading cloud service and we need to setup it in project as well. So I don't want to deploy my app on azure or link it with azure cloud services.
