### ISSUE TITLE
PolicyRecordingBot and Whiteboards

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#387]
We are currently able to record audio, video and screen shares. Is Whiteboard stream somehow also available? If yes, could you please let us know what changes are needed to record whiteboards shared during a teams meeting?

**Comment by ssulzer** [comment]
No, the whiteboard stream is not available to the bot.

**Comment by saraswat40** [comment]
Thanks
