### ISSUE TITLE
Dominant speaker timestamp

### ISSUE THREAD

**Issue by BetaLixT** [microsoftgraph/microsoft-graph-comms-samples#392]
**Describe the issue**
Currently there is no timestamp on Dominant speaker so I can accurately map the dominant speaker to a position in audio, is there any way to do this currently?

**Expected behavior**
A timestamp in the DominantSpeakerChangedEventArgs for the DominantSpeakerChanged event

**Comment by 1fabi0** [comment]
I guess it's okay that there is no timestamp because you're receiving the Events in realtime so you can just create a Timestamp yourself

**Comment by BetaLixT** [comment]
I need to map the event to the video/audio data that use server side timestamps, creating a timestamp myself wouldn't be the most accurate thing. Hence I'm wondering if we can get timestamps from teams for the dominant speaker event much like we do for video and audio packets.

**Comment by 1fabi0** [comment]
The difference between the real event and you receiving it will only be a few milliseconds (not recognizable) and it's also questionable if this event is triggered from Teams servers or if it's provided from the SDK by calculating who is speaking in the audio packets but that's something I don't know yet but I can imagine.

**Comment by 1fabi0** [comment]
Ok just got some Information from Microsoft about it actually creating the Timestamp yourself will be the most precision you can get for this event, it's triggered from the Microsoft side and send to the Bot without any time details.

**Comment by ssulzer** [comment]
Thanks @1fabi0.
@BetaLixT:
The DominantSpeakerChanged (DSC) events are triggered by feedback messages from the central conference media server which are delivered via the audio channel (along with the audio/voice content). The DSC events do not have timestamps but you can use the timestamp of the most recently received AudioMediaBuffer as a close approximation. Note, it can take up to 2 seconds for a new speaker to be identified as a Dominant Speaker (DS), so if you receive a DSC event introducing a new DS it's likely the incoming audio media already includes 1-2 seconds worth of content from that speaker. Each received AudioMediaBuffer contains the media source IDs of the Active Speakers contained within that audio frame. Thanks.

**Comment by BetaLixT** [comment]
Ok noted, Thanks @ssulzer @1fabi0
