### ISSUE TITLE
Frame rate or duration of video feed

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-comms-samples#394]
Hi everyone,

When parsing out video data in the onMediaReceived event, is there a way to determine either the duration of the received data or the intended frame rate? Properties exist on the object for frame rate, but they not set.  

One might suppose that the timestamps might suit this purpose - but the downside being that you have to wait until the next event before you can make the determination (l.e. the Timespan between the 2 timestamps). 

advice would be much appreciated. thanks very much.

**Comment by 1fabi0** [comment]
You should be able to use `VideoMediaReceivedEventArg.Buffer.VideoFormat.FrameRate`

**Comment by AlexSapple** [comment]
thanks @1fabi0 - but this property is always 0, hence the problem.

**Comment by 1fabi0** [comment]
Ok but then you still should get the quality you subscribed with the frame Rate youe subscribed and if it's not the FrameRate you subscribed the `MediaStreamQualityChanged` Event of the Video Socket with the new quality should be fired first

**Comment by AlexSapple** [comment]
thanks again @1fabi0 - I'll have a look at that event. I wasn't aware of that one, so thanks very much!  

- I'm not aware of being able to subscribe with a requested frame rate. I can subscribe with a preferred resolution, but does that imply a framerate?

**Comment by 1fabi0** [comment]
As far as I understand the implemantation of Microsoft for the Bot, yes the resolution imply the framerate, see the documentation for [Bandwidth](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.IVideoSocket.html#Microsoft_Skype_Bots_Media_IVideoSocket_SetReceiveBandwidthLimit_System_UInt32_) it implies this for me

**Comment by AlexSapple** [comment]
brilliant! - ok cool, I didn't know that - thanks very much @1fabi0 - I'm going to close this now since you given a solution.
