### ISSUE TITLE
Latency issue: Bot is taking over 20 sec to connect to MS Teams

### ISSUE THREAD

**Issue by manpreetjunejaee** [microsoftgraph/microsoft-graph-comms-samples#401]
Time taken by to get the call on MS Teams after triggering call from SDK is too high.

Using "Calls.AddAsync" function :

`var statefulCall = await this.Client.Calls().AddAsync(call, scenarioId: scenarioId, mediaSession: mediaSession).ConfigureAwait(false);`

How to debug more to find root cause for this issue ? Is there anything that can be done to improve performance in general?

**Comment by 1fabi0** [comment]
Did you already try on a Azure VM normal join Process takes about 5-10 seconds, but if you do this local it may be that your internet connection is too slow

**Comment by ssulzer** [comment]
@manpreetjunejaee 
Where is your bot deployed - what Azure region?
Can you please share a scenario-id (and approximately date/time in UTC) of a sample slow call setup? Thanks.

**Comment by manpreetjunejaee** [comment]
Turned out to be a code and load balancer rule issue.  Closing it.
