### ISSUE TITLE
Joining MeetingToken Fails with Code 9999

### ISSUE THREAD

**Issue by itisslizz** [microsoftgraph/microsoft-graph-comms-samples#413]
**Describe the issue**
We have a call to a bot that was Escalated by inviting a PSTN number. After we get the Established with the meeting Info token.
We try to join the call with a second bot. But the creation of the call with the meeting Info fails.

Can you help why this is?

**Code Snippet**
POST
```
{
    "callbackUri": "https://portal.dewe-01.luware.cloud/api/msTeamsDriver/v1/calling/fc1d71f5-3e6d-49b3-b19e-6c3a1a96bdd3",
    "source": {
        "identity": {
            "application": {
                "id": "fc1d71f5-3e6d-49b3-b19e-6c3a1a96bdd3",
                "@odata.type": "microsoft.graph.identity"
            },
            "@odata.type": "microsoft.graph.identitySet",
            "applicationInstance": {
                "id": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                "@odata.type": "microsoft.graph.identity"
            }
        },
        "@odata.type": "microsoft.graph.participantInfo"
    },
    "requestedModalities": [
        "audio"
    ],
    "meetingInfo": {
        "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik4xb25SeFM...",
        "@odata.type": "microsoft.graph.tokenMeetingInfo"
    },
    "tenantId": "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "@odata.type": "microsoft.graph.call"
}
```
The Response we got:

```
{
    "error": {
        "code": "9999",
        "message": "Unkown internal Server Error.",
        "innerError": {
            "date": "2021-02-11T09:42:35",
            "request-id": "373cdfed-c3ae-4341-a7f1-4201a584b89d",
            "client-request-id": "413958cd-cd3a-4491-a4a5-b5545762bb0b"
        }
    }
}
```

**Expected behavior**
We expect to receive a 200 response and that we are able to join the call with the second bot.

**Call ID**
CallChain Id: e0bc840b-7c76-4e92-80a2-a3c821a65404

**Additional context**

**Comment by 1fabi0** [comment]
Did you try to let the bot not join by token but by meeting information like thread, meeting id and organizer id

**Comment by itisslizz** [comment]
I do not have these for the call. The meeting is created by inviting a participant to a p2p call. At which I receive an established event with the meetingToken.

**Comment by 1fabi0** [comment]
Actually you can use your existing call `ICall.Resource.MeetingInfo` to get the correct information or are you already using this approach?

**Comment by itisslizz** [comment]
I forgot to specify the MediaConfig in my join request, that was the issue.
