### ISSUE TITLE
Peer to peer call is terminated automatically

### ISSUE THREAD

**Issue by muradhaider5786** [microsoftgraph/microsoft-graph-comms-samples#421]
**Issue**
I am trying to develop a simple bot that is supposed to answer incoming call made in personal chat with bot. The bot is employing application hosted media to play or get access to media streams. I am making use of classes and controllers that are implemented in Huebot project.The bot is registered on MS Azure and I am using `ngrok` for local testing and debugging. While debugging after making the call,  breakpoints are hit that are placed in 'CallsOnIncoming' or 'CallsOnUpdated' event handlers. So my bot configurations over Azure and in MS Teams seem to be correct. For setting up media platform, I have installed the wildcard SSL certificated issued by Let's Encrypt and CName records are created for corresponding tcp URLs exposed by ngrok. The environment is multi-tenant i.e. bot registration is done on another tenant, while bot is installed and tested in MS Teams on another tenant.   The problem is, when call is made to the bot, after 5 to 10 seconds call is terminated automatically. Please guide, what could be wrong.

**Code Snippet**
These are Media platform settings:
```
 MediaPlatformInstanceSettings = new MediaPlatformInstanceSettings()
                    {
                        CertificateThumbprint = "0B687..................",
                        InstanceInternalPort = 8445,
                        InstancePublicPort = 15410,
                        InstancePublicIPAddress = new IPAddress(0x0),
                        ServiceFqdn = "4.mycustomdomain.com",

                    },
```

**Expected behavior**
The Call status should turn to 'Established' and the call shouldn't end until user does this.

**Graph SDK**
 - Version 3.12 , 
 **Mcirsoft.Graph.Communications.Calls**
 -Version '1.2.0.1702'

**Call ID**
'f01f5500-691f-4512-abf6-965707ac7900' ,  DateTime (UTC) | 3/5/2021 2:22:12 PM

**Additional context**
Here's the snapshot for ngrok:
![image](https://user-images.githubusercontent.com/79193192/110129513-db98ac80-7de9-11eb-9227-efc58741e25b.png)

**Comment by muradhaider5786** [comment]
Included information about hosting and test environment.

**Comment by saadali** [comment]
Did you find any solution related to this problem. I have the same problem
