### ISSUE TITLE
Configure bot to enter specific meetings

### ISSUE THREAD

**Issue by gabrielionita** [microsoftgraph/microsoft-graph-comms-samples#425]
Is there any way for the end user to configure the teams-recording-bot to join specific meetings? 
More specifically, after the Office 365 admin grants permission for the bot, can the user install an app (app for Teams meetings, messaging extentions, etc) in Microsoft Teams and from which to configure what meetings the bot to join in? 
I can't find a way doing this because the Recording Policy can be used globally for all users or for specific users, but not for specific meetings of an user. 
Also, if I'm tring to join the bot via the POST method, the bot can't flip the recording status to Recording.

**Comment by chrisbardon** [comment]
Is there a reason you wouldn't use the recording APIs and choose not to record/join certain meetings?  Adding the policy to the user invites the bot when the call starts, but does not require that the bot joins.  You could ignore anything you're not interested in (e.g. all 1:1 calls, and meetings that aren't in a watchlist), and join the rest.  

It would be interesting to have a webhook that fired when a user created a meeting though-not sure if there's a way to get that outside of polling the calendar, and even then, that would miss non-calendar events.

**Comment by gabrielionita** [comment]
@chrisbardon, thanks a lot for the hint. I thought that the policy forces the bot to participate in the meeting, but I was wrong.

**Comment by gabrielionita** [comment]
I'm trying to reject the call via Call.RejectAsync(), but I still get this error in Teams:

> We coundn't connect you 
> There was a problem setting up the recording required by your org. Try joining again.

Should I answer the call and just ignore it?

**Comment by gabrielionita** [comment]
When creating the recording policy, [`New-CsTeamsComplianceRecordingApplication`](https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamscompliancerecordingapplication?view=skype-ps) has some flags that can be disabled so that the bot isn't required in all meetings. By running

```powershell
New-CsTeamsComplianceRecordingApplication `
-Parent $policyName -Id $identity."ObjectId" `
-RequiredBeforeCallEstablishment $false ` 
-RequiredDuringCall $false ` 
-RequiredBeforeMeetingJoin $false `
-RequiredDuringMeeting $false
```

I can now reject the calls for the bot and the actual calls can continue.
