### ISSUE TITLE
Support for Cloud Services extended support for Bot Media SDK/Microsoft.Skype.Bots.Media

### ISSUE THREAD

**Issue by lolochristen** [microsoftgraph/microsoft-graph-comms-samples#436]
**Describe the issue**
As the Bot Media SDK must run on a service with a range of open ports and on .NET Framework Cloud Services (classic) was so far a choice to run a bot. But Cloud Services Classic will retire and MSFT proposes to migrate to Cloud Services (extended support). Documentation says Certificates must be obtained by Azure KeyVault but Microsoft.Skype.Bots.Media directly accesses local Certificate Store. Please provide a solution for Bot Media SDK to fulfill the extended support requirements.

**Expected behavior**
Support for Azure KeyVault Certificates or possible to inject Certificate with Private Key manually.

**Graph SDK (please complete the following information):**
 - Microsoft.Skype.Bots.Media Version 1.19.0.25

**Comment by 1fabi0** [comment]
The sdk loads certificates from the Certificate store from the underlying windows machine if you for example use a service fabric with key vaults the service fabric automatically installs the Certificate into the Certificate store. So solution for the Certificate stuff would be installing the Certificates directly into the Cloud Service underlying Windows which should be a question for the Cloud Service side how to do this.
