### ISSUE TITLE
I deployed TeamsRecordingBot on AKS, but I can't attend the meeting

### ISSUE THREAD

**Issue by IsekiRiki** [microsoftgraph/microsoft-graph-comms-samples#441]
**Describe the issue**

I have deployed the bot to AKS by following the steps below.
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/deploy/aks.md#azure-kubernetes-services

Then I try to join the meeting using a test user (with policy applied), but I can't.
When I try to join, it looks like the image below.
![joinError](https://user-images.githubusercontent.com/75764025/113406215-104a5480-93e6-11eb-9bf9-4bd111e2d52b.png)

The pod log is below.

Setup: Starting VC_redist
Setup: Converting certificate
Setup: Installing certificate
Certificate "*****" added to store.

CertUtil: -importPFX command completed successfully.
Setup: Deleting bindings
Setup: Adding bindings
Setup: Done

RecordingBot: booting
RecordingBot: running
Skipped publishing IncomingHTTPPOST events to Event Grid topic recordingbotevents --No topic key specified
Scenario-Id: 0d7330c2-9cde-4a4d-9e2a-9ebf2f78940b
Connection: close

**Expected behavior**
Test users join the meeting

**Comment by 1fabi0** [comment]
Do you have applied the meeting policy correctly? can you please check that?

**Comment by IsekiRiki** [comment]
Thank you very much. solved.
The cause was that the following parameters were incorrect when creating the conference policy.
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/docs/setup/policy.md#create-an-application-instance

  -ApplicationId <BOT_ID>
 
After redeploying with the correct BOT_ID, you can now join the meeting.
