### ISSUE TITLE
Production ready infrastructure for video media bot

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-comms-samples#449]
Hi all, 

this question isn't relating to an issue - just looking for advice in terms of infrastructure for running a video media bot in a production environment (so something with high availability and able to support at least a few concurrent calls). I'm not an infrastructure person - and so my knowledge is very basic.

Currently, in my staging environment, I'm running the cheapest VM I can - as a cloud service (classic) - I've got it as an A2_v2 size. This works fine for a test environment and the media bot can _just_ hold a single call where subscribed to a single video socket. This setup does however run very hot - around 95% when a video feed is available.

So I've a couple of questions -  

1. for an environment that needs to support at least a degree of concurrent calls - let's say potentially 5 concurrent video calls, can anyone recommend a suitable VM size (working out cost is quite scary... :))
2. running the service with multiple instances - does this effectively mean multiple vm's? I appreciate that OS updates etc will knock a single instance offline and for reliable availability I'm going to need to run with multiple instances
3. Following on from 2, will instances just be taken offline for updates arbitrarily? I'm thinking about calls in progress getting killed?
4. Following on from 2 and 3, when running multiple instances, how do I ensure that load balancing will get notifications sent back to the correct instance (i.e. when a webhook notification lands - the notificationUrl) - how do I ensure that is routed to the instance that the call is on? 

really appreciate any advice! 
thanks.

**Comment by 1fabi0** [comment]
For the VM Size is the Dv3-series a good size and then you have to choose if you want to run it in azure service fabric or docker or kubernetes then each instance would run on a virtual machine or multiple intances would run on one virtual machine for your knockout problem checkout [this issue](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/336) or you would have to have your own backup and is alive checks (Don't know if kubernetes may can create there some backup system). For your last issue you can just have http and tcp ports for each instance on your load balancer that is always pointing to the same instance.

**Comment by AlexSapple** [comment]
thanks @1fabi0. That's helpful information.

**Comment by WezMorris** [comment]
@1fabi0 is it possible to run the sample on a single VM, outside the cloud service? If so, how?

**Comment by AlexSapple** [comment]
@WezMorris - not that I'm answering for @1fabi0 (nor that I am particularly skilled in this infra area) - but I intend to try and run a call bot as a service in a just a plain VM behind an application gateway. I'll get around to trying that at some point. I don't see why that wouldn't work. Not sure if that's actually any better than using the cloud service and worker role though...

**Comment by 1fabi0** [comment]
To note, I am not sure right now where it is persisted I would have to search now but, for prod it's, as far as I know, not allowed to host application hosted media bot's outside of azure.
