### ISSUE TITLE
Policy Recording Bot (Failed to initialize platform configuration (ECS timeout))

### ISSUE THREAD

**Issue by saadali** [microsoftgraph/microsoft-graph-comms-samples#450]
Following are the samples that we are using as a base,

https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot

I run this solution locally and it was working fine a week ago and suddenly it stops working and throws exception when i setting up a media settings. Following is the problem;

![image](https://user-images.githubusercontent.com/439127/118656009-659dc200-b7ea-11eb-9cf9-b55ce4294b37.png)

**Comment by AlexSapple** [comment]
Hi @saadali, 

have you seen this issue (closed last week) - if using emulation, you may need to enforce a certain TLS level

https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/446

**Comment by saadali** [comment]
I just saw it and it seems to be working now :)
