### ISSUE TITLE
Policy Recording Bot : Can't publish from VisualStudio

### ISSUE THREAD

**Issue by Gaku-Yamaguchi** [microsoftgraph/microsoft-graph-comms-samples#452]
I tried to deploy Policy Recording Bot to my subscription. I followed "Get Started" in README.md step by step as below. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/84550686/119068857-f3aebe00-ba1f-11eb-82d9-93c641b3848e.png)

but I failed publish from my Visual Studio. (step 4 in image above)
error message in Azure Portal  is below.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/84550686/119069037-4ee0b080-ba20-11eb-9594-dad8eed587d1.png)

I checked some documents and found this.
https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-troubleshoot-location-not-found-for-role-size

based on this document, changed value of "vmsize" attribute in "ServiceDefinition.csdef" to other available values in my location (japaneast) and published again over and over. but still failed deploying and always same message.
`<WorkerRole name="CRWorkerRole" vmsize="Standard_A2_v2">
    <Runtime executionContext="elevated" />
    <Startup>
      <Task commandLine="Startup.cmd &gt; Startup.cmd.log" executionContext="elevated" taskType="simple">
        <Environment>`
This is the list I tried for vmsize.
Standard_A2_v2, Standard_A4_v2, Standard_D3, Standard_D2, Standard_D2_v2, Standard_D3_v2, Standard_D2_v3, Standard_D4_v3     

my environment info is below.
Azure Cloud Service(classic) location : japaneast
VisualStudio Version : Visual Studio 2019 Version 16.8.3

How can I publish this project from visual studio on my azure? or if you have another way to publish, please share it.

**Comment by 1fabi0** [comment]
I think the response message is pretty clear that something that is required for the deployment(seems like creating the deployment slot) is currently not available in the area japaneast, you should try a different azure region

**Comment by Gaku-Yamaguchi** [comment]
Thanks for the comment. I will try a different azure region.
