### ISSUE TITLE
Question: Can PolicyRecordingBot be implemented in Java? 

### ISSUE THREAD

**Issue by jong64** [microsoftgraph/microsoft-graph-comms-samples#459]
This is a quick question, rather than reporting an issue.

Is it technically possible and supported to implement PolicyRecordingBot in Java? I know that Graph SDK for Java exists (https://github.com/microsoftgraph/msgraph-sdk-java-core), however, it is unclear to me if this SDK contains "everything" needed to fully implement PolicyRecordingBot without losing any of the functionality currently in the .NET version.

Thanks in advance for answer.

**Comment by jong64** [comment]
Another question (I searched existing issues and could not find pertaining information):

The sample bot contains various logging statements in various classes. However, when I fetch the log page via GET on "/logs" endpoint, it appears to only contain those logging statements pertaining to HTTP requests/responses. 

Does anyone know where I can find the rest of the logging? For instance, the OnRecordingStatusFlip function in CallHandler.cs contains a couple of log statements, which I do not see in the page returned from "/logs" endpoint, even though I'm pretty sure this function is called on my deployed bot, judging from the fact that my call is interrupted in a minute or so. 

Any tips would be appreciated.

**Comment by ssulzer** [comment]
@jong64 
I would not recommend it, unless you split the application into multiple processes. In order to receive real-time audio/video media from the Teams meeting, that part of the bot **must** use the Microsoft.Graph.Communications.Calls.Media & Microsoft.Skype.Bots.Media SDKs, which require .NET Framework / Windows.

**Comment by jong64** [comment]
@ssulzer 
Thanks.
