### ISSUE TITLE
Could not load file or assembly MediaPerf / Microsoft.Rtc.Internal.Media.DLL

### ISSUE THREAD

**Issue by rossbuggins** [microsoftgraph/microsoft-graph-comms-samples#46]
One step closer after [setting IIS Express to 64bit ](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/45). I'm now seeing:

Could not load file or assembly 'Microsoft.Rtc.Internal.Media.DLL' or one of its dependencies. The specified module could not be found.

If I set to break on all .net exceptions I'm actually seeing:

System.BadImageFormatException: 'Could not load file or assembly 'MediaPerf' or one of its dependencies. The module was expected to contain an assembly manifest.'

In bin there is the MediaPerf dll, .h and .ini

**Comment by rossbuggins** [comment]
I changed from using an old style MVC to new, but forced framework to be 4.7.2 instead of .net core.

**Comment by InDieTasten** [comment]
@rossbuggins  Can you elaborate on the change you've made to make it work? What were the individual steps you've taken to facilitate compatibility between IIS and MediaPerf. I'm not sure I know what you mean by "old style MVC to new". What's new, which dependencies did you reference?

**Comment by Lex45x** [comment]
@InDieTasten I guess "old-style MVC to new" means migration from default ASP.NET WebAPI 2 pipeline to OWIN.
I think so because I run in the same issue, and this migration helped me.
