### ISSUE TITLE
ICommunicationsClient ProcessNotificationAsync returns invalidRequest: Unexpected empty message

### ISSUE THREAD

**Issue by rossbuggins** [microsoftgraph/microsoft-graph-comms-samples#47]
When I call:

Client.ProcessNotificationAsync(requestMessage)
where Client is ICommunicationsClient I#m getting a response of:

microsoft.graph.communications.core.exceptions.error
invalidRequest: Unexpected empty message 

_"{\"@odata.type\":\"#microsoft.graph.communications.core.exceptions.serviceException\",\"error\":{\"@odata.type\":\"#microsoft.graph.communications.core.exceptions.error\",\"code\":\"invalidRequest\",\"message\":\"Unexpected empty message content\"},\"statusCode\":400,\"message\":\"Code: invalidRequest\\r\\nMessage: Unexpected empty message content\\r\\n\",\"data\":{},\"targetSite\":{\"Name\":\"ExtractNotifications\",\"AssemblyName\":\"Microsoft.Graph.Communications.Core, Version=1.0.0.1296, Culture=neutral, PublicKeyToken=31bf3856ad364e35\",\"ClassName\":\"Microsoft.Graph.Communications.Core.Notifications.NotificationProcessor\",\"Signature\":\"Microsoft.Graph.CommsNotifications ExtractNotifications(System.String, Newtonsoft.Json.JsonSerializerSettings)\",\"Signature2\":\"Microsoft.Graph.CommsNotifications ExtractNotifications(System.String, Newtonsoft.Json.JsonSerializerSettings)\",\"MemberType\":8,\"GenericArguments\":null},\"stackTrace\":\"   at Microsoft.Graph.Communications.Core.Notifications.NotificationProcessor.ExtractNotifications(String content, JsonSerializerSettings serializerSettings)\\r\\n   at Microsoft.Graph.CommunicationsClientExtensions.<ProcessNotificationAsync>d__1.MoveNext()\",\"source\":\"Microsoft.Graph.Communications.Core\",\"hResult\":-2146233088}"_

I though this call should in affect start the process of to fire the events that are registered:
this.Client = builder.Build();
this.Client.Calls().OnIncoming += this.CallsOnIncoming;
this.Client.Calls().OnUpdated += this.CallsOnUpdated;

I'm just trying to find a bit more clarity over whats going on around this stage, I've got the notification from teams that a call is comming in, to /callback/calling on my app, from here im calling Client.ProcessNotificationAsync, with a url of callback/notification set in the builder. At this stage i though it was going to call off to MS graph and respond back on callback/notification? which then fires the OnIncoming / OnUpdated on the client object?

Is the graph comms SDK open source? I couldn't find it anywhere, as I wan'ted to see exactly what goes on in ProcessNotificationAsync on implementations of ICommunicationsClient

Thanks

**Comment by ksikorsk** [comment]
Hello,

You are correct in thinking that this function call triggers the notifications, but it needs to be a request that is passed in by the service.  There is no need to have a separate controller for your initial callback then for the notifications, we deserialize and disambiguate all notifications the same way.  That being said, you can do so if you wish for your own purposes.

The flow is as follows:
```
Service ---- Incoming Call ---> client.ProcessNotificationAsync ---> client.Calls().OnIncoming
Service <---    Answer     ---- call.AnswerAsync()
Service ----    updates    ---> client.ProcessNotificationAsync ---> call.OnUpdated
```

The exception is telling me that the request that is received is empty, are you sure that you are passing in the correct request to the client?  If you can provide me with a http payload (headers and body) i can verify whether it is correct or not.  Please redact all private information (tokens, names, emails, phone numbers, etc...).

Cheers,
Kamil

**Comment by rossbuggins** [comment]
Hi Kamil,

Just found my issue, I had a parameter on the http post tagged for FromBody - this doesn't just copy the body data into it, it moves it there and stips it from the request object...

https://stackoverflow.com/questions/13226817/getting-raw-post-data-from-web-api-method


> _I needed something similar but for strings, and ensuring there was no parameter in the POST method ended up being essential to using the equivalent ReadAsStringAsync, it was empty otherwise. – Grant H. Jul 8 '14 at 23:40_
