### ISSUE TITLE
Plasn for compatibility with Microsoft.Graph version 4 ?

### ISSUE THREAD

**Issue by JiriZidek** [microsoftgraph/microsoft-graph-comms-samples#475]
Microsoft.Graph.Communications.Calls, Microsoft.Graph.Communications.Client, Microsoft.Graph.Communications.Common or Microsoft.Graph.Communications.Core explicitly state dependency on Microsft.Graph.Core LESS than 2.0 that implies that Microsoft.Graph version 4 cannot be used in same project since it requres at least Microsft.Graph.Core 2.0. 

Is there any plan to upgrade Microsoft.Graph.Communications.* to become compatible with recent Microsoft.Graph stack ? Or some kind of replacement ?

Using recent Microsoft.Graph 4 is motivated namely by newer authentication methods.

**Comment by 1fabi0** [comment]
There was an update for Microsoft.Graph.Communications.* that it now requires Microsoft.Graph.Core2.0.5+ and with it Microsoft Graph 4.0.5

**Comment by JiriZidek** [comment]
Works ! Thx.
