### ISSUE TITLE
IOnlineMeetingRequest CreateAsync fails with Code: BadRequest Code: BadRequest Message: Invalid request.

### ISSUE THREAD

**Issue by rossbuggins** [microsoftgraph/microsoft-graph-comms-samples#49]
I'm trying to use IOnlineMeetingRequest to create an online meeting. I'm building up the OnlineMeeting object and passing it to CreateAsync. However, its coming back with BadRequest Code: BadRequest Message: Invalid request.

```
var from = turnContext.Activity.From.AadObjectId;
var cBuilder = new  OnlineMeetingRequestBuilder("https://graph.microsoft.com/beta", bc);
IOnlineMeetingRequest r = cBuilder.Request();

var m = new OnlineMeeting();
m.MeetingType = MeetingType.MeetNow;
m.Participants = new MeetingParticipants();

var part1 = new MeetingParticipantInfo() {
    Identity = new IdentitySet() {
         User = new Identity() {
                Id = from } } };

m.Participants.Organizer = part1;
m.Subject = turnContext.Activity.Text;
var mr = await r.CreateAsync(m);
```

However, using fiddler I've taken the body and the auth headers and used them directly in postman, which creates the meeting without a problem.

The json in the body is as follows, I cant see anything wrong with it.

>{    "@odata.type": "#microsoft.graph.onlineMeeting",
>     "subject": "help me",
>     "participants": {
>         "@odata.type": "#microsoft.graph.meetingParticipants",
>         "organizer": {
>             "@odata.type": "#microsoft.graph.meetingParticipantInfo",
>             "identity": {
>                 "@odata.type": "#microsoft.graph.identitySet",
>                 "user": {
>                     "@odata.type": "#microsoft.graph.identity",
>                     "id": "[MY USER GUID]"
>                 }
>             }
>         }
>     },
>     "meetingType": "meetNow"
> }

The returned data when using this in postman is

 

>  "@odata.context": "https://graph.microsoft.com/beta/$metadata#app/onlineMeetings/$entity",

Just to note, I have also updated the template Auth providers to use:
`"https://login.microsoftonline.com/{tenant}";`
as the authority template instead of 
`"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token";`
so that it works with the ADAL v4 libraries.

**Comment by rossbuggins** [comment]
The OnlineMeetingRequestBuilder needs the full Online meeting url:

`  var cBuilder = new OnlineMeetingRequestBuilder("https://graph.microsoft.com/beta/app/onlineMeetings", bc);`

**Comment by ksikorsk** [comment]
We plan on updating all the samples to use ADAL in the upcoming weeks.  Thanks for the hint.

Your OnlineMeeting request is correct.  One suggestion is that you use the DefaultContainerClient to build the request, instead of building it yourself.  This would avoid future invalid URI problems, as the client constructs the right URIs.

```
var onlineMeeting = new Microsoft.Graph.OnlineMeeting()
{
    ...
};
var meetingRequest = statelessClient.App.OnlineMeetings.Request();
var meeting = await meetingRequest.AddAsync(onlineMeeting).ConfigureAwait(false);
```

**Comment by rossbuggins** [comment]
Brill thanks, I thought there must be a way to get it without entering the url
