### ISSUE TITLE
NumberOfMultiviewSockets cannot be set more than 9?

### ISSUE THREAD

**Issue by nikskhubani** [microsoftgraph/microsoft-graph-comms-samples#494]
**Describe the issue**
We are implementing a calling application hosted media bot on ASF and we are stuck with this strange limitation. When I try to increase the number beyond 9, it throws an error about Max sockets consumed. 

**Code Snippet**
        public const uint NumberOfMultiviewSockets = 9;

**Expected behaviour**
We should be able to set NumberOfMultiviewSockets to at least 100 as 100 participants are very common nowadays.

**Graph SDK (please complete the following information):**
 - Version 1.2.0.859

**Call ID**
Not necessary.

**Stack Trace**
Error Message: **Cannot have more than 10 video sockets**
Stack:    at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform.CreateMediaConfiguration(IAudioSocket audioSocket, IList`1 videoSockets, IVideoSocket vbssSocket, IDataSocket dataSocket)
   at Microsoft.Graph.Communications.Calls.Media.MediaSocketFactory.CreateMediaConfiguration(IAudioSocket audioSocket, IEnumerable`1 videoSockets, IVideoSocket vbssSocket, IDataSocket dataSocket)
   at Microsoft.Graph.Communications.Calls.Media.MediaSession.GetMediaConfiguration()
   at Microsoft.Graph.Communications.Calls.StatefulCallCollection.AddAsync(Call resource, IMediaSession mediaSession, Guid scenarioId, CancellationToken cancellationToken)
   at Microsoft.Graph.Communications.Calls.CallCollectionExtensions.AddAsync(ICallCollection callCollection, JoinMeetingParameters parameters, Guid scenarioId, CancellationToken cancellationToken)
   at XYZ.CallReceiver.Service.Bot.Bot.<JoinCallAsync>d__49.MoveNext() in 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at XYZ.CallReceiver.Service.Controllers.JoinCallController.<JoinCallAsync>d__0.MoveNext() in

**Additional context**
Not necessary.

**Comment by nikskhubani** [comment]
We have changed the logic for now to allocate video socket to only participants who come from OnDominantSpeakerChanged. Also we periodically clean up video sockets of those who didnt speak for 1 minutes...

**Comment by 1fabi0** [comment]
There is a internal limit for every teams client to 10 video sockets 9 video + 1 vbss, you can also view this limit in other clients, you could also join more Bot participants to the call which also have 9 video sockets available and concat all the calls in a logic, but your solution you came up with is the goto solution for this that is also implemented in some samples here.

**Comment by mosoftwareenterprises** [comment]
> We have changed the logic for now to allocate video socket to only participants who come from OnDominantSpeakerChanged. Also we periodically clean up video sockets of those who didnt speak for 1 minutes...

Hi @nikskhubani ,
You mention you clean up video sockets. Are you just calling Dispose on them?

What happens if they start speaking again, do you get the video back somehow?

Thanks

**Comment by 1fabi0** [comment]
To Clean up the video sockets you should dispose them, but I think what @nikskhubani ment with cleaning up the sockets was to unsubscribe them from a participants video, by calling the `Unsubscribe`-Method on the VideoSockets and subscribe to a new video feed when available, at least that's the common way to do this.

**Comment by nikskhubani** [comment]
Yes, as you see this line of code in **OnDominantSpeakerChanged**

`   if (e.CurrentDominantSpeaker != DominantSpeakerNone)
                {
                    IParticipant participant = this.GetParticipantFromMSI(e.CurrentDominantSpeaker);
                    var participantDetails = participant?.Resource?.Info?.Identity;

                    if (participantDetails != null)
                    {
                        // we want to force the video subscription on dominant speaker events
                        this.SubscribeToParticipantVideo(participant, forceSubscribe: true);
                        this.AILogger?.LogTrac($"Subscribed to dominent speaker", participantEmail: participant.Id);
                    }
                }`

If there is a new dominant speaker, the code will force the unsubscribe one of the speakers as shown here:

` if (updateMSICache) { this.currentVideoSubscriptions.TryInsert(msi, out uint? dequeuedMSIValue); }`

This will dequeue one of the subscriber and subscribe a new one.
