### ISSUE TITLE
Problem when running $Session=New-CsOnlineSession

### ISSUE THREAD

**Issue by lyuboSynergy** [microsoftgraph/microsoft-graph-comms-samples#496]
I'm trying to configure an Azure Call Recording Bot and I'm following https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot#create-a-recording-policy sample.

I've made it to the step "Create an Application Instance" but hit a wall when running "$Session=New-CsOnlineSession"

First command is:
Import-Module SkypeOnlineConnector

SkypeOnlineConnector is deprecated and it is advised to use Microsoft Teams instead.
https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector

So instead of "Import-Module SkypeOnlineConnector" I run "Import-Module MicrosoftTeams" which is executed successfully. My MicrosoftTeams version is:
![image](https://user-images.githubusercontent.com/37655949/136532942-92676f05-7c31-4a5a-868b-af332bed0d46.png)

When I run the second line "$Session=New-CsOnlineSession" I get the following error and cannot continue further:
New-CsOnlineSession: The 'New-CsOnlineSession' command was found in the module 'MicrosoftTeams', but themodule could not be loaded. For more information, run 'Import-Module MicrosoftTeams'.

**Comment by chrisbardon** [comment]
Yes, you need to run this in a Teams tenant.  It's a Teams powershell command (not Azure), so if there's no Teams data, it won't do anything.  If you need one, you should check out https://developer.microsoft.com/en-us/microsoft-365/dev-program.  You can get a free dev tenant with 25 E5 users that you can run any of these commands against.
