### ISSUE TITLE
There was a problem setting up the recording required by your org. Try joining again.

### ISSUE THREAD

**Issue by lyuboSynergy** [microsoftgraph/microsoft-graph-comms-samples#501]
**Describe the issue**
I've configured a teams recording bot and uploaded it to Azure. I've subscribed to Microsoft 365 Developer Program where I've got a Teams subscription with 25 users. I've granted one of them the TeamsComplianceRecordingPolicy. I'm trying to test the solution as I'm placing a call from a non-recorded user to a recorded user but Teams forwards the call to a voice mail and say "There was a problem setting up the recording required by your org. Try joining again.".

What I observe is that users with configured recorded policy cannot pickup the call and the above message appear. Users without the call recording policy can communicate freely.

I've configured the bot to send logs to AppInsights but nothing is logged there. Where I can find any logs?

**Comment by 1fabi0** [comment]
It seems like your bot is not running, or not working properly, so it can't join, also it seems like your policy is strict, so when no bot is available then your users under policy can not join. Also in the samples there is no App Insights configured, so you won't get logs in AppInsights, you should check where you can see std out

**Comment by angieleba** [comment]
@lyuboSynergy did you manage to solve this?

**Comment by lyuboSynergy** [comment]
@angieleba I've started bot configuration all over again and at the end I was able to place the call and also to pick it up. Unfortunately it was some time ago and currently I'm not working with teams anymore and it will be hard to help you out further.
