### ISSUE TITLE
Graph media TCP endpoint spec

### ISSUE THREAD

**Issue by rossbuggins** [microsoftgraph/microsoft-graph-comms-samples#51]
After getting local media working with the sdk, I want to understand more on what the sdk is doing to take the raw tcp stream in and converting to buffered events. As the sdk isn’t open source yet, is their a spec avalaible for the graph media tcp endpoint?

**Comment by ssulzer** [comment]
Here’s a brief overview of how the media platform (implemented in the Microsoft.Skype.Bots.Media nuget package) works. Please note that we currently have no plans to open-source the media platform, although other portions of the SDK may be open-sourced.

To enable a bot to participate in Skype/Teams voice/video calls, and to provide the bot with real-time “frame-by-frame” I/O access to the media streams, the media platform implements the necessary protocols, codecs, and APIs, to host a real-time media endpoint within the bot application’s process. Real-time media is encrypted, encoded using a codec like G.722 for audio and H.264 for video, and transported using the _RTP_ protocol, most often via UDP. Connectivity with the peer media endpoint is negotiated via the _ICE_ protocol. There is quite a lot of “machinery” in this media endpoint “stack,” hidden below a relatively simple, socket-like programming interface. 

To set up a voice/video call between the bot and a Skype/Teams peer (which may be a multiparty conferencing server, or MCU), our calling cloud needs to connect to the media platform in the bot’s process to tell it what to do: create voice and video RTP channels, bind the Audio/VideoSocket objects to the channels, allocate local UDP ports to send/receive RTP packets, and configure codecs, encryption parameters, and peer transport information. When the call ends, we need to tell the media platform to deallocate the RTP channel and endpoint resources.

To accomplish this, we establish a TLS/TCP-based control channel to the bot’s media platform. To connect to the platform on a specific machine or VM instance, we need to know the bot’s service FQDN and a public-facing port (InstancePublicPort) which uniquely identifies the machine instance (in case the bot service is a cluster of machines). The control channel is secured using TLS with mutual certificate authentication; the bot platform validates the client SSL certificate presented by the Skype/Teams calling cloud. This control channel does not carry actual voice/video media traffic, only commands to operate the bot’s media endpoint. Real-time media content is sent/received via separately allocated local UDP ports.

Note, the media endpoint (including RTP channels and UDP sockets) for a given bot call are affinitized (or pinned) to the specific machine instance on which the associated Audio/VideoSocket objects were allocated by the bot application. The media platform cannot move these resources to another machine instance (within the bot's service cluster) during the bot call.

As the bot’s caller (or peer) speaks, the bot receives RTP packets containing encrypted and encoded voice content. (For voice, the incoming rate is typically 50 RTP packets per second.) The packets are decrypted and decoded into buffers of “raw” 16-bit PCM samples which are delivered to the bot app. The media endpoint stack mitigates RTP packet loss, out-of-order delivery, jitter, and applies appropriate error concealment and “healing” to the received media stream to improve quality. A similar process handles video.

The media buffers are delivered to the bot app in the correct sequence order, one-at-a-time. The bot app will not receive the next buffer until its Audio/VideoMediaReceived event handler returns, so it is important for the bot to process incoming buffers in real-time (50 per second for audio; up to 30/second for video).

References for some of the protocols I mentioned:
RTP: https://en.wikipedia.org/wiki/Real-time_Transport_Protocol
ICE: https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment

Thanks,
Stephen

**Comment by rossbuggins** [comment]
So the bot media platform sort of turns the bot into a S4B client - that's all pretty similar? (My background is S4B). It's only now I've started looks at voice through teams, hence my flurry of questions over the last week - so thanks for the above, really useful to know @ssulzer  👍 

So with a standard teams call, how much of the above is happening on the clients, ICE etc? as desktop client isn't native, but all web based? So is their a concept of p2p calls in teams like their is in S4B? Thanks, Ross

**Comment by rossbuggins** [comment]
I’ll read this https://docs.microsoft.com/en-us/microsoftteams/microsoft-teams-online-call-flows :-)

________________________________

**Comment by ssulzer** [comment]
Call signaling and media session setup for a bot is similar to a Teams client. Bots can participate in 1:1 and group calls/meetings. The underlying call signaling protocols in Teams differ from those used in Skype for Business. Thanks.

**Comment by ksikorsk** [comment]
Closing this issue given that Stephen provided some details above.
