### ISSUE TITLE
Call transfer from group call fails with "Cannot do transfer for meeting mode"

### ISSUE THREAD

**Issue by bleul** [microsoftgraph/microsoft-graph-comms-samples#512]
**Describe the issue**
I tried to implement call transfer from a group call as described [here](https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=csharp%2Chttp#example-5-call-transfer-from-a-group-call).
When the transfer request is sent, graph responds with error 8523 "Cannot do transfer for meeting mode".

**Code Snippet**
Call creation:

            public Task<Call> createGroupCall()
            {
    
			    var call = new Call
			    {
				    CallbackUri = "https://<my-callback-url>/api/calling",
				    Targets = new List<InvitationParticipantInfo>()
				    {
					    new InvitationParticipantInfo
					    {
						    Identity = new IdentitySet
						    {
							    User = new Identity
							    {
								    DisplayName = "Megan Bowen",
								    Id = "b54e1c1a-c91e-40dd-ab38-9558a09dbec0"
							    }
						    }
					    },
					    new InvitationParticipantInfo
					    {
						    Identity = new IdentitySet
						    {
							    User = new Identity
							    {
								    DisplayName = "Johanna Lorenz",
								    Id = "e1cb1d7e-585c-49ae-975d-385a7e402f2d"
							    }
						    }
					    }
				    },
				    RequestedModalities = new List<Modality>()
				    {
					    Modality.Audio
				    },
				    MediaConfig = new ServiceHostedMediaConfig
				    {
				    },
				    TenantId = "62ffd0ba-9be7-4252-8a64-93eecb7f3e2d"
			    };
    
			    return _graphServiceClient.Communications.Calls
				    .Request()
				    .AddAsync(call);
		    }

Transfer request creation:		

		public async void transferCall(Call call)
		{
			var participants = await _graphServiceClient.Communications.Calls[call.Id].Participants
				.Request()
				.GetAsync();

			var transferTarget = new InvitationParticipantInfo
			{
				Identity = new IdentitySet
				{
					User = new Identity
					{
						DisplayName = "Adele Vance",
						Id = "b25dd44f-a301-4d58-b966-9640f9c71764",
					}
				},
				AdditionalData = new Dictionary<string, object>()
				{
					{"endpointType", "default"}
				}
			};

			Participant transfereeParticipant = participants.FirstOrDefault(c => c.Info.Identity.User?.Id == "e1cb1d7e-585c-49ae-975d-385a7e402f2d");

			var transferee = new ParticipantInfo
			{
				Identity = new IdentitySet
				{
					User = new Identity
					{
						Id = transfereeParticipant.Info.Identity.User.Id,
						AdditionalData = transfereeParticipant.Info.Identity.User.AdditionalData
					}
				},
				ParticipantId = transfereeParticipant.Id
			};

			await _graphServiceClient.Communications.Calls[call.Id]
				.Transfer(transferTarget, transferee)
				.Request()
				.PostAsync();
		}

Transfer Request:

```
POST /v1.0/communications/calls/e81f5e00-a90c-4890-bdb8-be8c76f4a535/microsoft.graph.transfer HTTP/1.1
{
   "transferTarget":{
      "identity":{
         "user":{
            "displayName":"Adele Vance",
            "id":"b25dd44f-a301-4d58-b966-9640f9c71764"
         }
      },
      "endpointType":"default"
   },
   "transferee":{
      "identity":{
         "user":{
            "id":"e1cb1d7e-585c-49ae-975d-385a7e402f2d",
            "tenantId":"62ffd0ba-9be7-4252-8a64-93eecb7f3e2d",
            "identityProvider":"AAD"
         }
      },
      "participantId":"460e8859-0685-42af-89c8-dbd8f05e5dfd"
   }
}
```

Error:
```
{
   "error":{
      "code":"8523",
      "message":"Cannot do transfer for meeting mode.",
      "innerError":{
         "date":"2021-12-09T17:18:54",
         "request-id":"2668cc61-51c9-47ab-86df-6c7268486c05",
         "client-request-id":"2668cc61-51c9-47ab-86df-6c7268486c05"
      }
   }
}
```

**Comment by rum-imagicle** [comment]
@bleul have you closed issue because you found a solution? Can you share an update?
Thanks!

**Comment by Janath** [comment]
@bleul / @rum-imagicle 

Have yous guys find a solution for this?

Thanks.
