### ISSUE TITLE
Exception when answering incoming call after update to latest packages

### ISSUE THREAD

**Issue by mmatt1967** [microsoftgraph/microsoft-graph-comms-samples#523]
Hi,

We've been working on a Teams Compliance Recording implementation based on the Policy Recording Bot sample for a while and have been able to successfully record calls. However, after updating the project with the latest release of the Microsoft.Graph.Communications packages, recording fails with this exception when the service tries to answer the incoming call:

> 	An exception occurred when invoking Created callback for resource: communications/calls.
> 	exception: Method not found: 'Microsoft.Graph.ICallAnswerRequestBuilder Microsoft.Graph.ICallRequestBuilder.Answer(System.String, Microsoft.Graph.MediaConfig, System.Collections.Generic.IEnumerable`1<Microsoft.Graph.Modality>, System.Nullable`1<Int32>)'.
> 	StackTrace:    at Microsoft.Graph.Communications.Calls.StatefulCall.<AnswerAsync>d__28.MoveNext()
> 	   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
> 	   at Microsoft.Graph.Communications.Calls.StatefulCall.AnswerAsync(MediaConfig mediaConfig, IEnumerable`1 acceptedModalities, String callbackUri, Guid scenarioId, CancellationToken cancellationToken, Int32 participantCapacity)
> 	   at Microsoft.Graph.Communications.Calls.CallExtensions.AnswerAsync(ICall call, IMediaSession mediaSession, String callbackUri, Guid scenarioId, CancellationToken cancellationToken, Int32 participantCapacity)
> 	   at com.dvsoft.TeamsRecordingService.FrontEnd.Bot.Bot.<CallsOnIncoming>b__30_0(ICall call)
> 

Can anyone explain what has broken here?

Thanks,
Mark

**Comment by saadali** [comment]
I also got the same issue

**Comment by 1fabi0** [comment]
I laready mentioned the problem in issue #521 currently the maximum supported version of the Microsoft.Graph Nuget package is 4.17.0. In higher versions the `ICallAnswerRequestBuilder` was changed

**Comment by mmatt1967** [comment]
Thanks @1fabi0 , that has solved my problem.
