### ISSUE TITLE
Graph application hosted media doesn't raise VideoMediaReceived in a docker container

### ISSUE THREAD

**Issue by yi-fan-song** [microsoftgraph/microsoft-graph-comms-samples#531]
**Describe the issue**
A clear and concise description of what the issue is.
Running the graph media sdk in a docker container makes it unable to receive video streams.

`VideoSocket.GetQualityOfExperienceData()` indicates that it is receiving ~50000 bitrate and 30 fps, but the final metrics reported by the sdk indicate no video received and `VideoSocket.VideoMediaReceived` is never raised.

Otherwise the sdk is working as expected, I am receiving audio, participants change, calls change, etc.

**Code Snippet**
Insert the code snippet if any.
I'd be happy to provide an example project if someone is willing to investigate. 

**Expected behavior**
The media processor receives video and raises the event `VideoSocket.VideoMediaReceived`

**Graph SDK (please complete the following information):**
 - Microsoft.Graph Version 4.22
 - Microsoft.Graph.Communications.* Version 1.2.0.4161
 - Microsoft.Skype.Bots.Media 1.23.0.49-alpha

**Call ID**
Provide the list call ids that encountered this issue. Include the time in UTC/GMT when these call have occurred.

**Logs**
If required, please add [logs](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html) from the SDK. (Please remove any PII from the logs before uploading)

**Additional context**
Docker version 20.10.9 on mcr

**Comment by mosoftwareenterprises** [comment]
What is your docker config? The video comes over a TCP socket, not HTTP, have you got that port accessible outside the container?

**Comment by yi-fan-song** [comment]
The image is based off `mcr.microsoft.com/dotnet/framework/runtime:4.8`. I am running it with the correct ports published afaik.
```
docker run -p 8000:8000 -p 8445:8445 -p 443:443 teamsbot:latest
```
I spent a couple of days troubleshooting networking. I don't believe that to be the issue.

And from #51, the video does not necessarily come over a tcp connection, it may be udp. The exposed tcp port is used as a control socket.

**Comment by yi-fan-song** [comment]
`mcr.microsoft.com/dotnet/framework/runtime:4.8` is not a good base image for the MediaProcessor, it is silently failing somewhere in the `VideoSocket`. Using `mcr.microsoft.com/windows` has fixed it.
