### ISSUE TITLE
Video event is not called after turning camera off and on in MSTeams

### ISSUE THREAD

**Issue by NetanelMosheCohen** [microsoftgraph/microsoft-graph-comms-samples#559]
The video event is not called after turning off camera in MSTeams.
I do receive video buffer in the event before turning off camera.

**Code Snippet**

`BotMediaStream` constructor has this code:
```
// Subscribe to the video media.
this.videoSockets = mediaSession.VideoSockets?.ToList();
            if (this.videoSockets?.Any() == true)
            {
                this.videoSockets.ForEach(videoSocket =>
                    {
                        videoSocket.VideoMediaReceived += this.OnVideoMediaReceived;                       
                    }
                );
            }  
```

After turning camera off and on again in MSTeams, the code doesn't reach this method:
```
private async void OnVideoMediaReceived(object sender, VideoMediaReceivedEventArgs e)
        {
            try
            {
                // write e.buffer to bin file
                await _mediaStream.AppendVideoBuffer(e.Buffer, this.participants);
                e.Buffer.Dispose();
            }
            catch (Exception ex)
            {
                this.GraphLogger.Error(ex);
                LogHelper.Logger.log(TraceLevel.Error, ex.ToString());
            }
            finally
            {
                e.Buffer.Dispose();
            }
        }
```

**Expected behavior**
OnVideoMediaReceived should be called when camera is on.

**Graph SDK version:**
1.2.0.850

**Comment by 1fabi0** [comment]
This is expected behaviour as you should only receive video when the participant is sending video.

**Comment by 1fabi0** [comment]
In the case of the restart you have to resubscribe with the video socket to the Participants video

**Comment by NetanelMosheCohen** [comment]
@1fabi0 Thanks. I tried it without success.
This code was added to the audio event:
![image](https://user-images.githubusercontent.com/56232437/175046189-69e5674d-2284-4da8-abd8-b9891470e185.png)

What I did, is to check if 15 seconds passed from the last video buffer that I got and if so, resubscribe to the video event. The condition works ok but after turning camera on, the code doesn't reach the method of the video event.

Did you mean to this approach? Do you see a problem here or you have a better way?

**Comment by 1fabi0** [comment]
What you check there is only the Event but on the socket there is a method called `Subscribe` that needs to be called with media source ID of the video of the participant

**Comment by NetanelMosheCohen** [comment]
It worked, thanks!
