### ISSUE TITLE
StreamWilerecording on audio recording

### ISSUE THREAD

**Issue by mwerghemmi** [microsoftgraph/microsoft-graph-comms-samples#56]
The scenario i want to acheve is the following: 
record a long conversation and transcript the voice to be able to implement a conversational bot. when i set streamwhilerecording to true, i got the ressource immediately once i start recording but the audio content is not streamed before the record ends. 
is it possible to invoke audio streaming few seconds (5 ) after the record starts ?

**Comment by ksikorsk** [comment]
Stream while recording will likely be removed in an upcoming update.  The format is very specific, and it has limited functionality.  For recording/transcoding full conversations take a look at our Local Media Samples which give you raw access to the audio stream.

**Comment by mwerghemmi** [comment]
thx @ksikorsk for the rplay, 
we will develop a local media bot for the transcription option.. 

will all the /record feature be removed or just the flag streamwhilerecording ? 
That was a very intersting one ! 
Mefteh.

**Comment by ksikorsk** [comment]
I believe it's just the streamWhileRecording flag, but @VinodRavichandran  can share more.

**Comment by VinodRavichandran** [comment]
@mwerghemmi Just the flag. /record is still a valid API.
