### ISSUE TITLE
Audio file doesn't play on playPrompt

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#58]
**Describe the issue**
I have a bot in a conference call. Here is the request I send:
2019-05-03 01:03:40.840050188 [PLAY_AUDIO]: POST to https://graph.microsoft.com/beta/app/calls/311a0400-0d44-4333-b509-ae8a4c330e54/playPrompt: 

```
{
  "clientContext": "6b157a75-4d68-d252-25e2-8b8819af72d5",
  "prompts": [
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
        "resourceId": "011f4ee4-c13f-5616-9a9a-fa8db6326712"
      },
      "loop": 3
    }
  ]
}

Here is the response I get:
{
	"@odata.type": "#microsoft.graph.commsNotifications",
	"value": [
		{
			"@odata.type": "#microsoft.graph.commsNotification",
			"changeType": "deleted",
			"resource": "/app/calls/311a0400-0d44-4333-b509-ae8a4c330e54/operations/2276ed78-9adc-46ce-9a2e-a79cf70c5cc2",
			"resourceData": {
				"@odata.type": "#microsoft.graph.playPromptOperation",
				"prompts": [
					{
						"@odata.type": "#microsoft.graph.mediaPrompt",
						"mediaInfo": {
							"@odata.type": "#microsoft.graph.mediaInfo",
							"uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
							"resourceId": "011f4ee4-c13f-5616-9a9a-fa8db6326712"
						},
						"loop": 3
					}
				],
				"completionReason": "unknown",
				"status": "completed",
				"createdDateTime": "2019-05-03T01:03:40.8860558+00:00",
				"lastActionDateTime": "2019-05-03T01:03:41.1694188+00:00",
				"clientContext": "6b157a75-4d68-d252-25e2-8b8819af72d5",
				"id": "2276ed78-9adc-46ce-9a2e-a79cf70c5cc2"
			}
		}
	]
}
```

But I don't hear the audio playing. Please let me know what I am missing.

**Comment by saraswat40** [comment]
Overnight the response has changed to this:
2019-05-03 20:00:56.894477963 [PLAY_AUDIO]: http response body: {
  "error": {
    "code": "UnknownError",
    "message": "{\"message\":\"No HTTP resource was found that matches the request URI 'https://a-pma-usea2-01.plat.skype.com:6703/newPlatform/v1/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants('playPrompt')'.\"}",
    "innerError": {
      "request-id": "4c88633c-1376-4092-ae36-938f7d5b17c7",
      "date": "2019-05-03T20:00:56"
    }
  }
}

I am assuming this has nothing to do with me?

**Comment by ksikorsk** [comment]
@saraswat40 can you remove the "loop" param and try sending the same prompt 3 times?
```json
{
  "clientContext": "6b157a75-4d68-d252-25e2-8b8819af72d5",
  "prompts": [
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
        "resourceId": "011f4ee4-c13f-5616-9a9a-fa8db6326712"
      }
    },
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
        "resourceId": "011f4ee4-c13f-5616-9a9a-fa8db6326712"
      }
    },
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
        "resourceId": "011f4ee4-c13f-5616-9a9a-fa8db6326712"
      }
    }
  ]
}
```

**Comment by ksikorsk** [comment]
You can also call the PlayAsync API 3 times, but wait until you get a response before playing again.  Latest SDK build exposed a `propmtQueued` callback which tells you when the previous prompt was queued.

**Comment by ksikorsk** [comment]
There are some known issues with `loop` and with multiple prompts being passed in.

**Comment by saraswat40** [comment]
Thanks for the quick response. I removed the loop completely and sent it once but it still doesn't work.
POST to https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants/playPrompt: {
  "clientContext": "49453d66-bad0-2bc8-4403-21e48e9296c3",
  "prompts": [
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "http://www.externalharddrive.com/waves/computer/hello.wav",
        "resourceId": "54b6f2b7-c13b-b70c-4f95-326ab2ac9744"
      }
    }
  ]
}
2019-05-03 22:01:21.494465681 [PLAY_AUDIO]: POST to https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants/playPrompt
BOTTENDER |INFO | 2019-05-03 22:01:21.567892479 [PLAY_AUDIO]: POST to https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants/playPrompt took 73 msec: https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants/playPrompt
BOTTENDER |INFO | 2019-05-03 22:01:21.568432168 [PLAY_AUDIO]: http response status code: 404
BOTTENDER |INFO | 2019-05-03 22:01:21.568441490 [PLAY_AUDIO]: http response body: {
  "error": {
    "code": "UnknownError",
    "message": "{\"message\":\"No HTTP resource was found that matches the request URI 'https://a-pma-usea2-01.plat.skype.com:6703/newPlatform/v1/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/participants('playPrompt')'.\"}",
    "innerError": {
      "request-id": "8f70a4a2-5e2e-4186-a0ce-3bed3ead3eff",
      "date": "2019-05-03T22:01:21"
    }
  }
}

**Comment by ksikorsk** [comment]
Your endpoint is not correct... are you using any of our SDKs?
`https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/**participants/**playPrompt`

It should be:
`https://graph.microsoft.com/beta/app/calls/2f1a0400-b6a7-48a9-9a04-1e48d4502fb8/playPrompt`

**Comment by saraswat40** [comment]
Hello, It works now. Many thanks for your help with this.
