### ISSUE TITLE
Any chance to support .netstandard 2.0 in Microsoft.Graph.Communications.Calls.Media (which allows only 4.7.2)

### ISSUE THREAD

**Issue by JiriZidek** [microsoftgraph/microsoft-graph-comms-samples#590]
Microsoft.Graph.Communications.Calls.Media cannot be used from .net6 app.

![image](https://user-images.githubusercontent.com/8578952/188978948-97b8acab-3810-4ce4-a035-940648910afb.png)

Provide version dependent on .netstadard2.0 or 2.1 (as is the case of other Microsoft.Graph.Communications.* libs)

MS.Graph 4.38.0

Context: our MS Teams app is run in AKS, only module using Media has to run on Windows machine....

**Comment by ssulzer** [comment]
@JiriZidek 
Work on adding .NET Core support in the Graph bot media SDK is in-progress. Currently only .NET Framework is supported.

Note, even once we have .NET Core support, the Graph bot media SDK will still require Windows Server to run.

**Comment by JiriZidek** [comment]
No problem with Windows. Problem is impossibility to reference .net6 shared modules and being stuck in C#7.1 syntax.
