### ISSUE TITLE
AKS Teams Recording Bot Sample deployment files does not work with latest Kubernetes > v1.22

### ISSUE THREAD

**Issue by LucidBijay** [microsoftgraph/microsoft-graph-comms-samples#594]
Hi, @1fabi0 @dongkyunn @ksikorsk @MaslinuPoimal and @lstappen , who I think have worked on similar types of issues. Any help would be appreciated.

Teams Recording Bot [sample ](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/AksSamples/teams-recording-bot) deployment process does not work with the latest AKS version > 1.22. 
I updated cert-manager.bat and ingress-nginx.bat to the following versions:
```
Cert-manager: version v1.8.0
AKS version: 1.23.8
IngressController version: 4.1.3
```

But it can not generate the certificate and set the ingress with the required externalIP. Note, that other files in [teams-recording-bot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot) folder under the deployment section are unchanged. Only updated: removed **beta** prefix

I tried to explicitly specify the loadbalacerIP in ingress-ngix.bat as

```
helm install nginx-ingress ingress-nginx/ingress-nginx ^
    --create-namespace ^
    --namespace ingress-nginx ^
    --version 4.1.3 ^
    --set controller.replicaCount=1 ^
    --set controller.ingressClassResource.default=true ^
    --set controller.nodeSelector."kubernetes\.io/os"=linux ^
    --set controller.service.loadBalancerIP=20.12.198.45 ^
    --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-dns-label-name"=aks-recording-prod
    --set controller.service.enabled=false ^
    --set controller.admissionWebhooks.enabled=false ^
    --set controller.config.log-format-stream="" ^
    --set controller.extraArgs.tcp-services-configmap=ingress-nginx/teams-recording-bot-tcp-services
```

And after this, it generates a certificate and the ingress also points to externalIP but when I hit post request using JoinURL, it gives **200 OK but Bot does not join.**

I am getting this error (Server Internal Error. DiagCode: 500#7112) once I deploy it to Azure Kubernetes and see logs on the CallOnUpdate section. I doubt it might be due to TCP mappings OR certificates. I am not sure how to see the additional logs once deployed to AKS.

**I doubt TCP mapping because: I cannot telnet to prod.bot.virtuosis.net 28550**

**I don't know how to fix it.**

![image](https://user-images.githubusercontent.com/75725080/190873836-5aa81257-28e1-4f92-937d-1491608bac72.png)

Here are details of pods and certificates deployed to AKS:
**1. kubectl get pods -n teams-recording-bot**
![image](https://user-images.githubusercontent.com/75725080/190869723-25ca5e2f-2ca5-473f-8a3b-01794ad760a5.png)

**2. Some logs:**
![image](https://user-images.githubusercontent.com/75725080/190870028-08b4ac00-efd2-46ea-92be-2a1f4fca5dce.png)

**3. kubectl describe certificate -n teams-recording-bot**

> Name:         ingress-tls
Namespace:    teams-recording-bot
Labels:       app.kubernetes.io/managed-by=Helm
              helmAppVersion=1.0.3
              helmName=teams-recording-bot
              helmVersion=1.0.0
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2022-09-16T16:17:14Z
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
          .:
          k:{"type":"Ready"}:
            .:
            f:lastTransitionTime:
            f:message:
            f:observedGeneration:
            f:reason:
            f:status:
            f:type:
        f:notAfter:
        f:notBefore:
        f:renewalTime:
    Manager:      cert-manager-certificates-readiness
    Operation:    Update
    Subresource:  status
    Time:         2022-09-16T16:17:14Z
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
          f:helmAppVersion:
          f:helmName:
          f:helmVersion:
        f:ownerReferences:
          .:
          k:{"uid":"a26a4d7e-3228-48da-ba07-79974549e1f6"}:
      f:spec:
        .:
        f:dnsNames:
        f:issuerRef:
          .:
          f:group:
          f:kind:
          f:name:
        f:secretName:
        f:usages:
    Manager:    cert-manager-ingress-shim
    Operation:  Update
    Time:       2022-09-16T16:17:14Z
  Owner References:
    API Version:           networking.k8s.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  teams-recording-bot
    UID:                   a26a4d7e-3228-48da-ba07-79974549e1f6
  Resource Version:        657054
  UID:                     318b47fc-5ae0-41cd-9370-b085095a21df
Spec:
  Dns Names:
    prod.bot.virtuosis.net
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt
  Secret Name:  ingress-tls
  Usages:
    digital signature
    key encipherment
Status:
  Conditions:
    Last Transition Time:  2022-09-16T16:17:14Z
    Message:               Certificate is up to date and has not expired
    Observed Generation:   1
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2022-12-14T19:24:49Z
  Not Before:              2022-09-15T19:24:50Z
  Renewal Time:            2022-11-14T19:24:49Z
Events:                    <none>

**4. kubectl describe pod teams-recording-bot-0 -n teams-recording-bot**

> Name:             teams-recording-bot-0
Namespace:        teams-recording-bot
Priority:         0
Service Account:  default
Node:             aksscale000005/10.240.0.113
Start Time:       Sat, 17 Sep 2022 22:49:39 +0545
Labels:           app=teams-recording-bot
                  controller-revision-hash=teams-recording-bot-76f8574954
                  statefulset.kubernetes.io/pod-name=teams-recording-bot-0
Annotations:      <none>
Status:           Running
IP:               10.240.0.134
IPs:
  IP:           10.240.0.134
Controlled By:  StatefulSet/teams-recording-bot
Containers:
  recording-bot:
    Container ID:   containerd://d20d72c11f6ae9dda4fcf0f67f430ecc8c0905fa2ae42e42ff017da85f2b9a7e
    Image:          acrmeetingrecordingbot.azurecr.io/teams-recording-bot:1.0.3
    Image ID:       acrmeetingrecordingbot.azurecr.io/teams-recording-bot@sha256:f5dda1002fdaf4277f0b015158549ba7704e7f824e7bf6f66eb61b695cbc389f
    Ports:          9441/TCP, 8445/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 17 Sep 2022 22:59:20 +0545
    Ready:          True
    Restart Count:  0
    Environment:
      AzureSettings__BotName:                              <set to the key 'botName' in secret 'bot-application-secrets'>            Optional: false
      AzureSettings__AadAppId:                             <set to the key 'applicationId' in secret 'bot-application-secrets'>      Optional: false
      AzureSettings__AadAppSecret:                         <set to the key 'applicationSecret' in secret 'bot-application-secrets'>  Optional: false
      AzureSettings__ServiceDnsName:                       prod.bot.virtuosis.net
      AzureSettings__InstancePublicPort:                   28550
      AzureSettings__InstanceInternalPort:                 8445
      AzureSettings__CallSignalingPort:                    9441
      AzureSettings__PlaceCallEndpointUrl:                 https://graph.microsoft.com/v1.0
      AzureSettings__CaptureEvents:                        false
      AzureSettings__EventsFolder:                         events
      AzureSettings__MediaFolder:                          archive
      AzureSettings__TopicKey:
      AzureSettings__TopicName:                            recordingbotevents
      AzureSettings__RegionName:
      AzureSettings__IsStereo:                             false
      AzureSettings__WAVSampleRate:                        0
      AzureSettings__WAVQuality:                           100
      AzureSettings__AzureStorageAccountConnectionString:  DefaultEndpointsProtocol=https;AccountName=meetingrecordingbot;AccountKey=XuqtdV4wggeuT3BhvO8iyPSCsjNpAN6pzyOXrhUCqnJpAnU7N66WOI0W1Xh6kJ5ZI9bSKiHw76bh+AStpOre4Q==;EndpointSuffix=core.windows.net
      AzureSettings__AzureStorageAccountContainerName:     audiofiles
      AzureSettings__PodName:                              teams-recording-bot-0 (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-sfhs9 (ro)
      C:/certs/ from certificate (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-tls
    Optional:    false
  kube-api-access-sfhs9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              agentpool=scale
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:  <none>

**5. Same type of logs for teams-recording-bot-1 and teams-recording-bot-2**

_Originally posted by @LucidBijay in https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/532#issuecomment-1250115777_

**Comment by LucidBijay** [comment]
hi, @ssulzer Do you have any idea about it? Deployment scripts are not working fine with Kubernetes greater than 1.19. I am talking about the MS Graph samples of Teams recording bot mentioned above.

**Comment by 1fabi0** [comment]
The sample was not created with new aks versions and not updated since it was created, to make it run on newer versions of AKS you need to update some things in the Helm deployment, like update you're ingress and cert manager to the latest versions

**Comment by LucidBijay** [comment]
@1fabi0 
I understand that. So I updated the following files to updated version:
cert-manager.bat

> @echo off
> 
> echo Creating cert-manager namespace
> kubectl create ns cert-manager
> 
> echo Updating helm repo
> helm repo add jetstack https://charts.jetstack.io
> helm repo update
> 
> echo Installing cert-manager
> helm install ^
>   cert-manager jetstack/cert-manager ^
>   --namespace cert-manager ^
>   --version v1.9.1 ^
>   --set nodeSelector."kubernetes\.io/os"=linux ^
>   --set webhook.nodeSelector."kubernetes\.io/os"=linux ^
>   --set cainjector.nodeSelector."kubernetes\.io/os"=linux ^
>   --set startupapicheck.nodeSelector."kubernetes\.io/os"=linux ^
>   --set installCRDs=true
> 
> echo Waiting for cert-manager to be ready
> kubectl wait pod -n cert-manager --for condition=ready --timeout=60s --all
> 
> echo Installing cluster issuer
> kubectl apply -f cluster-issuer.yaml


cluster-issuer.yaml

> apiVersion: cert-manager.io/v1
> kind: ClusterIssuer
> metadata:
>   name: letsencrypt
> spec:
>   acme:
>     server: https://acme-v02.api.letsencrypt.org/directory
>     email: xyz@abc.onmicrosoft.com
>     privateKeySecretRef:
>       name: letsencrypt
>     solvers:
>     - http01:
>         ingress:
>           class: nginx
>           podTemplate:
>             spec:
>               nodeSelector:
>                 "kubernetes.io/os": linux



ingress-nginx.bat

> @echo off
> 
> echo Creating ingress-nginx namespace
> kubectl create namespace ingress-nginx
> 
> echo Adding helm repositories
> helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
> helm repo add stable https://charts.helm.sh/stable
> helm repo update
> 
> echo Installing ingress-nginx
> helm install nginx-ingress ingress-nginx/ingress-nginx ^
>     --create-namespace ^
>     --namespace ingress-nginx ^
>     --version 4.3.0 ^
>     --set controller.replicaCount=1 ^
>     --set controller.nodeSelector."kubernetes\.io/os"=linux ^
>     --set controller.service.enabled=false ^
>     --set controller.admissionWebhooks.enabled=false ^
>     --set controller.config.log-format-stream="" ^
>     --set controller.extraArgs.tcp-services-configmap=ingress-nginx/teams-recording-bot-tcp-services



Output:
Ingress is created with no Address:
![image](https://user-images.githubusercontent.com/75725080/194723010-d4b667b0-7c63-404a-9f12-791af8bf6911.png)


Ingress controller is fine:
![image](https://user-images.githubusercontent.com/75725080/194723030-31119db9-b67f-413f-b9fc-15a449b9a577.png)

Cert is fine:
![image](https://user-images.githubusercontent.com/75725080/194723057-3d13edce-2d9d-44dd-a3b8-426ec0ab1a00.png)

Pods are running fine:
![image](https://user-images.githubusercontent.com/75725080/194723075-ad4ac82a-55b3-4754-97b0-1236561fc12f.png)



**But still I can not post the baseUrl/joincall POST request with join URL.**
![image](https://user-images.githubusercontent.com/75725080/194723124-fe3f002b-d087-40f6-9d2a-2389931b47e5.png)


Any suggestion what I am missing here?

**Comment by 1fabi0** [comment]
I think you also have to update the ingress.yaml because the newer version of ingress nginx that supports the new cert manager does not support the old beta template of the ingress yaml... I think you have to use v1 now of the ingress networking template

**Comment by LucidBijay** [comment]
Hi @1fabi0 thank you for replying back. I updated that already to v1 as shown in the screenshot. Removed all beta references from all the files where I found them, for your information.
![image](https://user-images.githubusercontent.com/75725080/194723563-e3b36c16-821b-4a03-b1ae-ab0659189e1e.png)

**Comment by 1fabi0** [comment]
You're ingress is wrong paths should contain a path that is then further specified see [this](https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/) take a close look at the paths part

**Comment by LucidBijay** [comment]
@1fabi0  I see only the order is different. Are you pointing me to update the order as this:
![image](https://user-images.githubusercontent.com/75725080/194724470-436e99dd-5b91-4b8f-8592-93f3f3e0ecb8.png)

**Comment by 1fabi0** [comment]
@LucidBijay can you check if you have any certificate requests pending or any certificates in your cluster?

**Comment by LucidBijay** [comment]
Hi @1fabi0 not sure, but just reversed the order of path and backend under paths part in ingress.yaml, with the latest versions, as discussed above, it worked fine. Thank you for your suggestions and feedback. I am going to close this ticket.
