### ISSUE TITLE
Unable to get end of calls

### ISSUE THREAD

**Issue by CaleoSystems** [microsoftgraph/microsoft-graph-comms-samples#596]
Hi,

Im testing teams-recording-bot locally. When I generate a call between two users I can see how the recording starts and in Ngrok I can see the api/call messages. My problem is that when the call ends I do not receive any other message indicating a participant has left and the recording never ends until the console program is terminated but generating a corrupted wav files.

In a per2per call I receive 2 messages like this, only changing the userID:

{
    "@odata.type": "#microsoft.graph.commsNotifications",
    "value": [
        {
            "@odata.type": "#microsoft.graph.commsNotification",
            "changeType": "created",
            "resource": "/app/calls/761f6500-38b1-4b2c-aa99-5474e8554517",
            "resourceUrl": "/communications/calls/761f6500-38b1-4b2c-aa99-5474e8554517",
            "resourceData": {
                "@odata.type": "#microsoft.graph.call",
                "state": "incoming",
                "direction": "incoming",
                "callbackUri": "https://intellirec.caleo.dev/api/calls",
                "source": {
                    "@odata.type": "#microsoft.graph.participantInfo",
                    "id": "d0f60e51-7c49-44c8-a504-522c88377cc6",
                    "identity": {
                        "@odata.type": "#microsoft.graph.identitySet",
                        "user": {
                            "@odata.type": "#microsoft.graph.identity",
                            "id": "9b95267e-a60e-4c4e-a101-918e6fe32dfc",
                            "tenantId": "b56d479e-1032-4222-888d-83b273be0410",
                            "identityProvider": "AAD"
                        }
                    },
                    "endpointType": "skypeForBusinessVoipPhone",
                    "region": "amer"
                },
                "targets": [
                    {
                        "@odata.type": "#microsoft.graph.invitationParticipantInfo",
                        "identity": {
                            "@odata.type": "#microsoft.graph.identitySet",
                            "applicationInstance": {
                                "@odata.type": "#microsoft.graph.identity",
                                "id": "67970000-381d-4637-8b09-02dc30e2c1a3",
                                "tenantId": "b56d479e-1032-4222-888d-83b273be0410",
                                "identityProvider": "AAD"
                            }
                        },
                        "endpointType": "default",
                        "id": "dad5500d-d452-4e87-9bc2-bd2f7c89d183",
                        "region": null,
                        "languageId": null
                    }
                ],
                "meetingInfo": {
                    "@odata.type": "#microsoft.graph.tokenMeetingInfo",
                    "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6InBid0FFbGduc25NSGc4aWhucElISHlKdmI5USIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCIsIng1dCI6InBid0FFb........"
                },
                "tenantId": "b56d479e-1032-4222-888d-......",
                "myParticipantId": "dad5500d-d452-4e87-9bc2-bd2f7c89d183",
                "callChainId": "f18eed14-2069-47f0-ab02-6d9c911cb60c",
                "incomingContext": {
                    "@odata.type": "#microsoft.graph.incomingContext",
                    "sourceParticipantId": "d0f60e51-7c49-44c8-a504-522c88377cc6",
                    "observedParticipantId": "d0f60e51-7c49-44c8-a504-522c88377cc6"
                },
                "mediaHostedRegion": "USSC",
                "id": "761f6500-38b1-4b2c-aa99-5474e8554517",
                "applicationMetadata": {
                    "botData": {
                        "callId": "f18eed14-2069-47f0-ab02-6d9c911cb60c",
                        "mediaHostedRegion": "USSC",
                        "user": {
                            "participationMethod": "Callee"
                        },
                        "otherSideUser": {
                            "id": "8:orgid:2aabd250-de2b-4d88-855b-ba4f996915ab",
                            "participantId": "b9bae202-c3ef-4fad-9dc9-9e3037d43127",
                            "tenantId": "b56d479e-1032-4222-888d-83b273be0410",
                            "participationMethod": "Caller",
                            "clientLocation": "MX"
                        },
                        "inviteReasons": [
                            "ComplianceRecording"
                        ],
                        "policyIdentifier": "TeamsComplianceRecordingPolicy=Tenant:IntellirecBotRecordingPolicy",
                        "otherRecorders": [],
                        "pairedRecorders": [],
                        "isMultiParty": true
                    }
                }
            }
        }
    ]
}

Is there a way to know when the call ends on when a participant left a call?

Best regards.

**Comment by angieleba** [comment]
@CaleoSystems  CallOnUpdated(ICall sender, ResourceEventArgs<Call> e) in the CallHandler class should do it. Check if (e.OldResource.State == CallState.Established && e.NewResource.State == CallState.Terminated)

**Comment by CaleoSystems** [comment]
Hi Angie,

Thank you very much for your time to take a look to my issue. 
The "problem" was a misconfiguration issue, I just added a new Key to my env file and referenced it in my AzureSettings.cs file.

AzureSettings__ServiceDnsName=intellirec.caleo.dev
AzureSettings__ServiceCname=bot.caleo.dev       (The new key)

The Incomig Call notification was received by intellirec.caleo.dev/api/calls  but the other ones was redirected to bot.caleo.dev/api/calls/notifications, I changed it like this in AzureSettings.cs:
this.CallControlBaseUrl = new Uri($"https://{this.ServiceDnsName}/{HttpRouteConstants.CallSignalingRoutePrefix}/{HttpRouteConstants.OnNotificationRequestRoute}");

Before was: 
this.CallControlBaseUrl = new Uri($"https://{this.ServiceCname}/{podNumber}/{HttpRouteConstants.CallSignalingRoutePrefix}/{HttpRouteConstants.OnNotificationRequestRoute}");
