### ISSUE TITLE
An error  "Audio is unsupported" occurs when we let TeamsBot join Teams meeting.

### ISSUE THREAD

**Issue by Tetsu-Yokota** [microsoftgraph/microsoft-graph-comms-samples#602]
We have the following problem in using TeamsBot. Please let us know how to resolve it.

**Describe the issue**
When we used the EchoBot sample, I got an error message "Audio is unsupported".
 　Please let us know how to resolve this issue.
　The following procedure will cause this error:
　　1. Start the service by "EchoBot.sh".
　　2. Launch a Teams meeting.
　　3. Let the bot join Teams meeting by a join request.
　　4. The above error appears in the Visual Studio (EchoBot.sh) terminal.
　　　 ※Please see error logs listed as below.

**Graph SDK (please complete the following information):**
 - Microsoft.Graph Version 4.22

**Logs**
　fail: EchoBot.Services.Http.BotMediaLogger[0]
　[AvMP][AppId:6120d1be-b028-4dd5-ac67-7c66583619da] TL_ERROR(TF_COMPONENT) [EC2AMAZ-QJ7I77E]9116.20::10/06/2022-05:55:33.319.0000000C
  (AVMP,UpdateStreamStateAndNotify:SinkStateManager.cs(123)) [MP] UpdateStreamState - MediaType: Audio is unsupported

**Additional context**
　PC in use
　　Edition		Windows Server 2022 Datacenter
　　Version		21H2																

　Visual Studio
　　Microsoft Visual Studio Community 2022 (64-bit) - Current
　　Version 17.3.4

**Comment by ssulzer** [comment]
@Tetsu-Yokota 
I've not seen this error before. Are you still able to reproduce it?
One thing to try is to switch to Windows Server 2019. The bot media SDK has not been validated on Windows Server 2022, so there might be a bug running on the newer version of Windows.
