### ISSUE TITLE
How to debug without ngrok

### ISSUE THREAD

**Issue by DieguJota** [microsoftgraph/microsoft-graph-comms-samples#604]
Today I work with this application locally using NGROK and it works perfectly,

Now, i have a Windows VM on azure (xxxx.cloudapp.azure.com) and I want to debug the application inside that VM, **without using NGROK**, how can I do that?
I think using Ngrok is not recommended if I want to leave it running in production inside this VM, or am I wrong?

Is there any documentation or step by step I can follow?

**Comment by 1fabi0** [comment]
You can open the required ports on the vm's firewall(s) (most probably the ports are 9442 and 8445)
then you also need your certificate for your dns that is pointing to your vm (you could do that with certbot)
then for some projects here you also need to set up url bindings for ssl termination
and don't forget to configure you're application to use you're domain, endpoints, ports and certificate

**Comment by DieguJota** [comment]
@1fabi0 Thanks for the answer, perfect apparently it's pretty easy to do.

But I have a doubt, what would I fill in this configuration of local.{mydomain}.com? According to the documentation I would need to put the NGROK:
[Link](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/PublicSamples/PsiBot#:~:text=In%20your%20App%20Services%20Domain%2C%20map%20the%20CNAME%20entry%20so%20any%20request%20to%20local.%7Bmydomain%7D.com%20will%20be%20redirected%20to%200.tcp.ngrok.io.)

**Comment by DieguJota** [comment]
@1fabi0  So what I need to do is redirect local.{mydomain}.com to xxxx.cloudapp.azure.com:8445 instead of 0.tcp.ngrok.io correct?

**Comment by DieguJota** [comment]
Or would I no longer need this setting in DNS? In the MediaServiceFQDN configuration of the Bot, would I already put xxxx.cloudapp.azure.com:8445?

**Comment by 1fabi0** [comment]
You could do both, whatever you like more.

**Comment by DieguJota** [comment]
@1fabi0 Now I'm having trouble getting the bot to join the call. All media negotiation is done, but I have this error in the project output. Any idea what it could be?

![image](https://user-images.githubusercontent.com/94137522/202531877-c1996ef0-73f4-4dd7-9a35-3f8be5cfd324.png)

**Comment by DieguJota** [comment]
@1fabi0  Now I get call notifications and media settings seem to be done successfully. But I don't get any audio/video buffers, I don't get the participant list either.
Apparently the Bot is not able to participate in the call.

Do you have any idea what the problem is?
[log.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/10035292/log.txt)

**Comment by DieguJota** [comment]
@1fabi0  I'm still investigating but without success... I only receive call notifications, media configuration is done and after that the bot simply doesn't receive any more participant updates, call updates, etc...
[Log2.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/10042783/Log2.txt)

**Comment by 1fabi0** [comment]
I'm not completly sure, if you do that but, in the logs it looks like you try to create more than 9 video sockets allowed are only 9 video sockets per Call and one Video Based Screen sharing socket

**Comment by DieguJota** [comment]
The strange thing is that the same environment, only using Ngrok works perfectly...

**Comment by 1fabi0** [comment]
I think you have to update your `CallControlBaseUrl`, it is set in the initialize of the `AzureSettings` and in default doesn't provide any port there in the url ( with ngrok it is automatically 443 and doesn't need to be set specifically), so make sure that the `CallControlBaseUrl` contains the `CallSignalingPort`

**Comment by nagendramishr** [comment]
I have a similar situation,  I created a self-signed certificate for domain.com and installed it.. I use that thumbprint and am trying to run in a VM in Azure, however I never get  to a point where I can see a socket in a LISTENING state in netstat.   Do I need to use real certificate?  Any thoughts about running this in normal non HTTPS mode as I'll be putting this behind app gateway or something else that can terminate the SSL?

**Comment by DieguJota** [comment]
@1fabi0 That was exactly the problem! Now I'm getting all notifications, thank you so much for your support!

**Comment by 1fabi0** [comment]
@nagendramishr self signed certificates are not allowed

**Comment by nagendramishr** [comment]
@1fabi0 ,  sad... any way to run this without HTTPS or using a developer certificate?

**Comment by 1fabi0** [comment]
@nagendramishr no, for https you could use ngrok... But that doesn't solve you're media platform connection certificate issue

**Comment by nagendramishr** [comment]
If ngrok can be used, couldn't say something like Azure Functions (which has a valid certificate) also be used as a proxy  server?

**Comment by 1fabi0** [comment]
For https probably yes but problem would still be the tcp connection to the media platform problem
-1 you can't reach a azure function via plain tcp (that's required)
-2 azure functions should not run longer than 5 minutes or something arround there so only a durable function could be considered

**Comment by nagendramishr** [comment]
Thank you Fabian,

Is it safe to say of the 3 ports, 1 is HTTPS and the other  TCP?   Is there a document that explains the protocols that the different ports use?  We just want to be able to load balance the service for when it hits resource limits.

Nagendra

**Comment by nagendramishr** [comment]
Is there a way to run this in something like azure app service which provides its own certificate?

**Comment by 1fabi0** [comment]
No 2 reasons you can't access the certificate and the app service only allows https ingress

**Comment by nagendramishr** [comment]
I was thinking of following this article to pull the Thumbprint from Azure app service into the app config.  

https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code
but for the TCP ports, I don't see a way to get it to listen on multiple ports.

I will explore let's encrypt to get a certificate. However a basic question as I'm not even sure if I have things running correctly:  why doesn't netstat show a socket in a listening state even with a self signed certificate?

**Comment by kokosda** [comment]
> I'm not completly sure, if you do that but, in the logs it looks like you try to create more than 9 video sockets allowed are only 9 video sockets per Call and one Video Based Screen sharing socket

How do you know it is 9? Can you share any references?

**Comment by InDieTasten** [comment]
@kokosda Oh, and also @1fabi0 and myself are developing and operating a bot that subscribes and records these streams, so we we know from trial and error as well :D
