### ISSUE TITLE
Resource in notification not recognized

### ISSUE THREAD

**Issue by PieterVandendriessche** [microsoftgraph/microsoft-graph-comms-samples#61]
**Describe the issue**
When /callback/calling is called in my application, it returns an exception when ProcessNotificationAsync method is called.
This exception came after updating to version 1.1.0-prerelease.452. In the previous update this exception wasn't raised. 

**Exception Snippet**
~~~~
 Microsoft.Graph.Communications.Core.Exceptions.ServiceException
  HResult=0x80131500
  Message=Code: invalidRequest
Message: Resource in notification is not recognized.

  Source=Microsoft.Graph.Communications.Core
  StackTrace:
   at Microsoft.Graph.Communications.Core.Notifications.NotificationProcessorExtensions.ExtractResouceData(CommsNotification notification) 
~~~~

**Graph SDK:**
Framework: .NET Core 2.1
- Microsoft.Graph.Communications.Calls 1.1.0-prerelease.452
- Microsoft.Graph.Communications.Client 1.1.0-prerelease.452
- Microsoft.Graph.Communications.Core.Calls 1.1.0-prerelease.452

**Comment by ksikorsk** [comment]
Can you provide a little more information please?  Do you have information regarding the content of the notification giving you this error?  Alternatively, if you could provide a date/time and call id I can look this up on our end.

**Comment by PieterVandendriessche** [comment]
Thank you for your answer @ksikorsk! 
Since the application throws the exception before acquiring a call id, i cannot provide that. The notification is the callback that is done by MS Teams, for example initiating a call, update of participants etc...
This is the Stacktrace:
`  at Microsoft.Graph.Communications.Core.Notifications.NotificationProcessorExtensions.ExtractResouceData(CommsNotification notification)` 

This also happens in the latest version of the sdk ( 1.1.0-prerelease.581).

Thanks in advance!

**Comment by ksikorsk** [comment]
You can look at the headers and content before sending it off to the notification processor.  At a minimum we need your callback URI and date time.  Something to help us find your bot log entry.

**Comment by ksikorsk** [comment]
Further, if you integrate with the IGraphLogger and can provide us with the log traces, we can better diagnose your issue:

All the samples are integrated with the `SampleObserver`:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/Common/Sample.Common/Logging/SampleObserver.cs
https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html

They also have an endpoint to spit out SDK logs:
https://bot.contoso.com/logs

**Comment by PieterVandendriessche** [comment]
The log is the following:
`$>2019-05-14T18:05:15.7488976Z Warning: CommunicationsClientExtensions.cs:231 LogRequestAndCreateResponse
ScenarioId: b1c6dae1-dce6-4fa4-86b8-e5e6f11dfe7b
AppId: f9240451-914d-4708-b5fe-912a4391f49b
AppName: dlwr-phdev-mima-bot
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 2078
request: POST http://localhost/callback/calling
response: 400 BadRequest
headers:
  client-request-id: 4672f9cf-2f3e-4e2c-934b-714c6e5355d9
  scenario-id: b1c6dae1-dce6-4fa4-86b8-e5e6f11dfe7b
  Content-Type: application/json; charset=utf-8
{
  "error": {
    "code": "invalidRequest",
    "message": "Resource in notification is not recognized."
  },
  "statusCode": 400,
  "message": "Code: invalidRequest\r\nMessage: Resource in notification is not recognized.\r\n",
  "data": {},
  "stackTrace": "   at Microsoft.Graph.Communications.Core.Notifications.NotificationProcessorExtensions.ExtractResouceData(CommsNotification notification)\r\n   at Microsoft.Graph.Communications.Client.CommunicationsClient.ProcessNotifications(Uri callbackUri, CommsNotifications notifications, String tenantId, Guid requestId, Guid scenarioId, IDictionary`2 additionalData)\r\n   at Microsoft.Graph.Communications.Client.CommunicationsClientExtensions.ProcessNotificationAsync(ICommunicationsClient client, HttpRequestMessage request)",
  "source": "Microsoft.Graph.Communications.Core",
  "hResult": -2146233088
}
$>2019-05-14T18:05:15.7070810Z Warning: CommunicationsClientExtensions.cs:220 LogRequestAndCreateResponse
ScenarioId: b1c6dae1-dce6-4fa4-86b8-e5e6f11dfe7b
AppId: f9240451-914d-4708-b5fe-912a4391f49b
AppName: dlwr-phdev-mima-bot
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST http://localhost/callback/calling
headers:
  Connection: Keep-Alive
  Accept: application/json
  Authorization: (redacted)
  Host: localhost
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  X-Forwarded-For: (redacted)
  X-Forwarded-Proto: (redacted)
  X-Microsoft-Skype-Caller-Region: emea
  X-Microsoft-Skype-Chain-Id: b1c6dae1-dce6-4fa4-86b8-e5e6f11dfe7b
  X-Microsoft-Skype-Message-Id: 4672f9cf-2f3e-4e2c-934b-714c6e5355d9
  X-Microsoft-Skype-Original-Message-Id: a2684a81-0c5e-410f-a79e-546029ed986c
  X-Original-Host: (redacted)
  MS-ASPNETCORE-TOKEN: (redacted)
  X-Original-For: (redacted)
  X-Original-Proto: (redacted)
  Content-Type: application/json; charset=utf-8
  Content-Length: (redacted)
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "created",
      "resource": "/app/calls/361a0900-66df-49b6-94b2-4fe8bf42cb14",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "incoming",
        "direction": "incoming",
        "callbackUri": "https://4fd61e78.ngrok.io/callback/calling",
        "source": {
          "@odata.type": "#microsoft.graph.participantInfo",
          "identity": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "626fa5d2-aafc-4786-a06f-9476fd932da7",
              "tenantId": "3600ffa3-dc91-4e54-a774-076e624bf463",
              "identityProvider": "AAD"
            }
          },
          "region": "emea",
          "languageId": ""
        },
        "targets": [
          {
            "@odata.type": "#microsoft.graph.participantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "application": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "f9240451-914d-4708-b5fe-912a4391f49b",
                "tenantId": null,
                "identityProvider": "AAD"
              }
            }
          }
        ],
        "tenantId": "3600ffa3-dc91-4e54-a774-076e624bf463",
        "myParticipantId": "de0ba7e3-12d3-4e77-9ef1-27dbc87d69b1",
        "id": "361a0900-66df-49b6-94b2-4fe8bf42cb14"
      }
    }
  ]
}
$>2019-05-14T18:05:15.6279979Z Warning: CommunicationsClientExtensions.cs:213 LogRequestAndCreateResponse
ScenarioId: b1c6dae1-dce6-4fa4-86b8-e5e6f11dfe7b
AppId: f9240451-914d-4708-b5fe-912a4391f49b
AppName: dlwr-phdev-mima-bot
Exception occurred while processing notification
exception: Code: invalidRequest
Message: Resource in notification is not recognized.

StackTrace:    at Microsoft.Graph.Communications.Core.Notifications.NotificationProcessorExtensions.ExtractResouceData(CommsNotification notification)
   at Microsoft.Graph.Communications.Client.CommunicationsClient.ProcessNotifications(Uri callbackUri, CommsNotifications notifications, String tenantId, Guid requestId, Guid scenarioId, IDictionary`2 additionalData)
   at Microsoft.Graph.Communications.Client.CommunicationsClientExtensions.ProcessNotificationAsync(ICommunicationsClient client, HttpRequestMessage request)`

**Comment by ksikorsk** [comment]
@PieterVandendriessche I plugged your payload into our unit tests and everything went through OK.  There were no changes in this code path for a long time.

The only thing I can think of is that the SDK binaries are not being picked up by the serializer.  Can you look in your bin folder and see if the `Microsoft.Graph.Communications.Core.Calls` binary is in the same folder as `Microsoft.Graph.Communications.Core`?

**Comment by ksikorsk** [comment]
@PieterVandendriessche any update?

**Comment by PieterVandendriessche** [comment]
Haven’t checked it yet, Will keep you up to date
