### ISSUE TITLE
Subscription to receive audio frames from the CallHandler owner

### ISSUE THREAD

**Issue by CRochaVox** [microsoftgraph/microsoft-graph-comms-samples#614]
Hello everyone, I have the bot recording Teams meetings perfectly, but the CPU consumption is very high when I have many people on the same call.

In a call with ten people I receive frames from ten people per subscription assigned in the CallHandler, is there a way in the audio subscription itself I can only receive frames from the "owner" of the CallHandler instead of receiving from everyone in the call?

Is there any parameter that I pass?
Or is there any way to only receive audio frames from a person per created callHandler?

**Comment by leo0104** [comment]
Subscriptions are only for video.
You can try out [UnmixedAudioBuffers](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/bot_media/Microsoft.Skype.Bots.Media.AudioMediaBuffer.html#Microsoft_Skype_Bots_Media_AudioMediaBuffer_UnmixedAudioBuffers). With that you are able to receive up to four audio buffers from individual speakers. You have to explicitly enable it in AudioSocketSettings when creating the local media session.

**Comment by CRochaVox** [comment]
Thanks for the answer @leo0104 , I'll check if it works!
