### ISSUE TITLE
Application with instance id GUID is not registered in APS store

### ISSUE THREAD

**Issue by juveinfo** [microsoftgraph/microsoft-graph-comms-samples#62]
Issue: What's Aps Store? How to configure?
My Request URL, something like this:
https://graph.microsoft.com/beta/app/onlineMeetings/6fd19438-xxxx-416b-8007-99057975970c_19:meeting_XXX@thread.v2

**Comment by ksikorsk** [comment]
Hello, 

GET /onlineMeetings has a very specific use case that is only valid if you have a VTC license.  It is not meant to be used to look up a meeting by the thread id.

What are you looking to do with this endpoint?

**Comment by juveinfo** [comment]
Thanks for your reply @ksikorsk 
We want to have the backend service to create meeting, and redirect the meeting joinUrl to our portal, in order to enduser:
1. click the joinUrl to participate the meeting.
2. other participants could be invited automatically.
BTW, when the onlinemeetings and calls API plan to release GA version?

**Comment by ksikorsk** [comment]
GA is scheduled for June/July.  We're working on finalizing the APIs now.

For your scenario, why do you have the thread id in the URI?  That is not needed to create a meeting.  

The URI should be:
`POST https://graph.microsoft.com/beta/app/onlineMeetings`
https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=cs

`GET https://graph.microsoft.com/beta/app/onlineMeetings/{id}` is only supported if you have created a meeting (above) and have the actual meeting id (not the thread id as you have in your example).
https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=cs

**Comment by tpmeredith** [comment]
> GA is scheduled for June/July. We're working on finalizing the APIs now.
> 
> For your scenario, why do you have the thread id in the URI? That is not needed to create a meeting.
> 
> The URI should be:
> `POST https://graph.microsoft.com/beta/app/onlineMeetings`
> https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=cs
> 
> `GET https://graph.microsoft.com/beta/app/onlineMeetings/{id}` is only supported if you have created a meeting (above) and have the actual meeting id (not the thread id as you have in your example).
> https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=cs

Will the API finally allow developers to support CTI integrations with teams? This is a major lacking feature for orgs who switched to teams, especially with SfB EoL targeting April 1st, 2020 as there are virtually zero 'working' CTI integrations with teams. I'm told by numerous developers the beta API is still missing key features to make this happen. For us we use whole MS stack (dynamics, etc) and its painful to not have a call CTI integration from MS teams to MS dynamics.

**Comment by ksikorsk** [comment]
I misspoke on the dates, I've been told we're targeting end of Q3 for API release.

@VinodRavichandran can speak to CTI integrations and which APIs are targeted for release.

**Comment by tpmeredith** [comment]
> I misspoke on the dates, I've been told we're targeting end of Q3 for API release.
> 
> @VinodRavichandran can speak to CTI integrations and which APIs are targeted for release.

Hi Vinod are you able to say if the upcoming API's will allow functionality of CTI for inbound call popup integrations in teams? Ideally it would be awesome if teams finally supported a webhook of some sorts for VoIP/calling.

**Comment by VinodRavichandran** [comment]
Yes it should be. You can refer to this video to see how Informacast Bot puts up an incoming call into Teams. https://www.youtube.com/watch?v=qJ0B-vYRP1g

**Comment by tpmeredith** [comment]
Hi VinodRavichandran I could be missing something but in looking at that youtube video as well as their website, it does not seem to work for inbound calls for teams. It looks like they have to manually type an alert with that bot/app command and then that initiates a call to a team (or just a meeting really?).

What is desperately needed for our company and I'm sure many others is the ability to have either a webhook notification for incoming calls that can extract key details of the call such as CID, DID, user receipient, etc. Either that or the ability in graphs API to have notification of inbound call. Not to just initiate a call otherwise CTI for inbound call popups would not work.

I've spoken to numerous developers from different MS partners and they all say the same thing that this functionality, even in the existing beta API, is not currently possible with teams leaving a big void for VoIP in SfB to Teams.

**Comment by VinodRavichandran** [comment]
Hi @tpmeredith, Thanks for clarifying the scenario. We are working on defining the E2E experience for Calling/Meeting events and would like to get some inputs on the scenario that you had in SFB and now planning for Teams. Can you send me an email at vin@microsoft.com to tell me more about your scenario/use case that your company is implementing?

**Comment by tpmeredith** [comment]
Thanks Vinod our developers and I shot you a few emails, did you receive them? Thanks again,
