### ISSUE TITLE
PsiBotService not joining the call

### ISSUE THREAD

**Issue by affanmehmood** [microsoftgraph/microsoft-graph-comms-samples#621]
I'm trying to set up the Azure portal but my bot fails to join the team's call.

I successfully installed the certificate and all the configurations, but I suspect my azure bot credentials are incorrect.

When I hit join call in https://blah.blah.ngrok.io/manage I get this error message in chrome.
POST https://blah.blah.ngrok.io/joinCall 500

I get ok response on /calls:
![image](https://user-images.githubusercontent.com/46571643/216917235-4f7a3788-9d36-4c77-82a7-ccff6e6bbacd.png)

"AadAppId":  
![image](https://user-images.githubusercontent.com/46571643/216936395-f12eb560-b1c3-4e73-9303-4fb83397c26e.png)

"AadAppSecret": I've used the app secret copied from this 
![image](https://user-images.githubusercontent.com/46571643/216935829-1336319e-5751-4156-971c-75e474a30af7.png)

Also, my Ngrok looks like this, and I've also added the local.mydomainname.co in the DNS manager
And my Ngrok looks like this:
![image](https://user-images.githubusercontent.com/46571643/216953568-635cddd5-dda2-4920-ba18-b96f9fa6b0ea.png)

I am trying to add the boot to the video meeting like this:
![image](https://user-images.githubusercontent.com/46571643/217202631-1e310c58-3e8e-4c44-9175-c8644a054c56.png)

P.s. My  "MediaServiceFQDN" is "local.mydomainname.co" and not "local.mydomainname.com", hope that's not causing the issue.

**Edit: I'm getting this error in Chrome Devtools: 
Join URL cannot be parsed: https://teams.live.com/meet/9592878251510
Parameter name: joinURL**

**Comment by ssulzer** [comment]
@affanmehmood 
Can you share a bot app id please.

**Comment by affanmehmood** [comment]
Thanks for responding. Sure here's my app id: 4cb947b2-b174-484a-a2ba-8898de206a5f

**Comment by ssulzer** [comment]
I don't see any calls for that bot app id - I assume you've tried the join operation within the past 30 days?
Likely the failure occurs before the bot application attempts to join a Teams meeting/call.
