### ISSUE TITLE
No Video Received for Live Events

### ISSUE THREAD

**Issue by ibirman** [microsoftgraph/microsoft-graph-comms-samples#623]
**Describe the issue**
I'm connecting to a Live Event and subscribing to the live video, but no video frames are received.  This is working fine for regular meetings, just not for live events.  This has been working for a while for us but stopped in December 2022.

**Code Snippet**
The subscribe works with no error: 

this.vbssSocket.Subscribe(videoResolution, mediaSourceId);
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot/FrontEnd/Bot/BotMediaStream.cs#L116

**Expected behavior**
Video frames are received

**Graph SDK (please complete the following information):**
1.17.0.39-alpha

**Call ID**
Provide the list call ids that encountered this issue. Include the time in UTC/GMT when these call have occurred.
761f6a00-b6ea-4ee1-aa4d-f594b85739bb

**Logs**
If required, please add [logs](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html) from the SDK. (Please remove any PII from the logs before uploading)

**Additional context**
What other info can I provide?  I don't see any difference between Meeting and Live Event except that I need to let the bot in for a Live Event.  Once I let the bot in, it connects with no errors but does not receive video.

**Comment by ssulzer** [comment]
What is your bot application id?
1.17.0.39 is an old version of the bot media SDK library from 3 years ago. Can you please try upgrading to a newer version?
https://www.nuget.org/packages/Microsoft.Skype.Bots.Media/1.25.0.530-alpha

**Comment by ibirman** [comment]
I tested with 1.25.0.530-alpha and I get the same result.  The bot is able to connect to the live event but does not receive any video.  What else can I try?

**Comment by ssulzer** [comment]
Is the bot able to receive the audio of the Live Event's Teams meeting? (and is not receiving just silence?) It may be the bot is stuck in the lobby.
Can you please share a recent CallId or the bot's application id.

**Comment by ibirman** [comment]
I only hear silence.  The most recent event from today has this URL: https://teams.microsoft.com/l/meetup-join/19%3ameeting_NzM2NDkxNTMtNzE1NC00MDk2LTkzYWItYzA3YjgzODYxOGQ5%40thread.v2/0?context=%7b%22Tid%22%3a%2224ed0676-67e2-4293-a8d4-28937fdb3247%22%2c%22Oid%22%3a%22daed13cd-7dc7-42e4-a429-15f9b364a09b%22%2c%22IsBroadcastMeeting%22%3atrue%7d

**Comment by ssulzer** [comment]
@ibirman 
Can you please conduct a new test where you are certain that there is an active audio/video source within the Teams meeting. e.g., there is a user talking + sharing screen content.
Be sure your bot application handles the transfer from the lobby to the main meeting. While in the lobby, the bot will not be able to hear anything nor will its attempts to subscribe to video sources work. Once in the main meeting, it should be able to hear any talkers and subscribe to their video sources. Be sure to listen to the VideoSocket.VideoReceiveStatusChanged event to handle cases where the VideoSocket's MediaReceiveStatus transitions from Active to Inactive then back to Active, which will happen when the bot is moved from the lobby into the main meeting. After the VideoSocket's MediaReceiveStatus has transitioned back to the Active state, the bot will have to (re-)subscribe on the VideoSocket.

**Comment by ibirman** [comment]
Thanks, that works!
