### ISSUE TITLE
In step when deploying, with New-AzDeployment and xPathQueries:[Security!]

### ISSUE THREAD

**Issue by jamil-z** [microsoftgraph/microsoft-graph-comms-samples#633]
**Describe the issue**
A clear and concise description of what the issue is.I am following the git guide to implement the EchoBot
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/PublicSamples/EchoBot
Now I am at this step: Deploy the Infrastructure
with all the previous steps executed correctly
and with the values of 
    Keyvault Secrets Setup
    Use Cognitive Services mode?
existing

and obtain this error
ProvisioningState: Failed

New-AzDeployment: D:\moodbit\boot-teams-EchoBot\microsoft-graph-comms-samples\Samples\PublicSamples\EchoBot\ADF\release-az\Start-AzDeploy.ps1:310
Line |
 310 |  … $global:r = New-AzDeployment @Common @TemplateArgs @OptionalParameter …

**Expected behavior**
that it will continue with the execution and the deployment is done correctly.

**Logs**

microsoft-graph-comms-samples\Samples\PublicSamples\EchoBot\ADF\release-az\Start-AzDeploy.ps1:310
Line |
 310 |  … $global:r = New-AzDeployment @Common @TemplateArgs @OptionalParameter …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 9:17:39 PM - The deployment 'AEU2-Moodbit-BOT-D1-EchoBot' failed with error(s). Showing 2 out of 2 error(s). Status Message: Data collection rule is invalid (Code: InvalidPayload)  - XPath query is
     | invalid. Query: 'Security!', Error: Query expression cannot be empty. (Code:InvalidProperty)   Status Message: At least one resource deployment operation failed. Please list deployment operations for
     | details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)  - {   "status": "Failed",   "error": {     "code": "ResourceDeploymentFailure",     "message":
     | "The 'AzureAsyncOperationWaiting' resource operation completed with terminal provisioning state 'Failed'.",     "details": [       {         "code": "DeploymentFailed",         "message": "At least one
     | resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",         "details": [           {
     | "code": "BadRequest",             "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidPayload\",\r\n    \"message\": \"Data collection rule is invalid\",\r\n    \"details\": [\r\n      {\r\n
     | \"code\": \"InvalidProperty\",\r\n        \"message\": \"XPath query is invalid. Query: 'Security!', Error: Query expression cannot be empty.\",\r\n        \"target\":
     | \"Properties.DataSources.WindowsEventLogs[0].XPathQueries[0]\"\r\n      }\r\n    ]\r\n  }\r\n}"           }         ]       }     ]   } } (Code:Conflict)   CorrelationId:
     | d739fc31-9cf9-43f5-9a1d-8704911e0d93

**Additional context**
Checking the problem can be in this line 

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/PublicSamples/EchoBot/ADF/release-az/Start-AzDeploy.ps1#L308

or in this other one of the xPathQueries: [
                         'Security!'
                     ]
in; this line
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/PublicSamples/EchoBot/ADF/bicep/OMS.bicep#L844
about this, should it stay like this or should it be modified?

**Comment by atx-barnes** [comment]
I was encountering the same issue trying to stand up the Audio and Video bot.

In the OMS.bicep or whatever arm template file has the 'Security!' xPathQueries value just add the wildcard * at the end so its 'Security!*'
