### ISSUE TITLE
EchoBot Deployment Failing - Cannot Start Service (VMExtensionProvisioningError)

### ISSUE THREAD

**Issue by jamil-z** [microsoftgraph/microsoft-graph-comms-samples#644]
Hello everyone,

I am having trouble deploying EchoBot using both local deployment and GitHub workflow. In both cases, I am encountering the same error related to starting the 'EchoBotService' on the virtual machine.

Here's the error message I am getting:

New-AzDeployment: D:\a\My-Echo-Bot\My-Echo-Bot\Samples\PublicSamples\EchoBot\ADF\release-az\Start-AzDeploy.ps1:329

 Line |
 329 |  … $global:r = New-AzDeployment @Common @TemplateArgs @OptionalParameter …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 2:03:14 PM - The deployment 'AEU1-XXXXXXX-BOT-D1-EchoBot' failed with error(s). Showing 2 out of 2 error(s).
     | Status Message: At least one resource deployment operation failed. Please list deployment operations for
     | details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)  - The
     | resource write operation failed to complete successfully, because it reached terminal provisioning state
     | 'Failed'. (Code: ResourceDeploymentFailure)    - VM has reported a failure when processing extension
     | 'Microsoft.Powershell.DSC'. Error message: "DSC Configuration 'BotServers' completed with error(s). Following
     | are the first few: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource
     | functionality with error message: The running command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop: Service 'EchoBotService (EchoBotService)' cannot be
     | started due to the following error: Cannot start service EchoBotService on computer '.'.  The
     | SendConfigurationApply function did not succeed."  More information on troubleshooting is available at
     | https://aka.ms/VMExtensionDSCWindowsTroubleshoot  (Code:VMExtensionProvisioningError)    Status Message: At
     | least one resource deployment operation failed. Please list deployment operations for details. Please see
     | https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)  - The resource write
     | operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code:
     | ResourceDeploymentFailure)    - At least one resource deployment operation failed. Please list deployment
     | operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code:
     | DeploymentFailed)      - The resource write operation failed to complete successfully, because it reached
     | terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)        - At least one resource
     | deployment operation failed. Please list deployment operations for details. Please see
     | https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)          - The resource
     | write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code:
     | ResourceDeploymentFailure)            - VM has reported a failure when processing extension
     | 'Microsoft.Powershell.DSC'. Error message: "DSC Configuration 'BotServers' completed with error(s). Following
     | are the first few: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource
     | functionality with error message: The running command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop: Service 'EchoBotService (EchoBotService)' cannot be
     | started due to the following error: Cannot start service EchoBotService on computer '.'.  The
     | SendConfigurationApply function did not succeed."  More information on troubleshooting is available at
     | https://aka.ms/VMExtensionDSCWindowsTroubleshoot  (Code:VMExtensionProvisioningError)    CorrelationId:
     | xxx-xxx-xxx-xxx
     
I have redacted sensitive information with 'xxx-xxx-xxx-xxx'.

Has anyone experienced a similar issue, or can someone provide guidance on how to resolve this problem? Any help would be greatly appreciated.

Thank you!

**Comment by ravitejaobelisk** [comment]
Hello @jamil-z , I have been facing the same issue for the past four days and I am unable to identify the root cause. If you have any leads on this issue, please let me know. Thank you.
