### ISSUE TITLE
[Policy Recording bot] How to get both unmixed and mixed audio

### ISSUE THREAD

**Issue by oxygennik2009** [microsoftgraph/microsoft-graph-comms-samples#645]
Hi,

It's mentioned that in order to get both audio stream options **a bot should establish two separate calls into the meeting**

> In order to receive both mixed and unmixed audio simultaneously, the bot must establish two separate calls into the meeting.

It's not a second bot as I understood and it's not answering the same call two times either.
Will anything like inviting the same the bot through the associated application id work? 

Could anyone please guide me or give any tips on how to do that?

**Comment by oxygennik2009** [comment]
@1fabi0 Yeah, you got what I was asking about :D

> And if you are wondering: with mixed audio you can also only receive audio of at max 4 participants at a time just like unmixed audio.

At first, I thought mixed audio would let me capture audio from more than four people talking at once. That's why I was thinking of making another call to get mixed and unmixed data.

However, I'm still uncertain about the reason behind mentioning the need to establish a separate call to receive both mixed and unmixed streams. I'm also curious about the benefits of having both streams. Seems like there are none.

Thank you very much for your help!

**Comment by ssulzer** [comment]
A minor difference between the current mixed and unmixed audio formats: mixed audio has treatment applied to mitigate (conceal/"heal") packet loss and other network-related impairments, while unmixed audio does not. For a media bot running in Azure, most of the time packet loss (between the Teams meeting server and bot) is not a concern.

However, an upcoming release of the Microsoft.Skype.Bots.Media library will introduce a new feature to allow a single AudioSocket to deliver both mixed and unmixed audio simultaneously to the application. In the meantime, I would follow the advice from @1fabi0 to generate your own audio mix; you can then remove that when the new bot media SDK feature is available. Thanks.

**Comment by oxygennik2009** [comment]
@ssulzer Many thanks for the clarification!

**Comment by ssulzer** [comment]
@oxygennik2009 
FYI, our latest bot media SDK version 1.26.0.94 has a feature to allow the bot to receive both mixed and unmixed audio simultaneously using a single call session / AudioSocket.

https://[nuget.info/packages/Microsoft.Skype.Bots.Media/1.26.0.94-alpha](https://nuget.info/packages/Microsoft.Skype.Bots.Media/1.26.0.94-alpha)

Please see the readme.txt in the SDK about the new AudioSocketSettings EnableLocalAudioMixingForUnmixed API.

**Comment by oxygennik2009** [comment]
> @oxygennik2009 FYI, our latest bot media SDK version 1.26.0.94 has a feature to allow the bot to receive both mixed and unmixed audio simultaneously using a single call session / AudioSocket.
> 
> https://[nuget.info/packages/Microsoft.Skype.Bots.Media/1.26.0.94-alpha](https://nuget.info/packages/Microsoft.Skype.Bots.Media/1.26.0.94-alpha)
> 
> Please see the readme.txt in the SDK about the new AudioSocketSettings EnableLocalAudioMixingForUnmixed API.

@ssulzer many thanks!

And while it's not related to this thread but perhaps, you could shed some light on what deployment options are recommended for the Bot?
Seems like officially the only options are Cloud Services, Service Fabric and VMs. Any Azure Containers/Kubernetes options or there is no support for them? (The sample code is/was deprecated)
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots#c-or-net-and-windows-server-for-development

**Comment by InDieTasten** [comment]
> And while it's not related to this thread but perhaps, you could shed some light on what deployment options are recommended for the Bot?

Depends on your needs. AKS and Service Fabric are great for availability, scaling and orchestration during operation in general. Classic Cloud Services and VMs are a bit more static and don't offer too many options in the orchestration department, but are not as complicated to set up.

I can't say too much about the deprecation status of the various samples, but I think they all are a bit outdated. Updating them takes a bit of work, but isn't rocket science once you understand how the samples work. I run an up to date version in AKS in production for example.

**Comment by oxygennik2009** [comment]
> > And while it's not related to this thread but perhaps, you could shed some light on what deployment options are recommended for the Bot?
> 
> Depends on your needs. AKS and Service Fabric are great for availability, scaling and orchestration during operation in general. Classic Cloud Services and VMs are a bit more static and don't offer too many options in the orchestration department, but are not as complicated to set up.
> 
> I can't say too much about the deprecation status of the various samples, but I think they all are a bit outdated. Updating them takes a bit of work, but isn't rocket science once you understand how the samples work. I run an up to date version in AKS in production for example.

@InDieTasten Thank you!
