### ISSUE TITLE
Help me with graph communication calls api 

### ISSUE THREAD

**Issue by MiguelAngelSilva** [microsoftgraph/microsoft-graph-comms-samples#65]
Could someone help with an example on how to call a team contact through api rest? I have seen the documentation of Graph Communication Calls but I do not understand how to do it.

**Comment by ksikorsk** [comment]
https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&tabs=javascript

@VinodRavichandran @zhengni-msft do you know when we're doing a documentation sync?  Not all the examples in these are correct.

**Comment by ksikorsk** [comment]
@MiguelAngelSilva are you using an SDK and one of the samples, or are you using REST API directly?

**Comment by MiguelAngelSilva** [comment]
I want to use the Microsoft Graph sdk, but when I read the documentation I can not understand how to create a call that calls a Microsoft Teams contact.

**Comment by ksikorsk** [comment]
@MiguelAngelSilva It sounds like you are looking for a client SDK.  The API and SDK is meant to support server scenarios as a "Bot".  You need to have a publicly visible callback URI.

Do you require access to the raw media streams?

If you have a Windows Forms Application, you have a stateful application.  You should leverage the stateful SDK:
https://www.nuget.org/packages/Microsoft.Graph.Communications.Calls

Samples can be found here, keep in mind that these are all web applications:
https://github.com/microsoftgraph/microsoft-graph-comms-samples

**Comment by MiguelAngelSilva** [comment]
Thanks @ksikorsk  , are there any explanations about the architecture that you implemented in the examples?

**Comment by ksikorsk** [comment]
The samples try to stay simple... but they are stateful, so require [call affinity](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/StateManagement.html).  

Some documentation [here](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/Getting%20Started%20with%20the%20Local%20Media%20Samples.md) on the app hosted media samples.

And the specific documentation for [AudioVideoPlaybackBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot) and [HueBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot).

**Comment by ksikorsk** [comment]
Closing this issue as the question was too generic, and guidance was provided.

**Comment by MiguelAngelSilva** [comment]
> The samples try to stay simple... but they are stateful, so require [call affinity](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/StateManagement.html).
> 
> Some documentation [here](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/Getting%20Started%20with%20the%20Local%20Media%20Samples.md) on the app hosted media samples.
> 
> And the specific documentation for [AudioVideoPlaybackBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot) and [HueBot](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot).



What kind of project have you created for IncidentBot?
is Asp Net Web Api? Bot Framwork project? I do not know.

  And where did the directory structure created in the project come from (Folders: Bot, Controller, Data, Extensions and IncidentManagement)?

![image](https://user-images.githubusercontent.com/12915572/58504068-b66c0a00-813e-11e9-95b3-0bbbd4274c9e.png)

**Comment by ksikorsk** [comment]
Call affinity means that the instance of the application that handles the initial request needs to be the same instance that handles the call throughout the lifetime of the call.  There is affinity between the call and the instance handling the call.  In a multi instance environment (which the samples support), all notifications for the same call need to be routed to the same instance, given that that is where the call state is homed.

Incident bot is an ASP.NET Core Web Application leveraging the Microsoft.Graph calling APIs, and using the Microsoft.Graph.Communications SDK.

The directory structure is a logical grouping of content:
Bot -> The bot protocols for placing/answering calls, checking for participants, playing media, etc...
Controllers -> The Web API component of the sample.  This is how the sample communicates with other services.
Data -> The objects the sample uses for communication using it's rest API (exposed in Controllers)
IncidentManagement -> The business logic of the IncidentBot.

**Comment by MiguelAngelSilva** [comment]
you are the best! @ksikorsk 
Thanks! But  how can I use your example to have the bot redirect or transfer a call to a contact? In which class the code should be implemented to transfer the call. Could you help me or give me an example? since in the examples none uses redirection or call transfers.

**Comment by Laxmikantyadav94** [comment]
Hi,

Getting Below error while trying to fetch call details-

{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2020-06-30T12:32:22",
            "request-id": "9b8597c1-f6bf-483a-953b-809760bb7e7a"
        }
    }
}

https://graph.microsoft.com/v1.0/communications/calls/7ce57e74-f13e-4b83-8ab7-08518db159c9


I have provided token in header as well.

Any help would be much appriciated.
