### ISSUE TITLE
I am getting forbidden error when I make http post request from postman

### ISSUE THREAD

**Issue by rnpramasamy** [microsoftgraph/microsoft-graph-comms-samples#66]
To run this sample code, I registered a bot, added Teams Channel to the bot, and gave permissions to the bot to make calls based on instructions given in the below url:

https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/calls/register-calling-bot.html

**I deployed a bot in Microsoft Teams but no option for calling on my bot.**

I  scheduled a meeting at Microsoft Teams, and made http request to join in the meeting using Postman based on instructions given in the  below url:

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/BetaSamples/RemoteMediaSamples/Getting%20Started%20with%20the%20Remote%20Media%20Samples.md

Http Url: https://3ce.ngrok.io/incidents/raise

**But I got below exception:**
**{"Code: generalException\r\nMessage: Unexpected exception returned from the service.\r\nStatus Code: Forbidden\r\nScenario Id: 2b72668b-55da-430b-bd16-5fb7753820ce\r\n"}**

Error line:
**var statefulCall = await this.client.Calls().AddAsync(joinParam, scenarioId).ConfigurationAwait(false);**

**Comment by ksikorsk** [comment]
> I deployed a bot in Microsoft Teams but no option for calling on my bot.

That would be an issue with teams or an App Studio manifest mis-configuration.  Did you install the bot on your test client?

![image](https://user-images.githubusercontent.com/1817749/58271949-500c7380-7d5b-11e9-97f8-21205bbad946.png)

The specific error was:
```http
HTTP/1.1 403
Content-Type: application/json; odata.metadata=minimal
OData-Version: 4.0
{
  "error": {
    "code": "9004",
    "message": "Insufficient enterprise tenant permissions, cannot access this API."
  }
}
```

Did you give your bot tenant consent in your tenant to join the meeting?  The incident bot readme is lacking this information.  Some more info in the [Getting Started](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/Getting%20Started%20with%20the%20Local%20Media%20Samples.md#getting-started) section for local media samples.

**Comment by rnpramasamy** [comment]
I installed bot with team 

I gave admin consent to Bot

**Comment by rnpramasamy** [comment]
I installed bot with team 

I gave admin consent to Bot

**Comment by ksikorsk** [comment]
Does the bot have consent to the tenant that is hosting the meeting?  The error is saying that your bot does not have permissions to join the meeting.

**Comment by rnpramasamy** [comment]
Yes I gave permission to app to make calls when I created app and those permissions required admin consent. So in admin consent url, I used tenant id and app Id, pasted that url on browser address bar, it redirected me to admin consent page and I accepted those permissions

**Comment by ksikorsk** [comment]
Which scopes did you select?  You need the following:
- Calls.Initiate
- Calls.JoinGroupCall.All
- Calls.JoinGroupAsGuestCall.All

**Comment by ksikorsk** [comment]
Also, can you confirm that the tenant of the call matches the tenant of the meeting?

{
    "name": "<name-of-incident>", --> can be any string value
    "time": "<start-time-of-the-incident>", --> must be valid C# DateTime string
    **"tenantId": "{TenantId}", --> TenantID of the users your bot will be calling**
    "objectIds": [
        "{UserObjectId-1}",
        "{UserObjectId-2}"
    ],
    **"joinURL": "https://teams.microsoft.com/l/meetup-join/...",**
    "removeFromDefaultRoutingGroup": true,
    "allowConversationWithoutHost": true
}

**Comment by rnpramasamy** [comment]
Yes I used tenant Id and join url in post body request.

**Comment by rnpramasamy** [comment]
![image](https://user-images.githubusercontent.com/5311453/58300978-599ce680-7e02-11e9-9c3a-4a90dc0b6cbb.png)

![image](https://user-images.githubusercontent.com/5311453/58301087-b4ced900-7e02-11e9-8165-bbe217637751.png)

Webhook for calling:
I tried both:

https://mydomain.com/callback/calling

https://mydomain.com/api/calls

**Comment by ksikorsk** [comment]
Thanks for redacting all the private content.  Please confirm that the "tenantId" in the payload matches the "tid" in the joinUrl.  You can url decode the join URL to see the "tid".  Note that a tenant admin from this tenant is required to give you consent to place calls and join meetings.

**Comment by rnpramasamy** [comment]
Yes I checked it. The  tenantId matches value of tid.

**Comment by ksikorsk** [comment]
I see you are getting a 502 response now, not a forbidden response.  Can you look at the logs and let me know if you're having any errors?  Also look at your service in azure and make sure everything is starting up correctly.

**Comment by rnpramasamy** [comment]
Postman shows 502 response. But In the source code, I am getting below error:

{"Code: generalException\r\nMessage: Unexpected exception returned from the service.\r\nStatus Code: Forbidden\r\nScenario Id: 2b72668b-55da-430b-bd16-5fb7753820ce\r\n"}

Error line:
var statefulCall = await this.client.Calls().AddAsync(joinParam, scenarioId).ConfigurationAwait(false);

**Comment by rnpramasamy** [comment]
I got below trace information from Fiddler:

![image](https://user-images.githubusercontent.com/5311453/58687063-2e843b00-839e-11e9-9d78-f2f820a0b2f1.png)

Result:
![image](https://user-images.githubusercontent.com/5311453/58687161-7c993e80-839e-11e9-95ec-3e454e4dd41f.png)

I checked my tenant id and I have given correct one. But I am getting above error.

**Comment by MiguelAngelSilva** [comment]
@rnpramasamy 
you must enable the developer preview mode in Microsoft Teams.

![Uploading Enable Developer Preview.png…]()


> > I deployed a bot in Microsoft Teams but no option for calling on my bot.
> 
> That would be an issue with teams or an App Studio manifest mis-configuration. Did you install the bot on your test client?
> 
> ![image](https://user-images.githubusercontent.com/1817749/58271949-500c7380-7d5b-11e9-97f8-21205bbad946.png)
> 
> The specific error was:
> 
> ```httpspec
> HTTP/1.1 403
> Content-Type: application/json; odata.metadata=minimal
> OData-Version: 4.0
> {
>   "error": {
>     "code": "9004",
>     "message": "Insufficient enterprise tenant permissions, cannot access this API."
>   }
> }
> ```
> 
> Did you give your bot tenant consent in your tenant to join the meeting? The incident bot readme is lacking this information. Some more info in the [Getting Started](https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/Getting%20Started%20with%20the%20Local%20Media%20Samples.md#getting-started) section for local media samples.

**Comment by rnpramasamy** [comment]
I did it and I made a call from installed bot, the call reached to the bot code which is running in the Visual Studio. But my actual issue is when i join in a meeting using Microsoft.Graph.Communications.Client sdk, I am getting an error called "Request authorization tenant mismatch"

**Comment by rnpramasamy** [comment]
Please me to fix that error

**Comment by ksikorsk** [comment]
I need more information regarding the error.  Can you please send me a client log of the failed request?  You can do this by looking at the logs endpoint.  You can redact any private information app id, object ids, etc...

https://mydomain.com/logs

**Comment by rnpramasamy** [comment]
I traced by fiddler

Http Request

https://graph.microsoft.com/beta/app/calls

http response status code 403

http response message: request authorization tenant mismatch.

**Comment by ksikorsk** [comment]
I need the full request (including headers to locate it in our service logs).

**Comment by ksikorsk** [comment]
Please note that this is the request between the bot and the graph service, and not between your local client and the bot.

**Comment by ksikorsk** [comment]
Hello... I am closing this issue until further data is provided.  Please re-open if you're still experiencing the issue and can provide http traces (between the bot and the graph service).

**Comment by bikramdolai** [comment]
HI I am trying to setup the stateless solution , but getting the below error. I have followed all the above steps. Please help.
![image](https://user-images.githubusercontent.com/75412204/100972050-175b7600-355e-11eb-9a64-121777e07c59.png)

**Comment by ShwethaVenkatesh-wq** [comment]
Hi I have set up stateless solution. I have given all the permissions and checked my tenant id and I have given correct one. I have followed all the above solution but still I have the below error.
![Error](https://user-images.githubusercontent.com/75416361/101018765-f876d700-3591-11eb-8b6e-bae3479a306f.png)
