### ISSUE TITLE
Grouping mode and participantCapacity

### ISSUE THREAD

**Issue by luko28** [microsoftgraph/microsoft-graph-comms-samples#660]
Does this "Grouping mode" in policy recording bot works?
I'm setting the participantCapacity in ICall.AswerAsync, but it seems like it doesn't make any difference.

**Comment by InDieTasten** [comment]
It takes a bit more work to get this feature to work. First, if there are multiple join requests for the same meeting hitting your bot instance, then the platform will invite multiple bots, as only the answer of any of the join requests contains info about the capacity the bot supports.

Then, subsequent participants joining and requiring the bot for the same policy a special request will be sent to the bot. This notification needs to be processed via your own code. You need to handle the request and generate an Accept response for the platform to know you've really accepted this new participant. The CommunicationClient is not doing all the work for you here.

The docs are pretty slim on this, but yeah... this is how it works.

If you need further assistance, let me kow.

**Comment by InDieTasten** [comment]
Yes, this code should do the trick:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/c01a738af7ac1379e7e36fa62ed55beb87ef1476/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot/FrontEnd/Bot/CallHandler.cs#L228-L249

However, I'm not sure it really works and whether the event gets triggered properly using this way.
If it doesn't work as described, then there are still issues. I know that it works, when I circumvent the entire comms client and return the acceptJoinResponse manually from within my controller action.

**Comment by luko28** [comment]
It works, but I also had to update all packages (Microsoft.Graph...) to latest versions (I was a few releases late).
Thanks for help.
