### ISSUE TITLE
Incident Bot deployed on Azure: getting forbidden error on raising incident

### ISSUE THREAD

**Issue by rajlpand** [microsoftgraph/microsoft-graph-comms-samples#69]
Hi,

I am trying to make a call using Incident Bot sample and have deployed it on Azure at:

https://msgcsvspincbot1.azurewebsites.net/

I got API permissions granted by Admin, but when I try to raise incident there is a forbidden error, logs for this can be found at:

https://msgcsvspincbot1.azurewebsites.net/logs

The Azure tenant that I am trying this with has been granted the following API permissions by Azure Admin:

1) Microsoft.Graph.Calls.AccessMedia.All
2) Microsoft.Graph.Calls.Initiate.All
3) Microsoft.Graph.Calls.InitiateGroupCall.All
4) Microsoft.Graph.Calls.JoinGroupCall.All
5) Microsoft.Graph.Calls.JoinGroupCallAsGuest.All

Here is the JSON payload for POST request to raise incident:

{
    "name": "TestIn9", 
    "time": "Thursday, May 28, 2019 10:10 AM", 
    "tenantId": "97009a52-97e9-4290-8f2c-a8ac8925d978",
    "objectId1": "ea1e52f3-9b41-4610-bbe7-8533adf2be76",
    "objectId2": "66d29a15-1617-4971-9611-440fc13bb927",
    "joinURL": "https://teams.microsoft.com/_#/l/meetup-join/19:fb9e9eec508b41f3a106fccdae1fc8d8@thread.skype/1559064739458?context=%7B%22Tid%22:%22dad97a0c-c63c-4d47-820c-0e24b682426c%22,%22Oid%22:%22ea1e52f3-9b41-4610-bbe7-8533adf2be76%22%7D&anon=true&deeplinkId=95183f13-d1da-421e-fb5a-007588ece438",
    "removeFromDefaultRoutingGroup": true,
    "allowConversationWithoutHost": true
}

I have created an online meeting in Teams and am able to join using the two teams users whose objectID is used (minor modification to the sample for using objectIDs instead of array). Logs for the error seen in bot are attached, could you please check and see why this call is being forbidden?
[WSForbiddenError-5-28-19.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/3229102/WSForbiddenError-5-28-19.txt)

**Comment by ksikorsk** [comment]
The tenant ID of the meeting you are trying to join does not match the tenant id of the request payload:

Meeting tenant:
`"Tid":"dad97a0c-c63c-4d47-820c-0e24b682426c",`

tenant id of the users you are calling:
`"tenantId": "97009a52-97e9-4290-8f2c-a8ac8925d978",`

Which tenant has given you consent for the above permissions?  Our APIs don't currently support cross tenant scenarios, please ensure that the tenant of the meeting matches the tenant of the users you are calling, and that you have tenant consent for this tenant.

**Comment by rajlpand** [comment]
Thanks for the quick response, I am a user in the first tenant where the meeting was created and bot was registered with API permissions with other tenant where I am guest user. Will try it out within the same tenant, appreciate the clarification on cross tenant issue.

**Comment by rajlpand** [comment]
Sample works great with meeting created by user in same tenant, thanks for all the help!
