### ISSUE TITLE
how to create, respond, transfer calls with the sdk of Microsoft.Graph.Communications?

### ISSUE THREAD

**Issue by MiguelAngelSilva** [microsoftgraph/microsoft-graph-comms-samples#70]
**Describe the issue**
Someone implemented in their projects how to create, respond, transfer calls with the sdk of Microsoft.Graph.Communications?

Please take a step by step how to create the project, the type of project, etc.

Any real case?

**Comment by ksikorsk** [comment]
Can you clarify your question please?  

We have samples that join calls:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b900273ef1ceada77d6d45062b29c5ac54ae529/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/JoinCallController.cs#L54

place calls:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b900273ef1ceada77d6d45062b29c5ac54ae529/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/MakeCallController.cs#L50

answer incoming calls: 
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b900273ef1ceada77d6d45062b29c5ac54ae529/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Bot/Bot.cs#L442

We don't have any samples that do Transfer, but please look at the [API specifications](https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&tabs=cs) and [SDK documentation](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/calls/Microsoft.Graph.Communications.Calls.ICall.html?q=Transfer#Microsoft_Graph_Communications_Calls_ICall_TransferAsync_Microsoft_Graph_InvitationParticipantInfo_System_Threading_CancellationToken_).

**Comment by MiguelAngelSilva** [comment]
What I want to achieve is:
A bot that receives a call and transfers it to a Microsoft Teams contact

Do you have a step by step how to create a project from scratch?

**Comment by MiguelAngelSilva** [comment]
I'm running IncidentBot on my localhost.
I am using postman in the following way:
![image](https://user-images.githubusercontent.com/12915572/58588037-9b1efe80-8213-11e9-8d56-b1283788619e.png)

this is the configuration of the bot in azure:
![image](https://user-images.githubusercontent.com/12915572/58588347-4e87f300-8214-11e9-8e4b-058991aea80f.png)

this is the configuration of the appsettings.json file:
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "contoso.com",
    "TenantId": "00000000-0000-0000-0000-000000000000",

    "AppId": "00000000-0000-0000-0000-000000000000",
    "AppSecret": "__placeholder__"
  },
  "Bot": {
    "AppId": "058397a6-8ceb-48f4-b404-c15ef006c254",
    "AppSecret": "pnffVZFNFRB9;_cpv5161-!",
    "PlaceCallEndpointUrl": "https://graph.microsoft.com/beta",
    "BotBaseUrl": "https://6c904bcf.ngrok.io"
  }
}



No me funciona /makeCall

**Comment by JapNolt** [comment]
In your Azure bot registration for the webhook, instead of /makecall it should be /callback/calling. So when MS Graph wants to talk to your bot, it'll use the /callback/calling route but when you want to tell your bot to make a call using Postman, you'll use the /makecall route.

**Comment by ksikorsk** [comment]
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/7b900273ef1ceada77d6d45062b29c5ac54ae529/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/PlatformCallController.cs#L44

**Comment by ksikorsk** [comment]
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/aa91682c44c0d91876275212fbb2a45e6d6e600b/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/Controllers/HttpRouteConstants.cs#L13-L21

**Comment by ksikorsk** [comment]
> Click "edit" button of "Skype" channel, click "Calling" tab, select "Enable calling" radio button, then select "IVR - 1:1 IVR audio calls", and fill the Webhook (for calling) edit box with value "{BotBaseUrl}/callback/calling".

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/aa91682c44c0d91876275212fbb2a45e6d6e600b/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/README.md

**Comment by MiguelAngelSilva** [comment]
> > Click "edit" button of "Skype" channel, click "Calling" tab, select "Enable calling" radio button, then select "IVR - 1:1 IVR audio calls", and fill the Webhook (for calling) edit box with value "{BotBaseUrl}/callback/calling".
> 
> https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/aa91682c44c0d91876275212fbb2a45e6d6e600b/Samples/BetaSamples/RemoteMediaSamples/IncidentBot/README.md

Ok, in Readme.md says

{
  "name": "<name-of-incident>", 
  "time": "<start-time-of-the-incident-in-ISO-8601-format>", 
  "tenantId": "{TenantId}",
  "objectIds": [
    "{UserObjectId-1}",
    "{UserObjectId-2}"
  ],
  "meetingId": "{MeetingId}",
  "joinURL": "https://teams.microsoft.com/l/meetup-join/...",
  "removeFromDefaultRoutingGroup": true,
  "allowConversationWithoutHost": true
}

"meetingId": "{MeetingId}" where I get this data?

The channel bot record in azure is in my personal account. But the "tenantId": "{TenantId}" is that of my organization.
The azure channel bot must be registered in my organization's Tenant or can it be my personal account?

**Comment by ksikorsk** [comment]
Where the bot is registered has no bearing, we only care if the bot has consent from the tenant where they are performing the actions.

The meeting ID is only relevant for VTC cases (conference room terminals).  You may ignore in your context.

**Comment by MiguelAngelSilva** [comment]
Ok, now I was trying to transfer a call by inserting the code in the following example.
Could you please review it?
This is an example of Tom Morgan.
In the class Bot.cs -> Method CallsOnIncoming (ICallCollection sender, CollectionEventArgs <ICall> args) I put the code to transfer a call but when debugging the code does nothing.

### This is the code of the original Bot.cs file:
`

namespace ThoughtStuff.TeamsSamples.IVRBotSample
{
    using Microsoft.ApplicationInsights;
    using Microsoft.Extensions.Logging;
    using Microsoft.Graph;
    using Microsoft.Graph.Calls;
    using Microsoft.Graph.Core;
    using Microsoft.Graph.Core.Telemetry;
    using Microsoft.Graph.StatefulClient;
    using Sample.Common.Authentication;
    using Sample.Common.Meetings;
    using Sample.Common.OnlineMeetings;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ThoughtStuff.TeamsSamples.Data;



    /// <summary>
    /// The core bot logic.
    /// </summary>
    public class Bot
    {

        private readonly IGraphLogger graphLogger;

        private ConcurrentDictionary<string, CallHandler> callHandlers = new ConcurrentDictionary<string, CallHandler>();

        private LinkedList<string> callbackLogs = new LinkedList<string>();

        private AuthenticationProvider authProvider;
        private TelemetryClient telemetry = new TelemetryClient();

        public Uri baseURL { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bot"/> class.
        /// </summary>
        /// <param name="options">The bot options</param>
        /// <param name="loggerFactory">The logger factory</param>
        public Bot(BotOptions options, IGraphLogger graphLogger)
        {
            var instanceNotificationUri = CallAffinityMiddleware.GetWebInstanceCallbackUri(new Uri(options.BotBaseUrl, HttpRouteConstants.OnIncomingRequestRoute));

            this.graphLogger = graphLogger;
            this.baseURL = options.BotBaseUrl;

            var authProvider = new AuthenticationProvider(
                options.AppId,
                options.AppSecret,
                this.graphLogger);

            var builder = new StatefulClientBuilder("TeamsIVRBotSample", options.AppId, this.graphLogger);
            builder.SetAuthenticationProvider(authProvider);
            builder.SetNotificationUrl(instanceNotificationUri);
            builder.SetServiceBaseUrl(options.PlaceCallEndpointUrl);

            this.Client = builder.Build();


            this.Client.Calls().OnIncoming += this.CallsOnIncoming;
            this.Client.Calls().OnUpdated += this.CallsOnUpdated;

        }


        /// <summary>
        /// Gets the client.
        /// </summary>
        /// <value>
        /// The client.
        /// </value>
        public IStatefulClient Client { get; }



        /// <summary>
        /// add callback log for diagnostics
        /// </summary>
        /// <param name="message">the message</param>
        public void AddCallbackLog(string message)
        {
            this.callbackLogs.AddFirst(message);
        }


        /// <summary>
        /// Incoming call handler
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="args">The <see cref="CollectionEventArgs{ICall}"/> instance containing the event data.</param>
        private void CallsOnIncoming(ICallCollection sender, CollectionEventArgs<ICall> args)
        {
            Task answerTask;

            var call = args.AddedResources.First();

            var callee = call.Resource.Targets.First();
            var callType = callee?.Identity?.GetApplicationInstance() == null ? CallType.BotIncoming : CallType.BotEndpointIncoming;

            var callHandler = new IncomingCallHandler(this, call);
            this.callHandlers[call.Resource.Id] = callHandler;
            var mediaConfig = new List<MediaInfo>();

            answerTask = call.AnswerAsync(mediaConfig, new[] { Modality.Audio });

            Task.Run(async () =>
            {
                try
                {
                    await answerTask.ConfigureAwait(false);
                    this.graphLogger.Info("Started answering incoming call");
                }
                catch (Exception ex)
                {
                    this.graphLogger.Error(ex, $"Exception happened when answering the call.");
                }
            });
        }

        /// <summary>
        /// Updated call handler.
        /// </summary>
        /// <param name="sender">The <see cref="ICallCollection"/> sender.</param>
        /// <param name="args">The <see cref="CollectionEventArgs{ICall}"/> instance containing the event data.</param>
        private void CallsOnUpdated(ICallCollection sender, CollectionEventArgs<ICall> args)
        {
            foreach (var call in args.RemovedResources)
            {
                if (this.callHandlers.TryRemove(call.Id, out CallHandler handler))
                {
                    handler.Dispose();
                }
            }
        }



    }
}
`
### This is the code modified by me to transfer the call:

`

namespace ThoughtStuff.TeamsSamples.IVRBotSample
{
    using Microsoft.ApplicationInsights;
    using Microsoft.Extensions.Logging;
    using Microsoft.Graph;
    using Microsoft.Graph.Calls;
    using Microsoft.Graph.Core;
    using Microsoft.Graph.Core.Telemetry;
    using Microsoft.Graph.StatefulClient;
    using Sample.Common.Authentication;
    using Sample.Common.Meetings;
    using Sample.Common.OnlineMeetings;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ThoughtStuff.TeamsSamples.Data;



    /// <summary>
    /// The core bot logic.
    /// </summary>
    public class Bot
    {

        private readonly IGraphLogger graphLogger;

        private ConcurrentDictionary<string, CallHandler> callHandlers = new ConcurrentDictionary<string, CallHandler>();

        private LinkedList<string> callbackLogs = new LinkedList<string>();

        private AuthenticationProvider authProvider;
        private TelemetryClient telemetry = new TelemetryClient();

        public Uri baseURL { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bot"/> class.
        /// </summary>
        /// <param name="options">The bot options</param>
        /// <param name="loggerFactory">The logger factory</param>
        public Bot(BotOptions options, IGraphLogger graphLogger)
        {
            var instanceNotificationUri = CallAffinityMiddleware.GetWebInstanceCallbackUri(new Uri(options.BotBaseUrl, HttpRouteConstants.OnIncomingRequestRoute));

            this.graphLogger = graphLogger;
            this.baseURL = options.BotBaseUrl;

            var authProvider = new AuthenticationProvider(
                options.AppId,
                options.AppSecret,
                this.graphLogger);

            var builder = new StatefulClientBuilder("TeamsIVRBotSample", options.AppId, this.graphLogger);
            builder.SetAuthenticationProvider(authProvider);
            builder.SetNotificationUrl(instanceNotificationUri);
            builder.SetServiceBaseUrl(options.PlaceCallEndpointUrl);

            this.Client = builder.Build();


            this.Client.Calls().OnIncoming += this.CallsOnIncoming;
            this.Client.Calls().OnUpdated += this.CallsOnUpdated;

        }


        /// <summary>
        /// Gets the client.
        /// </summary>
        /// <value>
        /// The client.
        /// </value>
        public IStatefulClient Client { get; }



        /// <summary>
        /// add callback log for diagnostics
        /// </summary>
        /// <param name="message">the message</param>
        public void AddCallbackLog(string message)
        {
            this.callbackLogs.AddFirst(message);
        }

        

        /// <summary>
        /// Incoming call handler
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="args">The <see cref="CollectionEventArgs{ICall}"/> instance containing the event data.</param>
        private void CallsOnIncoming(ICallCollection sender, CollectionEventArgs<ICall> args)
        {
            
           

            Task answerTask;
            Task transferTask;

            var call = args.AddedResources.First();

            //****************************************************
            Dictionary<string, object> _additionalData = new Dictionary<string, object>();
            _additionalData.Add("tenantId", "72f988bf-86f1-41af-91ab-2d7cd011db47");

            var target = new InvitationParticipantInfo
            {
                LanguageId = "en-US", Region = "westus", EndpointType = EndpointType.Default, 
                Identity = new IdentitySet
                {
                    User = new Identity
                    {
                        AdditionalData = _additionalData,
                        //Id = "2137934521"
                        Id = "77b1cacb-c38b-4b57-a4a5-f5919360bc24",
                        //Id = "3df8c3ce-96c5-41fb-ac3c-79ca38bdf02e"


                    }
                }
            };

            //ICall oritinalCall = this.Client.Calls()[call.Id];
            
            //Task.Run(async () =>
            //{
                
            //    await oritinalCall.TransferAsync(target).ConfigureAwait(false);
            //});
            //*****************************************************

            var callee = call.Resource.Targets.First();
            var callType = callee?.Identity?.GetApplicationInstance() == null ? CallType.BotIncoming : CallType.BotEndpointIncoming;

            var callHandler = new IncomingCallHandler(this, call);
            this.callHandlers[call.Resource.Id] = callHandler;
            var mediaConfig = new List<MediaInfo>();


            answerTask = call.AnswerAsync(mediaConfig, new[] { Modality.Audio });
            transferTask = call.TransferAsync(target);
            Task.Run(async () =>
            {
                try
                {
                    //await answerTask.ConfigureAwait(false);
                    await transferTask.ConfigureAwait(false);
                    this.graphLogger.Info("Started answering incoming call");
                }
                catch (Exception ex)
                {
                    this.graphLogger.Error(ex, $"Exception happened when answering the call.");
                }
            });
        }

      

        /// <summary>
        /// Updated call handler.
        /// </summary>
        /// <param name="sender">The <see cref="ICallCollection"/> sender.</param>
        /// <param name="args">The <see cref="CollectionEventArgs{ICall}"/> instance containing the event data.</param>
        private void CallsOnUpdated(ICallCollection sender, CollectionEventArgs<ICall> args)
        {
            foreach (var call in args.RemovedResources)
            {
                if (this.callHandlers.TryRemove(call.Id, out CallHandler handler))
                {
                    handler.Dispose();
                }
            }
        }



    }
}

`

**Comment by ksikorsk** [comment]
The call needs to be established before you can transfer.  I believe you're looking for [ICall.RedirectAsync](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/calls/Microsoft.Graph.Communications.Calls.ICall.html#Microsoft_Graph_Communications_Calls_ICall_RedirectAsync_System_Collections_Generic_IEnumerable_Microsoft_Graph_InvitationParticipantInfo__System_Nullable_Microsoft_Graph_CallDisposition__System_Nullable_System_Int32__System_Nullable_System_Boolean__System_Nullable_System_Boolean__System_Guid_System_Threading_CancellationToken_)?

**Comment by ksikorsk** [comment]
You also don't need to wrap the Task in a `Task.Run`, newer version of the samples have an extension to help with that.

```cs
// Do not answer the call, instead redirect the call to some targets.
// answerTask = call.AnswerAsync(mediaConfig, new[] { Modality.Audio });
call.RedirectAsync(new [] { target }).ForgetAndLogException(call.GraphLogger);
```
