### ISSUE TITLE
InviteAsync does not work from a incoming call in local media mode (Apphosted)

### ISSUE THREAD

**Issue by tartaruga2024** [microsoftgraph/microsoft-graph-comms-samples#700]
**Describe the issue**
In appHosted mode Invite a teams user to join a existing call does not work.
However in serviceHosted mode it works just as expected, Teams user get a invitation and can join in to the call. 

Step1 : accept the incoming PSTN call and hearing the pompt.
Step2:  send inviteAsync to a teams user to join to the original call

Issue: Teams user never get the invitation
After 30 Seconds a exception is thrown 

12.02 10:07:46,218 ERROR [          ] [  140] ppHostedMedia.CallHandler: Error on Participants.InviteAsync: Status Code: 0
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 410
Message: Unexpected 'Failed' status for operation 67cbe828-bdb6-4976-b152-efff9d856d04:
addParticipants failed for participant 8:orgid:9ab26d40-230e-4448-b415-8784c5298131. Underlying reason: Client Media Error. DiagCode: 410#301004.@
AdditionalData:
	subcode: 301004

   at Microsoft.Graph.Communications.Client.OperationManager.ValidateOperation(String clientContext, CommsOperation operation)
   at Microsoft.Graph.Communications.Client.OperationManager.<WaitForCompletionAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulParticipantCollection.<InviteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamsMediaAdapterAppHostedMedia.CallHandler.<TransferToAgent>d__1.MoveNext() 

**Code Snippet**
    user = await _identityResolver.ResolveByPatternAsync("sip:maria.berger@test.xy");
                   var identity = ParticipantHelper.CreateFromId(user).Identity;
                   await Call.Participants.InviteAsync(identity, replacesCallID);

**Expected behavior**
The teams user should get the invitation and can join into the call

**Graph SDK (please complete the following information):**
Microsoft.Graph.Communications.Calls   1.2.0.5304
Microsoft.Graph.Communications.Calls.Media  1.2.0.5304

**Call ID**
Provide the list call ids that encountered this issue. Include the time in UTC/GMT when these call have occurred.

**Logs**
12.02 10:07:23,134 INFO  [          ] [  121] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Inviting participants started. 
12.02 10:07:23,148 INFO  [          ] [  121] ent.ICommunicationsClient: Generating client context: 67cbe828-bdb6-4976-b152-efff9d856d04 
12.02 10:07:23,151 INFO  [          ] [  121] ent.ICommunicationsClient: Waiting for completion of operation with id: 67cbe828-bdb6-4976-b152-efff9d856d04 and timeout: 00:00:30 
12.02 10:07:23,168 INFO  [          ] [  121] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Authenticating request for tenant: 0688dcf9-164e-4b85-aa11-cf763e279409 
12.02 10:07:23,171 INFO  [          ] [  121] ent.ICommunicationsClient: AuthenticationProvider: Generating OAuth token. 
12.02 10:07:23,173 INFO  [          ] [  121] ent.ICommunicationsClient: AuthenticationProvider: Generated OAuth token. Expires in 42,7709259966667 minutes. 
12.02 10:07:23,175 INFO  [          ] [  121] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] {
  "$id": "1",
  "participants": [
    {
      "@odata.type": "#microsoft.graph.invitationParticipantInfo",
      "identity": {
        "@odata.type": "#microsoft.graph.identitySet",
        "user": {
          "@odata.type": "#microsoft.graph.identity",
          "id": "9ab26d40-230e-4448-b415-8784c5298131"
        }
      }
    }
  ],
  "clientContext": "67cbe828-bdb6-4976-b152-efff9d856d04"
} 
12.02 10:07:23,287 INFO  [          ] [  142] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168]  
12.02 10:07:23,294 INFO  [          ] [  142] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] {
  "@odata.type": "#microsoft.graph.inviteParticipantsOperation",
  "participants": [
    {
      "@odata.type": "#microsoft.graph.invitationParticipantInfo",
      "identity": {
        "@odata.type": "#microsoft.graph.identitySet",
        "user": {
          "@odata.type": "#microsoft.graph.identity",
          "id": "9ab26d40-230e-4448-b415-8784c5298131",
          "tenantId": "0688dcf9-164e-4b85-aa11-cf763e279409"
        },
        "acsUser": "",
        "spoolUser": "",
        "phone": "",
        "guest": "",
        "encrypted": "",
        "onPremises": "",
        "acsApplicationInstance": "",
        "spoolApplicationInstance": "",
        "applicationInstance": ""
      },
      "participantId": "c3edff46-d206-4fdb-9df5-4201d7bb6558",
      "endpointType": ""
    }
  ],
  "clientContext": "67cbe828-bdb6-4976-b152-efff9d856d04",
  "status": "Running",
  "id": "a6419bf6-1964-4e81-b8cd-bb73be90deaa",
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#inviteParticipantsOperation"
} 
12.02 10:07:23,318 INFO  [          ] [  142] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168]  
12.02 10:07:23,319 INFO  [          ] [  142] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Found Location Header: https://graph.microsoft.com/v1.0/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453/operations/a6419bf6-1964-4e81-b8cd-bb73be90deaa 
12.02 10:07:23,324 INFO  [          ] [  142] ent.ICommunicationsClient: Running status response, operation running asyncronously: 67cbe828-bdb6-4976-b152-efff9d856d04 
12.02 10:07:23,375 DEBUG [          ] [  128] pterAppHostedMediaService: IN: {"@odata.type":"#microsoft.graph.commsNotifications","value":[{"@odata.type":"#microsoft.graph.commsNotification","changeType":"updated","resource":"/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453","resourceUrl":"/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453","resourceData":{"@odata.type":"#microsoft.graph.call","state":"established","mediaState":{"@odata.type":"#microsoft.graph.callMediaState","audio":"active"},"chatInfo":{"@odata.type":"#microsoft.graph.chatInfo","threadId":"19:5552c146-0b2d-4587-9e6d-350c61e62464","messageId":"0"},"meetingCapability":{"@odata.type":"#microsoft.graph.meetingCapability","allowTranslatedCaptions":true,"allowTranslatedTranscriptions":true,"recorderAllowed":["Attendee"]},"meetingProperties":{"@odata.type":"#microsoft.graph.meetingProperties","meetingLabel":"00000000-0000-0000-0000-000000000000","meetingStates":[]},"coOrganizers":[],"callChainId":"e5c04091-c134-4218-8b14-3dcf3dcfa168","replacesContext":"aHR0cHM6Ly9jYy1ldW5vLTA1LXByb2QtYWtzLmNjLnNreXBlLmNvbS9jYy92MS9jYWxsUGFydGljaXBhbnQvMWQxZjgxNmItYjJhYS00MDcyLTljOTQtZDQ4M2EwMjI4NzY3LzEzL2szLzQxNC9yZXBsYWNlbWVudD9ydD05M2Q2MDgxNWY0MzM0NzQ2OTA5ZDEyNGQ4YjUxNTk1ZCZyYz1leUp5ZEd4aWNtTWlPbnNpWlhOcFpDSTZJa2hJSWl3aVpYUnBaQ0k2SWpBMk9EaGtZMlk1TFRFMk5HVXROR0k0TlMxaFlURXhMV05tTnpZelpUSTNPVFF3T1NJc0ltbHdaR2wwWXlJNlptRnNjMlVzSW5CemRDSTZJa1JwY21WamRGSnZkWFJwYm1jaWZTd2ljblJwWkNJNklqUTZLelE1TkRBMU56STNOamN6TlNJc0luSjBjR1p6SWpwN0luTnlkSEJRYjJ4cFkza2lPaUp5WlhGMWFYSmxaQ0lzSW05bVptVnlUbTl1VFd0cFEzSjVjSFJ2VDI1c2VTSTZkSEoxWlN3aVpXNWhZbXhsVUhOMGJrOXdkR2x0YVhwaGRHbHZibk1pT25SeWRXVjlmUSUyNTNEJTI1M0QmaT0xMC02MC0xMy0xMjMmZT02Mzg0MzEwNzE2NzkxMTM5Nzc="}}]} 
12.02 10:07:23,385 INFO  [          ] [  128] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Scenario ID extracted from Scenario-Id is: e5c04091-c134-4218-8b14-3dcf3dcfa168 
12.02 10:07:23,391 INFO  [          ] [  128] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Request ID extracted from X-Microsoft-Skype-Message-ID is: 571f51e8-77ad-41ba-9107-313072c982e5 
12.02 10:07:23,392 INFO  [          ] [  128] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Authenticating inbound request (571f51e8-77ad-41ba-9107-313072c982e5): http://tma-hostedapp.skypelab-onipd.de:4443/graphcallbacks 
12.02 10:07:23,403 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Queue found for resource communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453, current queue size 4 with id communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453 
12.02 10:07:23,407 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] {
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "Updated",
      "resourceUrl": "/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453",
      "resource": "/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "callChainId": "e5c04091-c134-4218-8b14-3dcf3dcfa168",
        "chatInfo": {
          "@odata.type": "#microsoft.graph.chatInfo",
          "messageId": "0",
          "threadId": "19:5552c146-0b2d-4587-9e6d-350c61e62464"
        },
        "mediaState": {
          "@odata.type": "#microsoft.graph.callMediaState",
          "audio": "Active"
        },
        "state": "Established",
        "tenantId": "0688dcf9-164e-4b85-aa11-cf763e279409",
        "meetingCapability": {
          "@odata.type": "#microsoft.graph.meetingCapability",
          "allowTranslatedCaptions": true,
          "allowTranslatedTranscriptions": true,
          "recorderAllowed": [
            "Attendee"
          ]
        },
        "meetingProperties": {
          "@odata.type": "#microsoft.graph.meetingProperties",
          "meetingLabel": "00000000-0000-0000-0000-000000000000",
          "meetingStates": []
        },
        "coOrganizers": [],
        "replacesContext": "(Generic: NvCayOQc)"
      }
    }
  ]
} 
12.02 10:07:23,444 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168]  
12.02 10:07:23,444 DEBUG [          ] [  123] ppHostedMedia.CallHandler: [811f5c00-0e32-48ce-9f27-8d77b9892453] OnUpdated call with State Established 
12.02 10:07:23,447 DEBUG [          ] [  128] ctStringRespondingHandler: Response Code: Accepted 
12.02 10:07:23,447 DEBUG [          ] [  128] ctStringRespondingHandler: Response Body:  
12.02 10:07:25,122 DEBUG [          ] [  143] pterAppHostedMediaService: IN: {"@odata.type":"#microsoft.graph.commsNotifications","value":[{"@odata.type":"#microsoft.graph.commsNotification","changeType":"updated","resource":"/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453","resourceUrl":"/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453","resourceData":{"@odata.type":"#microsoft.graph.call","state":"established","mediaState":{"@odata.type":"#microsoft.graph.callMediaState","audio":"active"},"chatInfo":{"@odata.type":"#microsoft.graph.chatInfo","threadId":"19:5552c146-0b2d-4587-9e6d-350c61e62464","messageId":"0"},"meetingCapability":{"@odata.type":"#microsoft.graph.meetingCapability","allowAnonymousUsersToDialOut":false,"autoAdmittedUsers":"everyoneInCompany","allowAnonymousUsersToStartMeeting":false,"allowTranslatedCaptions":false,"allowTranslatedTranscriptions":false,"entryExitNotificationsEnabled":true,"allowRaiseHands":true,"attendeeRestrictions":"UnRestricted","allowPstnUsersToBypassLobby":false,"lockMeeting":false,"attendeeViewModes":"Default","stagingRoomEnabled":false,"meetingLiveState":{"@odata.type":"#microsoft.graph.stagingRoomLiveState","phase":"staging","seqNum":0},"cartEnabled":false,"refreshCartKey":false,"breakoutRoomsEnabled":false,"watermarkProtection":{"@odata.type":"#microsoft.graph.watermarkProtectionValues","isEnabledForContentSharing":false,"isEnabledForVideo":false},"recorderAllowed":["Organizers","Presenters"],"copilotMode":"enabledWithTranscript"},"meetingProperties":{"@odata.type":"#microsoft.graph.meetingProperties","meetingLiveState":{"@odata.type":"#microsoft.graph.stagingRoomLiveState","phase":"staging","seqNum":0},"meetingLabel":"00000000-0000-0000-0000-000000000000","meetingStates":[]},"coOrganizers":[],"callChainId":"e5c04091-c134-4218-8b14-3dcf3dcfa168","recordingConsentDetails":{"@odata.type":"#microsoft.graph.recordingConsentDetails","explicitRecordingConsentEnabled":false,"consentActivelyRequired":false},"replacesContext":"aHR0cHM6Ly9jYy1ldW5vLTA1LXByb2QtYWtzLmNjLnNreXBlLmNvbS9jYy92MS9jYWxsUGFydGljaXBhbnQvMWQxZjgxNmItYjJhYS00MDcyLTljOTQtZDQ4M2EwMjI4NzY3LzEzL2szLzQxNC9yZXBsYWNlbWVudD9ydD05M2Q2MDgxNWY0MzM0NzQ2OTA5ZDEyNGQ4YjUxNTk1ZCZyYz1leUp5ZEd4aWNtTWlPbnNpWlhOcFpDSTZJa2hJSWl3aVpYUnBaQ0k2SWpBMk9EaGtZMlk1TFRFMk5HVXROR0k0TlMxaFlURXhMV05tTnpZelpUSTNPVFF3T1NJc0ltbHdaR2wwWXlJNlptRnNjMlVzSW5CemRDSTZJa1JwY21WamRGSnZkWFJwYm1jaWZTd2ljblJwWkNJNklqUTZLelE1TkRBMU56STNOamN6TlNJc0luSjBjR1p6SWpwN0luTnlkSEJRYjJ4cFkza2lPaUp5WlhGMWFYSmxaQ0lzSW05bVptVnlUbTl1VFd0cFEzSjVjSFJ2VDI1c2VTSTZkSEoxWlN3aVpXNWhZbXhsVUhOMGJrOXdkR2x0YVhwaGRHbHZibk1pT25SeWRXVjlmUSUyNTNEJTI1M0QmaT0xMC02MC0xMy0xMjMmZT02Mzg0MzEwNzE2NzkxMTM5Nzc="}}]} 
12.02 10:07:25,132 INFO  [          ] [  143] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Scenario ID extracted from Scenario-Id is: e5c04091-c134-4218-8b14-3dcf3dcfa168 
12.02 10:07:25,133 INFO  [          ] [  143] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Request ID extracted from X-Microsoft-Skype-Message-ID is: b1d6f34e-9d50-42b0-8539-048ebe4f5219 
12.02 10:07:25,133 INFO  [          ] [  143] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Authenticating inbound request (b1d6f34e-9d50-42b0-8539-048ebe4f5219): http://tma-hostedapp.skypelab-onipd.de:4443/graphcallbacks 
12.02 10:07:25,231 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Queue found for resource communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453, current queue size 4 with id communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453 
12.02 10:07:25,246 DEBUG [          ] [  139] ppHostedMedia.CallHandler: [811f5c00-0e32-48ce-9f27-8d77b9892453] OnUpdated call with State Established 
12.02 10:07:25,248 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] {
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "Updated",
      "resourceUrl": "/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453",
      "resource": "/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "callChainId": "e5c04091-c134-4218-8b14-3dcf3dcfa168",
        "chatInfo": {
          "@odata.type": "#microsoft.graph.chatInfo",
          "messageId": "0",
          "threadId": "19:5552c146-0b2d-4587-9e6d-350c61e62464"
        },
        "mediaState": {
          "@odata.type": "#microsoft.graph.callMediaState",
          "audio": "Active"
        },
        "state": "Established",
        "tenantId": "0688dcf9-164e-4b85-aa11-cf763e279409",
        "meetingCapability": {
          "@odata.type": "#microsoft.graph.meetingCapability",
          "allowAnonymousUsersToDialOut": false,
          "autoAdmittedUsers": "everyoneInCompany",
          "allowAnonymousUsersToStartMeeting": false,
          "allowTranslatedCaptions": false,
          "allowTranslatedTranscriptions": false,
          "entryExitNotificationsEnabled": true,
          "allowRaiseHands": true,
          "attendeeRestrictions": "UnRestricted",
          "allowPstnUsersToBypassLobby": false,
          "lockMeeting": false,
          "attendeeViewModes": "Default",
          "stagingRoomEnabled": false,
          "meetingLiveState": {
            "@odata.type": "#microsoft.graph.stagingRoomLiveState",
            "phase": "staging",
            "seqNum": 0
          },
          "cartEnabled": false,
          "refreshCartKey": false,
          "breakoutRoomsEnabled": false,
          "watermarkProtection": {
            "@odata.type": "#microsoft.graph.watermarkProtectionValues",
            "isEnabledForContentSharing": false,
            "isEnabledForVideo": false
          },
          "recorderAllowed": [
            "Organizers",
            "Presenters"
          ],
          "copilotMode": "enabledWithTranscript"
        },
        "meetingProperties": {
          "@odata.type": "#microsoft.graph.meetingProperties",
          "meetingLiveState": {
            "@odata.type": "#microsoft.graph.stagingRoomLiveState",
            "phase": "staging",
            "seqNum": 0
          },
          "meetingLabel": "00000000-0000-0000-0000-000000000000",
          "meetingStates": []
        },
        "coOrganizers": [],
        "recordingConsentDetails": {
          "@odata.type": "#microsoft.graph.recordingConsentDetails",
          "explicitRecordingConsentEnabled": false,
          "consentActivelyRequired": false
        },
        "replacesContext": "(Generic: NvCayOQc)"
      }
    }
  ]
} 
12.02 10:07:25,310 INFO  [          ] [  122] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168]  
12.02 10:07:46,179 DEBUG [          ] [  123] pterAppHostedMediaService: IN: {"@odata.type":"#microsoft.graph.commsNotifications","value":[{"@odata.type":"#microsoft.graph.commsNotification","changeType":"deleted","resource":"/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453/operations/a6419bf6-1964-4e81-b8cd-bb73be90deaa","resourceUrl":"/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453/operations/a6419bf6-1964-4e81-b8cd-bb73be90deaa","resourceData":{"@odata.type":"#microsoft.graph.inviteParticipantsOperation","participants":[{"@odata.type":"#microsoft.graph.invitationParticipantInfo","identity":{"@odata.type":"#microsoft.graph.identitySet","user":{"@odata.type":"#microsoft.graph.identity","id":"9ab26d40-230e-4448-b415-8784c5298131","tenantId":"0688dcf9-164e-4b85-aa11-cf763e279409"}},"participantId":"c3edff46-d206-4fdb-9df5-4201d7bb6558"}],"status":"failed","clientContext":"67cbe828-bdb6-4976-b152-efff9d856d04","resultInfo":{"@odata.type":"#microsoft.graph.resultInfo","code":410,"subcode":301004,"message":"addParticipants failed for participant 8:orgid:9ab26d40-230e-4448-b415-8784c5298131. Underlying reason: Client Media Error. DiagCode: 410#301004.@"},"id":"a6419bf6-1964-4e81-b8cd-bb73be90deaa"}}]} 
12.02 10:07:46,183 INFO  [          ] [  123] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Scenario ID extracted from Scenario-Id is: e5c04091-c134-4218-8b14-3dcf3dcfa168 
12.02 10:07:46,184 INFO  [          ] [  123] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Request ID extracted from X-Microsoft-Skype-Message-ID is: 4895722e-cb43-4313-9766-b4460e481614 
12.02 10:07:46,185 INFO  [          ] [  123] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Authenticating inbound request (4895722e-cb43-4313-9766-b4460e481614): http://tma-hostedapp.skypelab-onipd.de:4443/graphcallbacks 
12.02 10:07:46,201 INFO  [          ] [  140] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Processing operation notification with id: a6419bf6-1964-4e81-b8cd-bb73be90deaa 
12.02 10:07:46,204 INFO  [          ] [  140] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] Completing operation with id: a6419bf6-1964-4e81-b8cd-bb73be90deaa and change type Deleted 
12.02 10:07:46,218 ERROR [          ] [  140] ppHostedMedia.CallHandler: Error on Participants.InviteAsync: Status Code: 0
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 410
Message: Unexpected 'Failed' status for operation 67cbe828-bdb6-4976-b152-efff9d856d04:
addParticipants failed for participant 8:orgid:9ab26d40-230e-4448-b415-8784c5298131. Underlying reason: Client Media Error. DiagCode: 410#301004.@
AdditionalData:
	subcode: 301004

   at Microsoft.Graph.Communications.Client.OperationManager.ValidateOperation(String clientContext, CommsOperation operation)
   at Microsoft.Graph.Communications.Client.OperationManager.<WaitForCompletionAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulParticipantCollection.<InviteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TeamsMediaAdapterAppHostedMedia.CallHandler.<TransferToAgent>d__1.MoveNext() 
12.02 10:07:46,239 WARN  [          ] [  140] ppHostedMedia.CallHandler: Timeout set in request: 25, ignored since transfereToAgent doesnt support custom timeout! 
12.02 10:07:46,239 DEBUG [          ] [  140] ppHostedMedia.CallHandler: Waiting 60 seconds for agent! 
12.02 10:07:46,247 INFO  [          ] [  140] ent.ICommunicationsClient: [e5c04091-c134-4218-8b14-3dcf3dcfa168] {
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "Deleted",
      "resourceUrl": "/communications/calls/811f5c00-0e32-48ce-9f27-8d77b9892453/operations/a6419bf6-1964-4e81-b8cd-bb73be90deaa",
      "resource": "/app/calls/811f5c00-0e32-48ce-9f27-8d77b9892453/operations/a6419bf6-1964-4e81-b8cd-bb73be90deaa",
      "resourceData": {
        "@odata.type": "#microsoft.graph.inviteParticipantsOperation",
        "participants": [
          {
            "@odata.type": "#microsoft.graph.invitationParticipantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "user": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "9ab26d40-230e-4448-b415-8784c5298131",
                "tenantId": "0688dcf9-164e-4b85-aa11-cf763e279409"
              }
            },
            "participantId": "c3edff46-d206-4fdb-9df5-4201d7bb6558"
          }
        ],
        "clientContext": "67cbe828-bdb6-4976-b152-efff9d856d04",
        "resultInfo": {
          "@odata.type": "#microsoft.graph.resultInfo",
          "code": 410,
          "message": "addParticipants failed for participant 8:orgid:9ab26d40-230e-4448-b415-8784c5298131. Underlying reason: Client Media Error. DiagCode: 410#301004.@",
          "subcode": 301004
        },
        "status": "Failed",
        "id": "a6419bf6-1964-4e81-b8cd-bb73be90deaa"
      }
    }
  ]
} 

**Additional context**

**Comment by ssulzer** [comment]
@tartaruga2024 
Where is your application-hosted media bot hosted? Is it in Azure and does it have a public IP address?
The call involving your appHosted media bot is failing because the IP address of the bot is not accessible/reachable from the Teams meeting server (running in Azure). Specifically, the IPAddress given for MediaPlatformInstanceSettings.InstancePublicIPAddress is not reachable.

**Comment by tartaruga2024** [comment]
@ssulzer 
we solved that issue by modifying the firewall port forwarding.

thanks
