### ISSUE TITLE
MediaAPINotInitialized Error

### ISSUE THREAD

**Issue by Javeria-Arif** [microsoftgraph/microsoft-graph-comms-samples#705]
Hi All,

I have followed all the steps in the PSI Bot service guide to add the PSI bot in my MS Teams call.

Now when I am joining the Teams call as a bot using Teams URL, the code is throwing "MediaAPINotInitialized Error". I am not sure why is this error being thrown? Can anyone guide on this?

![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/57355046/28358704-05b3-4c94-9248-d644f24dbcd7)
![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/57355046/488de054-59a2-4cfd-bbe0-49ac1decded2)

**Comment by InDieTasten** [comment]
You should check the output of the logger. I assume there will be more details for why the media api is not initialized. Also post the full stacktrace.

**Comment by Javeria-Arif** [comment]
@InDieTasten  One more thing that I found out, is when I start the application and run xx.ngrok-free.app/manage the code throws an exception in the BotService.cs class on this line "builder.SetMediaPlatformSettings(botConfiguration.MediaPlatformSettings);
".
The error is:
![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/57355046/c530ba13-2f8c-45b0-925c-6af28baa40f3)
![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/57355046/2b65da28-f85e-485a-ac15-8890124de135)


Uploading the stack trace for the previous error as well:

![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/57355046/3c38451d-02de-45b5-ac7e-49f98fa78ccf)

**Comment by vigbav36** [comment]
Hey , instead of using the instructions in read me for generating certificate , use Posh Acme

https://poshac.me/docs/v4/Tutorial/

And then install the certificate in local machine , re run it and it should work

**Comment by Javeria-Arif** [comment]
Thank you all. I have resolved this particular issue. I created a new RSA certificate which is supported by the media platform.
