### ISSUE TITLE
Send text response from the PSI bot to the online meeting

### ISSUE THREAD

**Issue by Javeria-Arif** [microsoftgraph/microsoft-graph-comms-samples#711]
Hi all,

I want to send some live text responses continuously from my PSI bot to the online meeting in real-time. Any leads to in which class is the text implementation handled?

**Comment by InDieTasten** [comment]
Are you talking about sending messages into the chat of the online meeting?

**Comment by Javeria-Arif** [comment]
Yes

**Comment by InDieTasten** [comment]
Then you wanna take a look at https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=csharp#examples
This repo is more related to the Graph Communications Calling SDK and I don't believe any of the samples are implementing messaging for channels or chats. Those are just part of regular Graph APIs and don't require a special SDK.

You will find the examples have tabs for selecting the protocol / language you wish to use the API with, which is pretty extensive compared to the app hosted media calling scenarios, which really only work on Windows using dotnet 6 or .NET Framework.
![image](https://github.com/microsoftgraph/microsoft-graph-comms-samples/assets/7047377/87a764f9-99a6-415b-b6a2-1977106fcbc9)

**Comment by Javeria-Arif** [comment]
@InDieTasten  Alright, I'll take a look into this. Thanks for the help.
