### ISSUE TITLE
Unable to debug locally- Is need the SSL certificate for local debug ?

### ISSUE THREAD

**Issue by subbiah46** [microsoftgraph/microsoft-graph-comms-samples#74]
We are trying to run the solution locally but we can't achieve this. 

We faced the below error.
![Issue](https://user-images.githubusercontent.com/49874047/58781459-88347180-85f9-11e9-8060-4e5454bbd83b.PNG)

**Comment by ksikorsk** [comment]
Which sample are you trying to run locally?  It looks like AV playback bot.  If that is the case you need to ensure that the start up project is the ccproj.

**Comment by ksikorsk** [comment]
Please keep in mind that while you can get the AV playback bot to work locally, it is not by default configured to run this way.  Some code changes are required.  The only guidance we provide for local runs of samples can be found [here](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot) and [here](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Testing.html).

**Comment by subbiah46** [comment]
We hosted the  AV playbackbot in azure cloud service and got the site URL as "http://test54321.cloudapp.net/". The next step is create the wildcard  certificate for our service. We confused for which domain we need to create the certificate. Shall we create a certificate for "*.Cloudapp.net" ?. If yes we can't get the no self signed certificate from the CA authority

**Comment by vinaychandra** [comment]
If you are hosting in Azure Cloud Service, you do not need a wildcard certificate and do not need to follow the guidance for a "local run". Local runs are only meant for testing on dev boxes and not in Azure.
Also, you cannot get a certificate for `*.cloudapp.net` because that domain is not owned by you. The easiest way would be to create a `CNAME` entry in your custom domain and point it to the azure cloudapp entry.

**Comment by subbiah46** [comment]
We follow the azure deployment steps "https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot/README.md". Here they mention to create the wildcard certificate. 
![image](https://user-images.githubusercontent.com/49874047/59012196-83b7c500-8854-11e9-9330-cf2bba72523d.png)

**Comment by vinaychandra** [comment]
I stand corrected. You can create the certificate for your custom domain that is pointed to your cloudapp.net site.

**Comment by ksikorsk** [comment]
Is there more guidance needed here, or can I close the issue?

**Comment by saraswat40** [comment]
@subbiah46  were you able to get this working. Can you please get in touch with me at saraswat40 at gmail. Thanks
