### ISSUE TITLE
Call status terminated , Error 500#3002 Internal server error

### ISSUE THREAD

**Issue by abhi161** [microsoftgraph/microsoft-graph-comms-samples#744]
I'm having a weird issue where my bot was working perfectly fine, and then suddenly started throwing an error. I haven't changed any settings or code, so I'm completely baffled.

Is this a bug, or is there something else going on? Any help would be greatly appreciated!

Call status updated to Terminated - Server Internal Error. DiagCode: 500#3002.@"

**Comment by abhi161** [comment]
@InDieTasten   
Thanks for sharing..

I'm using a wildcard certificate and have been developing my bot locally for a while now. Today, after closing and restarting it (2mins), the bot failed to appear in Teams. I'm seeing this error in my logs:

**Comment by InDieTasten** [comment]
@abhi161 Every certificate expires at some point. Perhaps the wildcard certificate you've been using expired at exactly that moment?

**Comment by abhi161** [comment]
@InDieTasten 

Actually I checked already the expiry is after 27th Dec 24.

**Comment by ak0037** [comment]
@InDieTasten  i tried using another certificate but some error

**Comment by abhi161** [comment]
@InDieTasten I tried with another certificate but error persist. Also checked firewall,  updated ports , checked thumbprint mismatch, connections all seems good.

Will really appreciate any help

**Comment by 1fabi0** [comment]
@abhi161 did you check #729, so your wildcard certificate is valid for your domain. E.g. a certificate for *.example.com would not be valid for bot.test.example.com

**Comment by abhi161** [comment]
![image](https://github.com/user-attachments/assets/2ae25a19-6219-4987-91cc-8f1ba18dbbda)

**Comment by abhi161** [comment]
probably this is the cause

**Comment by abhi161** [comment]
working fine now
