### ISSUE TITLE
Documentation: link to testing guide is broken

### ISSUE THREAD

**Issue by Robbos** [microsoftgraph/microsoft-graph-comms-samples#76]
**Describe the issue**
In the [following README](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples), the link to the Local Testing Guide returns a 404 not found.

**Code Snippet**
`To run your bot locally you will need to configure a local proxy.  [ngrok](https://ngrok.com/) is a great service that allows local proxy of both http (signalling) and tcp (media) traffic.  For more information please reference our [Local Testing Guide](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/testing.html)`

**Expected behavior**
The link needs to be adjusted to point to "Testing.html" with uppercase T. This fixes the 404 not found.
`To run your bot locally you will need to configure a local proxy.  [ngrok](https://ngrok.com/) is a great service that allows local proxy of both http (signalling) and tcp (media) traffic.  For more information please reference our [Local Testing Guide](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Testing.html)`

**Comment by ksikorsk** [comment]
fixed:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/pull/80
