### ISSUE TITLE
Not receiving a changeType deleted notification when a meeting ends

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#77]
**Describe the issue**
We have a bot which joins a Microsoft Teams meeting via the meeting URL. On a one on one call if the organizer hangs up, we get a notification of changeType 'deleted'. However, if this is an online meeting and the organizer ends the call, we only get a changeType 'updated' notification with a list of participants. We do get a changeType 'deleted' notification if the bot is removed from the call ( via remove participant )

**Expected behavior**
We should get a changeType 'deleted' notification when the online meeting ends.

**Graph SDK (please complete the following information):**
beta

**Call ID**
call id: 451f0a00-ea04-4c8f-90d8-cddf1ac603d5
call terminated: 2019-06-04 17:37:46 UTC

**Logs**
"@odata.type": "#microsoft.graph.commsNotifications",
	"value": [
		{
			"@odata.type": "#microsoft.graph.commsNotification",
			"changeType": "updated",
			"resource": "/app/calls/451f0a00-ea04-4c8f-90d8-cddf1ac603d5/participants",
			"resourceData": [
				{
					"@odata.type": "#microsoft.graph.participant",
					"info": {
						"@odata.type": "#microsoft.graph.participantInfo",
						"identity": {
							"@odata.type": "#microsoft.graph.identitySet",
							"application": {
								"@odata.type": "#microsoft.graph.identity",
								"id": "xxxx",
								"tenantId": null,
								"identityProvider": "AAD"
							}
						}
					},
					"mediaStreams": [
						{
							"@odata.type": "#microsoft.graph.mediaStream",
							"mediaType": "audio",
							"sourceId": "19",
							"direction": "sendReceive",
							"serverMuted": false
						}
					],
					"isMuted": false,
					"isInLobby": false,
					"id": "ca727bd4-cfa9-4db5-a296-c0fe1251512c"
				}
			]
		}
	]
}
**Additional context**

**Comment by ksikorsk** [comment]
For a multiparty call, the call does not end while the bot is still in the meeting.  The bot needs to detect that they are the only participant, or the only "human" participant, and leave the meeting on it's own accord.

You can do this using the DELETE /app/calls/{id} API which would trigger the `"changeType": "deleted"` notification.

**Comment by saraswat40** [comment]
Got it. Thanks
