### ISSUE TITLE
Can Echobot be implemented in Java, MacOS?

### ISSUE THREAD

**Issue by jade0520** [microsoftgraph/microsoft-graph-comms-samples#773]
Hello, 
Thank you for sharing this great project.

I am trying to run the Echobot example on my MacBook, and I have two questions, so I wanted to raise an issue.

1.  Is it possible to develop this project in Java?
- I noticed a similar issue(https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/459#issue-908941883
) was raised before, but it has been some time since then, so I was wondering if it is possible now.

2. Can this project be developed on Mac?
- Similarly, in the previous issue(https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/459#issue-908941883), it was mentioned that it is not possible, but I am aware that DSC 3.0 is now available. Is it currently possible to run this on a MacBook?

Thank you in advance for your help.

**Comment by InDieTasten** [comment]
Not possible at the moment. There are still dependencies on `Microsoft.Skype.Bots.Media`, which rely on Windows.

Now whether you can interop with Java into dotnet packages, I don't know. But you will definitely require Windows.
