### ISSUE TITLE
Why Echo bot needs two apps?

### ISSUE THREAD

**Issue by jade0520** [microsoftgraph/microsoft-graph-comms-samples#778]
I'm currently working on building an Echobot following the instructions (https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/PublicSamples/EchoBot).
 
According to the instructions, "Bot Registration" step should be completed before deploying. However, after deploying I noticed another app called  "GH_Echobot_**_BOT". **What is different between these two bots? and which one should I use when the deploying script asks for "Azure Bot ADD Client ID"?**

Initially, I entered the information for the app I manually created during the "Bot Registration" step. But when I ran 'Action' following an error occurred, and I suspect the issue might be due to using the wrong app.
![image](https://github.com/user-attachments/assets/f96e1ec4-30e2-4ac3-8b83-f33896cd9ac5)

**Comment by InDieTasten** [comment]
I'm not familiar with the Echobot deployment scripts, but I suspect the following:

One app registration is used as identity for the bot to communicate with Graph and to perform it's actions during operation.

The other app registration serves as service principal to deploy infrastructure and code changes to Azure. It needs to have permissions to perform those tasks.

It's common to split those two aspects.

**Comment by jade0520** [comment]
Thank you for explanation! I put an app registration one when I deploy and it worked smoothly!
