### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by kkabza** [microsoftgraph/microsoft-graph-comms-samples#79]
It looks like there are some images missing in the documentation on deploying HueBot  https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot

I see image place holders but the images are not found on blob storage.

**Comment by ksikorsk** [comment]
Fixed by @RobRoseKnows... kudos!
https://github.com/microsoftgraph/microsoft-graph-comms-samples/pull/78
