### ISSUE TITLE
Error while trying to publish the audio video bot sample

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#81]
I am trying to publish the AudioVideo sample as described here: https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot

I am on Deploy, Step 4 but I get the following error:
Error	CS0234	The type or namespace name 'Common' does not exist in the namespace 'Sample' (are you missing an assembly reference?)	FrontEnd	C:\Users\admin\source\repos\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Bot\Bot.cs	23	Active

I don't have a background in c# development and I don't know how to troubleshoot this. Please help.

**Comment by saraswat40** [comment]
Most of my problems were related to Windows 7. Once I moved to Windows 10. The solution is published successfully to Azure Cloud Service. For some reason the cloud service is not reachable. I don't know why (yet).

**Comment by saraswat40** [comment]
I am able to send a POST request to my application at the joinCall endpoint, but consistently get this error:
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000215: Invalid client secret is provided.

We have regenerated/rebuilt/republished the build several times but not able to get past this issue.

**Comment by ksikorsk** [comment]
Did you put a break point to ensure that the client secret is as expected?  Depending on the sample you may have to "escape" your secret just so it is stored/read correctly.

**Comment by saraswat40** [comment]
Yes, this one gets deployed in Azure and runs in Azure so I'm not sure if the client secret is as expected. But we are aware of issues with '+' and '/' characters in the secret and I tried with secrets without those characters.

**Comment by ksikorsk** [comment]
I expect that the error is accurate, and the secret is getting somehow adjusted.  You can attach your debugger to the Azure deployed code (you have to publish a `Debug` build so that breakpoints are accurate).  Alternatively you can run locally if you have that set up.

If neither of the above work for you, try some online xml encoder and save the encoded secret within the config file.

**Comment by saraswat40** [comment]
I generated another secret last night without the '+' and '/' characters and it didn't seem to have done anything. But as of few hours ago, I no longer get this error. I get a call Id in response as expected. Now I am trying to change the role to viewer I get this error:
Status Code: NotFound
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
Status Code: NotFound
Scenario Id: 0c7e8c37-0700-43a0-a340-af4bad280830
 ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.
Status Code: NotFound

   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCall.<ChangeScreenSharingRoleAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.AudioVideoPlaybackBot.FrontEnd.Bot.Bot.<ChangeSharingRoleAsync>d__23.MoveNext() in C:\temp2\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Bot\Bot.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.AudioVideoPlaybackBot.FrontEnd.Http.ChangeScreenSharingRoleController.<ChangeScreenSharingRoleAsync>d__0.MoveNext() in C:\temp2\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Http\Controllers\ChangeScreenSharingRoleController.cs:line 47

**Comment by ksikorsk** [comment]
Can you provide a full (with redacted personal information) http trace of the request?  You should be able to get the logs using `https://service.com/logs/0c7e8c37-0700-43a0-a340-af4bad280830` endpoint.

**Comment by saraswat40** [comment]
Another problem is that even though joinCall returns a callid, the bot is not in the call. I don't see another participant in the participants view either. I will post the logs shortly.

**Comment by ksikorsk** [comment]
The error is that you are trying to change screen sharing role for a call that does not exist:

[LogProtocolMessage,LoggingMessageHandler.cs(374) 9df204c3-5f5b-48f1-9429-5f5c6f845cfa 1438098] || activityid=9df204c3-5f5b-48f1-9429-5f5c6f845cfa || ltid=1438098 || msgid= || request.msgid=125ce2c1-2a40-4b02-afe8-5b16e632df61 || statuscode=NotFound || fid= || local.msgid=6350b0fc-0fae-4208-9881-79c8e7a3aa98 ||
Response to incoming:: POST /app/calls/431f0500-0d6d-47c7-b2f2-e58f3c860149/Microsoft.Graph.changeScreenSharingRole
404 Not Found
Client-Request-ID: 125ce2c1-2a40-4b02-afe8-5b16e632df61
Scenario-ID: 0c7e8c37-0700-43a0-a340-af4bad280830
X-Microsoft-Skype-Chain-ID: 9df204c3-5f5b-48f1-9429-5f5c6f845cfa
OData-Version: 4.0
Date: Tue, 18 Jun 2019 17:50:13 GMT
Server: Microsoft-HTTPAPI/2.0
Content-Length: 53
Content-Type: application/json; odata.metadata=minimal
{
  "error": {
    "code": "9997",
    "message": "Call not found."
  }
}

**Comment by saraswat40** [comment]
Here are the logs:
$>2019-06-18T19:34:30.8224571Z Info: LoggingMessageHandler.cs:167 SendAsync
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 230
request: POST https://audiovideo.cloudapp.net/calls/441f0500-4361-4a26-8722-65fb3c1b7b3a/changeRole
response: 404 NotFound
headers:
  Transfer-Encoding: chunked
  request-id: 603a0aaa-b699-4add-ac3d-8fca3d85870b
  client-request-id: a7664838-d4b5-4447-8683-6e17de118757
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"SliceC","Ring":"4","ScaleUnit":"000","RoleInstance":"AGSFE_IN_4","ADSiteName":"WUS2"}}
  scenario-id: 370a43a2-fa21-4f28-8a8a-cd6fe6b46e0e
  Duration: 213.2369
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Tue, 18 Jun 2019 19:34:30 GMT
  Content-Type: text/plain; charset=utf-8
$>2019-06-18T19:34:30.8224571Z Error: GraphAuthClient.cs:114 SendHttpRequestAsync
ScenarioId: 370a43a2-fa21-4f28-8a8a-cd6fe6b46e0e
AppId: b22ad71e-224e-48b2-a1e0-15d2a20dadcf
AppName: AudioVideoPlaybackBot
CallId: 441f0500-4361-4a26-8722-65fb3c1b7b3a
TenantId: xxxxxxx
TransactionDirection: Outgoing
TraceType: HttpResponse
ResponseTime: 226
request: POST https://graph.microsoft.com/beta/app/calls/441f0500-4361-4a26-8722-65fb3c1b7b3a/microsoft.graph.changeScreenSharingRole
response: 404 NotFound
headers:
  Transfer-Encoding: chunked
  request-id: 603a0aaa-b699-4add-ac3d-8fca3d85870b
  client-request-id: a7664838-d4b5-4447-8683-6e17de118757
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"SliceC","Ring":"4","ScaleUnit":"000","RoleInstance":"AGSFE_IN_4","ADSiteName":"WUS2"}}
  scenario-id: 370a43a2-fa21-4f28-8a8a-cd6fe6b46e0e
  Duration: 213.2369
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Tue, 18 Jun 2019 19:34:30 GMT
  Content-Type: application/json
{
  "error": {
    "code": "generalException",
    "message": "Unexpected exception returned from the service.\r\nStatus Code: NotFound"
  },
  "responseHeaders": [
    {
      "key": "Transfer-Encoding",
      "value": [
        "chunked"
      ]
    },
    {
      "key": "request-id",
      "value": [
        "603a0aaa-b699-4add-ac3d-8fca3d85870b"
      ]
    },
    {
      "key": "client-request-id",
      "value": [
        "a7664838-d4b5-4447-8683-6e17de118757"
      ]
    },
    {
      "key": "x-ms-ags-diagnostic",
      "value": [
        "{\"ServerInfo\":{\"DataCenter\":\"West US 2\",\"Slice\":\"SliceC\",\"Ring\":\"4\",\"ScaleUnit\":\"000\",\"RoleInstance\":\"AGSFE_IN_4\",\"ADSiteName\":\"WUS2\"}}"
      ]
    },
    {
      "key": "scenario-id",
      "value": [
        "370a43a2-fa21-4f28-8a8a-cd6fe6b46e0e"
      ]
    },
    {
      "key": "Duration",
      "value": [
        "213.2369"
      ]
    },
    {
      "key": "Strict-Transport-Security",
      "value": [
        "max-age=31536000"
      ]
    },
    {
      "key": "Cache-Control",
      "value": [
        "private"
      ]
    },
    {
      "key": "Date",
      "value": [
        "Tue, 18 Jun 2019 19:34:30 GMT"
      ]
    }
  ],
  "statusCode": 404,
  "message": "Code: generalException\r\nMessage: Unexpected exception returned from the service.\r\nStatus Code: NotFound\r\n",
  "data": {},
  "targetSite": {
    "Name": "MoveNext",
    "AssemblyName": "Microsoft.Graph.Communications.Client, Version=1.1.0.581, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
    "ClassName": "Microsoft.Graph.Communications.Client.Transport.GraphAuthClient+<ValidateResponseAsync>d__5",
    "Signature": "Void MoveNext()",
    "Signature2": "System.Void MoveNext()",
    "MemberType": 8,
    "GenericArguments": null
  },
  "stackTrace": "   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()",
  "source": "Microsoft.Graph.Communications.Client",
  "hResult": -2146233088
}

**Comment by saraswat40** [comment]
Yes, I thought since the call was from yesterday I should try to create a new meeting and a new call. The logs above are from the new call I just created.

**Comment by ksikorsk** [comment]
Have you created a call first?  Do you have the logs for the call creation?

**Comment by ksikorsk** [comment]
Looks like our service cannot reach your bot:

```http
Request
POST https://audiovideo.cloudapp.net:10100/api/calling HTTP/1.1
Authorization: (redacted)
X-Microsoft-Skype-Chain-ID: adfd1055-8701-4fdd-9c09-cea0bf0c6c7b
Scenario-ID: 370a43a2-fa21-4f28-8a8a-cd6fe6b46e0e
Accept: application/json
User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
X-Microsoft-Skype-Message-ID: c7984298-b3a4-4a61-8fef-c86d65cca91d
Content-Type: application/json; charset=utf-8
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "updated",
      "resource": "/app/calls/441f0500-4361-4a26-8722-65fb3c1b7b3a",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "establishing",
        "chatInfo": {
          "@odata.type": "#microsoft.graph.chatInfo",
          "threadId": "19:meeting_MjIyNWQzNTEtNGM2Zi00MjhjLTkwMmUtNzExMGQ0YzZjMjg4@thread.v2",
          "messageId": "0"
        },
        "meetingInfo": "(redacted)"
      }
    }
  ]
}
```

```http
Response
<no response>
```

**Comment by ksikorsk** [comment]
Cannot establish media either... and so call is terminated.  There may be something wrong with your bot deployment.

```http
Request
HTTP/1.1 500
X-Microsoft-Skype-Processing-Instance: Microsoft.Skype.MediaController.FrontEnd_IN_4
X-Microsoft-Skype-Message-ID: 6f1580e3-8a9c-4afe-8822-bb4bd0acf5b0
X-Microsoft-Skype-Chain-ID: adfd1055-8701-4fdd-9c09-cea0bf0c6c7b
X-Microsoft-Skype-Proxy-Instance: Microsoft.Skype.MediaController.FrontEnd_IN_9
Date: Tue, 18 Jun 2019 19:31:03 GMT
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
Content-Length: 209
Content-Type: application/json; charset=utf-8
{
  "addParticipantResponse": null,
  "debugContent": {
    "correlationId": "adfd1055-8701-4fdd-9c09-cea0bf0c6c7b"
  },
  "reason": "MP resources creation failure",
  "mpUri": "net.tcp://audiovideo.cloudapp.net:20100/MediaProcessor"
}
```

**Comment by saraswat40** [comment]
The bot deployment is handled by visual studio and visual studio doesn't show any errors. We didn't change the source code or any configuration files except those mentioned in the readme. Also port 443 is reachable. I'm not sure how to troubleshoot this.

**Comment by ksikorsk** [comment]
Go to azure... make sure your application is running and no errors are reported.  Ensure that the URI matches that of your configuration.

![image](https://user-images.githubusercontent.com/1817749/59719212-e52f4a80-91e9-11e9-8d2e-caad845985e2.png)

![image](https://user-images.githubusercontent.com/1817749/59719265-fed09200-91e9-11e9-87bd-26d9fe03d53a.png)

**Comment by ksikorsk** [comment]
Looks like your SSL cert is invalid:
![image](https://user-images.githubusercontent.com/1817749/59719452-5ec73880-91ea-11e9-992f-925aa1c7b020.png)

**Comment by saraswat40** [comment]
The diagnose and solve problems link didn't help. We are using a self signed certificate because we have not been able to generate a signed certificate. Before the solution is deployed, we don't have the machine running on that domain name so it is difficult to get the certificate signed by the CA. After the solution is deployed, I have tried to enable IIS but for some reason the IIS is not accessible from an external IP address even with windows firewall disabled.

**Comment by ksikorsk** [comment]
Generally clients have their own domain, add a CName entry to resolve the *.cloudapp.net domain, and create an SSL cert for their own domain.  I've even heard of cases where the cert was managed by [Let's Encrypt](https://letsencrypt.org/).  I'm not sure why you need to access IIS to create a cert signed by CA.

> 1. Create a cloud service (classic) in Azure. Get your "Site URL" from Azure portal, this will be your DNS name and CN name for later configuration, for example: bot.contoso.com.
> 1. Set up SSL certificate and upload to the cloud service
>     1. Create a wildcard certificate for your service. **This certificate should not be a self-signed certificate.** For instance, if your bot is hosted at bot.contoso.com, create the certificate for *.contoso.com.
>     1. Upload the certificate to the cloud service.
>     1. Copy the thumbprint for later.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot/README.md

**Comment by saraswat40** [comment]
Thanks for your help with this. I got the sample to work after creating my own domain and a signed SSL.
