### ISSUE TITLE
What is the full cluter name for local deployment of Huebot?

### ISSUE THREAD

**Issue by RobRoseKnows** [microsoftgraph/microsoft-graph-comms-samples#82]
Hi, I'm having some trouble understanding the documentation on HueBot. In the `appsettings.json` it asks for a "BotBaseUrl". In [the documentation](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/HueBot) it says to replace the URL with your full cluster name. I'm confused however as to what the full cluster name is for a local run of HueBot. Is it necessary to fill out that field? Should I set it to the ngrok URL?

**Comment by ksikorsk** [comment]
This should be the ngrok url in the case where you are running the sample locally.  It is the url by which your application can be accessed.
