### ISSUE TITLE
Allow bot to blur background in a teams meeting

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#83]
Microsoft teams has a background blur feature: https://support.office.com/en-ie/article/blur-your-background-in-a-teams-meeting-f77a2381-443a-499d-825e-509a140f4780

Is it possible for a bot, which is in the call to blur the background?

**Comment by ksikorsk** [comment]
Yes, if you process the raw video stream.  You'd have to build your own model to blur the background.

https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples

**Comment by saraswat40** [comment]
Blurring the background is not simple. It would be easier if the existing blur control was enabled via an API.

**Comment by ksikorsk** [comment]
Unfortunately that is a client side feature.  Platform allows generic tools to access media, but nothing to transform/transcribe it.  There is no plan that I am aware of to support transformations of the media.

**Comment by ksikorsk** [comment]
@ssulzer is this something you ever plan to add support for?

**Comment by ssulzer** [comment]
We currently have no plan to provide a helper API in the bot media API for blurring (or any other kind of transforms), but it's not something we've considered.

@saraswat40 
What scenario do you want to enable? A bot taking the video from a Teams client, blurring its background, and then substituting the client's video with that transformed video stream for everyone else to see? Or just archive/record the blurred video?

Would your scenario require a bot performing this blurring for multiple clients within a Teams meeting?

**Comment by saraswat40** [comment]
@ssulzer ideally, we want two things. When a user enables the camera on a call, they get an option to blur the background as well. This feature already exists in microsoft teams today. We only want some kind of api call which will allow us to either blur the background automatically or at least get the blur status so that we can prompt the user to blur the background.

**Comment by ssulzer** [comment]
So the bot itself does not want to perform the blurring but instead wants to ensure all the blur-capable Teams clients are enabling their background blurring? e.g., because of a compliance policy? Thanks.

**Comment by saraswat40** [comment]
ideally the bot should be able to perform the blurring.

If and only if this is not possible, the bot should at least be able to detect that the blur is enabled or not.

**Comment by ssulzer** [comment]
So this scenario is not possible or supported by the bot platform. The following capabilities do not exist:

1. A bot cannot tell whether a client has enabled background blur or not. And this may not be just a technical limitation, but also a privacy concern (so would likely require authorization from the tenant). Similarly, a bot cannot command a client to enable their background blur feature.
2. The bot media platform does not provide any kind of blurring transformation helper API; the platform just provides raw access to the video stream.
3. There is no way for a bot to substitute a client's video source with a different (transformed) video source.

This would be a very advanced scenario to try to accomplish with a bot. A better approach might be to support a tenant policy to command all Teams clients to enable their background blurring (possibly only for certain meetings). But this would not work for certain endpoints, such as web clients, so how to handle those would need to be addressed. Thanks.
