### ISSUE TITLE
Bot doesn't receive chat notifications in a call

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#84]
**Describe the issue**
When the bot is part of the call and someone types something in the common chat or shares a file, the bot doesn't get a notification

**Expected behavior**
The Bot should get a notification

This could just be a feature which is not implemented yet. I am trying to find out if this is possible or not.

**Comment by ksikorsk** [comment]
You have to use the chats APIs to get the chat.  The calling/online meetings API does not support chat.

To access chats you have a couple options:
https://docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&tabs=cs
https://dev.botframework.com/

I will not provide support for chat APIs here.

**Comment by saraswat40** [comment]
Thanks. However, the chat API is probably not realtime. We have a compliance usecase where when a user shares a file, we want to show them a notification.

**Comment by ksikorsk** [comment]
Please raise this with the chat folks... these samples and APIs are for calls/online meetings.

**Comment by saraswat40** [comment]
I raised this here because this is similar to the participant notifications that are sent to the bot, say when a camera is turned on or the user enabled screen sharing. I understand that this is currently not supported.
