### ISSUE TITLE
I received 500 Internal Server Error

### ISSUE THREAD

**Issue by poxiaosyb** [microsoftgraph/microsoft-graph-comms-samples#85]
**Describe the issue**
I configure and run the sample of IncidentBot,next I use post man send an request .
I received an 500 Internal Server Error later
**Code Snippet**
https://incidentbot20190610114013.azurewebsites.net/incidents/raise
{
    "name": "<name-of-incident>",
    "time": "<start-time-of-the-incident>",
    "tenantId": "{9d870035-8b64-4403-8099-4f955087c2c3}",
    "objectIds": [
        "{b537f455-42f0-4192-a462-d148c12ad1e4}",
        "{c2e8a526-09d1-4a37-8aef-f57ad84d7d2b}"
    ],

    "joinURL": "https://teams.microsoft.com/l/meetup-join/19:ca705ef0e85b455eb859ad1f72eeced7@thread.skype/1560737371070?context={"Tid":"9d870035-8b64-4403-8099-4f955087c2c3","Oid":"b537f455-42f0-4192-a462-d148c12ad1e4"}",
    "removeFromDefaultRoutingGroup": true,
    "allowConversationWithoutHost": true
}

**Expected behavior**
I want to run the example and see what happens

**Graph SDK (please complete the following information):**

**Call ID**

**Logs**
If required, please add [logs](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html) from the SDK. (Please remove any PII from the logs before uploading)

**Additional context**

**Comment by ksikorsk** [comment]
Why are your guids in curly braces? "{abc}"
you should remove the curly braces, those were only there to show the placeholder value.

**Comment by ksikorsk** [comment]
Your join URL should be json escaped, or URL encoded... the string you have  is not a valid json.  The raw url you get from the teams client should work.

**Comment by ksikorsk** [comment]
This is an example of a valid json payload:
```json
{
    "name": "<name-of-incident>",
    "time": "<start-time-of-the-incident>",
    "tenantId": "9d870035-8b64-4403-8099-4f955087c2c3",
    "objectIds": [
        "b537f455-42f0-4192-a462-d148c12ad1e4",
        "c2e8a526-09d1-4a37-8aef-f57ad84d7d2b"
    ],
    "joinURL": "https://teams.microsoft.com/l/meetup-join/19:ca705ef0e85b455eb859ad1f72eeced7@thread.skype/1560737371070?context=%7B%22Tid%22%3A%229d870035-8b64-4403-8099-4f955087c2c3%22%2C%22Oid%22%3A%22b537f455-42f0-4192-a462-d148c12ad1e4%22%7D",
    "removeFromDefaultRoutingGroup": true,
    "allowConversationWithoutHost": true
}
```

**Comment by poxiaosyb** [comment]
thanks for your help,but  I removed the curly braces and still got an error 500.

**Comment by ksikorsk** [comment]
is your joinUrl encoded?

**Comment by poxiaosyb** [comment]
This is my joinUrl:  https://teams.microsoft.com/l/meetup-join/19:5f93bdb5ee79402d835c631602524f89@thread.skype/1560753737944?context={"Tid":"0047ccf9-5d9c-4cb8-8400-4d669fc05f62","Oid":"9def9696-ceab-4ccd-8d85-8e72f02feeae"}

**Comment by ksikorsk** [comment]
That is not a valid URL to put into a json payload.  please look at the sample I provided above.

**Comment by poxiaosyb** [comment]
Thank you very much for your help .
