### ISSUE TITLE
Call notifications

### ISSUE THREAD

**Issue by stefan2410** [microsoftgraph/microsoft-graph-comms-samples#88]
How a bot  using the Graph Calling API can get incoming call notifications only  and who answered the call eventually in real time?  
Is there another way using webhooks?

**Comment by ksikorsk** [comment]
Let me make sure I understand your question.  You're asking how a bot could register for incoming call notifications, and you want to know who joined the call?

For incoming call notifications we only support the web hook.  For knowing who answered the call, in a P2P call it is the bot.  In a multiparty call, we provide the roster, but that does not say if the participants were invited to the call, or joined by themselves.

**Comment by stefan2410** [comment]
1. A bot could register for incoming call notifications.   Yes.
Documentation is not clear to me.  I assume using the Calling SDK to register a stateful bot for calls without to answer them? I'm confused about the webhook , can you point out the specific documentation?
2. In a P2P call,  how the bot will know who answered the call, if it does not redirect/transfer the call.  If it was registered to incoming calls, only to get the notifications? 
I'm coming from S4B background-UCMA.

**Comment by ksikorsk** [comment]
1) Each sample has directions on how to get it set up, including [Registration](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/BetaSamples/RemoteMediaSamples#bot-registration) instructions.

2) The architecture in Teams is different than S4B.  The bot counts as a participant.  In a P2P call with a bot, there is only 1 other participant.  The bot is the other participant.  The bot can place a P2P call to another participant, and in this case the other participant answered/rejected the call.  If the bot was the recipient of an incoming P2P call then it is the one that answered/rejected the call.

For mutliparty calls, we provide the roster, which gives you notifications when participants are entering/leaving the meeting.  We have no mechanism today to join a meeting without media.

**Comment by ksikorsk** [comment]
Look at this documentation, it renders the images correctly:
https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta

**Comment by stefan2410** [comment]
What if the call was redirected to a group and we don't know the user who answered it?

**Comment by ksikorsk** [comment]
The `Call` has an `AnsweredBy` [property](https://docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta#properties), but it is not yet supported in the case of Redirect/Transfer.  @VinodRavichandran as FYI.

**Comment by stefan2410** [comment]
Do you have a plan for this release?  GA end of Q3?
What about webhooks? Is there a way to get incoming call notifications-answered by, without to register a bot using the Calling API?

**Comment by ksikorsk** [comment]
There is no mechanism today to get incoming call notifications without registering a bot.  @VinodRavichandran would have to speak to our release plan.  

What is the scenario you're looking to build?

**Comment by stefan2410** [comment]
Register the  bot using the Calling API for incoming PSTN calls. If there is no other way to get notifications, then to redirect the call in the specific group. then get the information for the user answered actually the call.

**Comment by ksikorsk** [comment]
You can do this today by having the bot manage multiple P2P calls (one inbound and x outbound), then transfer to the first agent that answers and terminate all the remaining ones.  It's not as efficient as having a single API that does it all under the hood, but it is possible.

**Comment by stefan2410** [comment]
B2B calls like UCMA.   maybe not so efficient but does it has overhead?

**Comment by stefan2410** [comment]
@ksikorsk  do you have a sample related to your suggesion " the bot manage multiple P2P calls (one inbound and x outbound),then transfer to the first agent that answers and terminate all the remaining ones"

**Comment by ksikorsk** [comment]
Best we have is the `IncidentBot` which supports incoming call, places calls to users, and plays prompts.
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/BetaSamples/RemoteMediaSamples

**Comment by stefan2410** [comment]
@ksikorsk
You closed the issue, but I still did not have an answer about  the AnsweredBy property from @VinodRavichandran 
Do you think my scenario is not important for a small contact center ? 

> The `Call` has an `AnsweredBy` [property](https://docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta#properties), but it is not yet supported in the case of Redirect/Transfer. @VinodRavichandran as FYI.

**Comment by ksikorsk** [comment]
Can you please open another issue specific to the outstanding question?

**Comment by stefan2410** [comment]
OK
