### ISSUE TITLE
Media Plattform to use certificates from the Azure Key Vault

### ISSUE THREAD

**Issue by martenekblad** [microsoftgraph/microsoft-graph-comms-samples#89]
When initiating the Media Plattform (by calling  MediaPlatform.Initialize) the certificate used for the Media Platform's WCF service endpoint is given in the form of a thumbprint. The media platform will then read the cert from local cert store on the server. This makes it more complicated to use Azure Key Vault for cert storage. 

A preferred way would be to have an option to let the consumer read the cert from any source.

**Comment by ksikorsk** [comment]
@ssulzer FYI

**Comment by ssulzer** [comment]
The Media Platform expects to load the bot's certificate from the local machine cert store, but you should be able to use Azure Key Vault to provision the VM with a certificate.

https://blogs.technet.microsoft.com/kv/2016/09/14/updated-deploy-certificates-to-vms-from-customer-managed-key-vault/
