### ISSUE TITLE
Trying to understand the AudioVideoSample

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#94]
**Describe the issue**
I am trying to understand how the audiovideo sample works.

I believe the joincall request ends up here and the control flow looks like this:
JoinCallController.cs > JoinCallAsync:
`var call = await Bot.Instance.JoinCallAsync(joinCallBody).ConfigureAwait(false);`
Bot.cs:
`var statefulCall = await this.Client.Calls().AddAsync(joinParams, scenarioId).ConfigureAwait(false);`
CallCollectionExtensions.cs:
`return callCollection.AddAsync(call, parameters.MediaSession, parameters.RemoveFromDefaultAudioRoutingGroup, scenarioId, cancellationToken);`
ICallCollection.cs:
`Task<ICall> AddAsync(Call resource, IMediaSession mediaSession = null, bool? removeFromDefaultRoutingGroup = false, Guid scenarioId = default(Guid), CancellationToken cancellationToken = default(CancellationToken));`
   

I can't find out the source for the class that implements ICallCollection.cs.

Is this closed source? If not, can you please point me in the right direction?

**Comment by ksikorsk** [comment]
The SDK is closed source.  We do have a [request to open source the SDK](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/52), but have not yet done so.  At this point I don't have a solid timeline as to when that will happen.  

Here are some pointers to understand the sample:
- Deploy (or set up locally) and try it out.
  - All the instructions should be in the [LocalMediaSamples folder](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples) and in the [AudioVideoPlaybackBot folder](https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/AudioVideoPlaybackBot)
- Review the logs for a given call at https://your.app.url/logs/{callId}.  The logs will show you:
  - What http requests are being made by the SDK and what notifications the SDK has processed.  This should match with our [API documentation](https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta)
  - Your instance specific URIs and the media tcp URIs... useful for troubleshooting whether the right "instance" is getting your requests.
- Review the [SDK documentation](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/) and the [documentation for ICallCollection](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/calls/Microsoft.Graph.Communications.Calls.ICallCollection.html#Microsoft_Graph_Communications_Calls_ICallCollection_AddAsync_Microsoft_Graph_Call_Microsoft_Graph_Communications_Calls_IMediaSession_System_Nullable_System_Boolean__System_Guid_System_Threading_CancellationToken_) and the [ICallCollection extensions](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/calls/Microsoft.Graph.Communications.Calls.CallCollectionExtensions.html#Microsoft_Graph_Communications_Calls_CallCollectionExtensions_AddAsync_Microsoft_Graph_Communications_Calls_ICallCollection_Microsoft_Graph_Communications_Calls_JoinMeetingParameters_System_Guid_System_Threading_CancellationToken_)

If you have any specific questions, you can also ask here :)

**Comment by saraswat40** [comment]
Got it. Thanks
