### ISSUE TITLE
Exception POSTing to AudioVideoPlaybackBot

### ISSUE THREAD

**Issue by simra** [microsoftgraph/microsoft-graph-comms-samples#96]
**Describe the issue**
I have deployed the AudioVideoPlaybackBot to an azure instance without any revisions to the code, aside from config. When I submit a POST request to the JoinCall route, the service returns an exception in the message body (see below).

**Code Snippet**
````
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: clientCallbackError
Message: Unexpected exception happened on client when authenticating request.
Scenario Id: 46b2df76-cb9b-4919-b349-4efbba79b2ea
 ---> Microsoft.Graph.Communications.Core.Exceptions.ClientException: Code: clientCallbackError
Message: Unexpected exception happened on client when authenticating request.
 ---> System.BadImageFormatException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at Sample.Common.Authentication.AuthenticationProvider.AuthenticateOutboundRequestAsync(HttpRequestMessage request, String tenant)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
````

**Expected behavior**
Bot should successfully join the call.

**Graph SDK (please complete the following information):**
 - Graph.Communications nugets are all V1.1.0-prerelease.581.  I'm not sure if this is the same as the Graph SDK.

**Call ID**
Join Url: https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjYxMmUzNmQtMDMxMy00Mzc0LTlhMzMtMTZjY2E1MTM2ZTc1%40thread.v2/0?context=%7b%22Tid%22%3a%22e4f0d009-006e-474f-a3a9-f7b80ffd9534%22%2c%22Oid%22%3a%22240bda36-4529-41a3-8ca6-d507f629e56f%22%7d

**Logs**
No logs collected. 

**Additional context**

**Comment by sunyuboalisa** [comment]
I also met the same problem.

**Comment by ksikorsk** [comment]
Thanks for reaching out folks.  We seem to be having issues with the recent update to MSAL libraries.  Trying to work through it.  If you by any chance troubleshoot the issue please do let us know.

**Comment by simra** [comment]
Thanks @ksikorsk, I'm not sure whether it's relevant but I see this delay-signing warning in the build output: 
````
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets(3039,5): warning : CloudServices49 : The assembly 'Microsoft.Identity.Client.dll' is delay-signed.
````

**Comment by ksikorsk** [comment]
As a temporary measure, if you load this changelist the samples should work:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/commit/3eb960ae62bb6e94b9906572bdbe39fa9b444be2

Last 2 checkins are the culprits.

**Comment by ksikorsk** [comment]
Hey folks... we resolved the exception.  Thanks for your patience:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/pull/98
